-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_Block_split7796_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    D_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    D_empty_n : IN STD_LOGIC;
    D_read : OUT STD_LOGIC;
    IC_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    IC_empty_n : IN STD_LOGIC;
    IC_read : OUT STD_LOGIC;
    OC_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    OC_empty_n : IN STD_LOGIC;
    OC_read : OUT STD_LOGIC;
    batch_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    batch_empty_n : IN STD_LOGIC;
    batch_read : OUT STD_LOGIC;
    batch_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    batch_out_full_n : IN STD_LOGIC;
    batch_out_write : OUT STD_LOGIC;
    batch_out1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    batch_out1_full_n : IN STD_LOGIC;
    batch_out1_write : OUT STD_LOGIC;
    D_V_out_out_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    D_V_out_out_full_n : IN STD_LOGIC;
    D_V_out_out_write : OUT STD_LOGIC;
    D_V_out_out2_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    D_V_out_out2_full_n : IN STD_LOGIC;
    D_V_out_out2_write : OUT STD_LOGIC;
    IC_V_out_out_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    IC_V_out_out_full_n : IN STD_LOGIC;
    IC_V_out_out_write : OUT STD_LOGIC;
    OC_V_out_out_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    OC_V_out_out_full_n : IN STD_LOGIC;
    OC_V_out_out_write : OUT STD_LOGIC;
    OC_V_out_out3_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    OC_V_out_out3_full_n : IN STD_LOGIC;
    OC_V_out_out3_write : OUT STD_LOGIC;
    ret_V_1_out_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    ret_V_1_out_out_full_n : IN STD_LOGIC;
    ret_V_1_out_out_write : OUT STD_LOGIC;
    ret_V_1_out_out4_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    ret_V_1_out_out4_full_n : IN STD_LOGIC;
    ret_V_1_out_out4_write : OUT STD_LOGIC;
    mul_ln31_1_out_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    mul_ln31_1_out_out_full_n : IN STD_LOGIC;
    mul_ln31_1_out_out_write : OUT STD_LOGIC;
    mul_ln31_1_out_out5_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    mul_ln31_1_out_out5_full_n : IN STD_LOGIC;
    mul_ln31_1_out_out5_write : OUT STD_LOGIC;
    mul_ln31_1_out_out6_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    mul_ln31_1_out_out6_full_n : IN STD_LOGIC;
    mul_ln31_1_out_out6_write : OUT STD_LOGIC;
    ret_V_cast_out_out_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    ret_V_cast_out_out_full_n : IN STD_LOGIC;
    ret_V_cast_out_out_write : OUT STD_LOGIC;
    ret_V_cast_out_out7_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    ret_V_cast_out_out7_full_n : IN STD_LOGIC;
    ret_V_cast_out_out7_write : OUT STD_LOGIC;
    ret_V_cast_out_out8_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    ret_V_cast_out_out8_full_n : IN STD_LOGIC;
    ret_V_cast_out_out8_write : OUT STD_LOGIC;
    ret_V_cast_out_out9_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    ret_V_cast_out_out9_full_n : IN STD_LOGIC;
    ret_V_cast_out_out9_write : OUT STD_LOGIC;
    ret_V_cast_out_out10_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    ret_V_cast_out_out10_full_n : IN STD_LOGIC;
    ret_V_cast_out_out10_write : OUT STD_LOGIC );
end;


architecture behav of top_Block_split7796_proc is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal D_blk_n : STD_LOGIC;
    signal IC_blk_n : STD_LOGIC;
    signal OC_blk_n : STD_LOGIC;
    signal batch_blk_n : STD_LOGIC;
    signal batch_out_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal batch_out1_blk_n : STD_LOGIC;
    signal D_V_out_out_blk_n : STD_LOGIC;
    signal D_V_out_out2_blk_n : STD_LOGIC;
    signal IC_V_out_out_blk_n : STD_LOGIC;
    signal OC_V_out_out_blk_n : STD_LOGIC;
    signal OC_V_out_out3_blk_n : STD_LOGIC;
    signal ret_V_1_out_out_blk_n : STD_LOGIC;
    signal ret_V_1_out_out4_blk_n : STD_LOGIC;
    signal mul_ln31_1_out_out_blk_n : STD_LOGIC;
    signal mul_ln31_1_out_out5_blk_n : STD_LOGIC;
    signal mul_ln31_1_out_out6_blk_n : STD_LOGIC;
    signal ret_V_cast_out_out_blk_n : STD_LOGIC;
    signal ret_V_cast_out_out7_blk_n : STD_LOGIC;
    signal ret_V_cast_out_out8_blk_n : STD_LOGIC;
    signal ret_V_cast_out_out9_blk_n : STD_LOGIC;
    signal ret_V_cast_out_out10_blk_n : STD_LOGIC;
    signal batch_read_reg_263 : STD_LOGIC_VECTOR (31 downto 0);
    signal D_V_fu_213_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal D_V_reg_270 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln31_fu_217_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal IC_V_fu_221_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal IC_V_reg_282 : STD_LOGIC_VECTOR (15 downto 0);
    signal OC_V_fu_225_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal OC_V_reg_288 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_reg_295 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_249_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln31_reg_304 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_fu_239_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal mul_ln31_1_reg_319 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_state10 : BOOLEAN;
    signal grp_fu_255_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_fu_249_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_249_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_255_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_255_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_249_ce : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_fu_255_ce : STD_LOGIC;
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal grp_fu_255_p00 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_255_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component top_mul_32s_32s_32_5_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component top_mul_mul_16ns_16ns_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    mul_32s_32s_32_5_1_U114 : component top_mul_32s_32s_32_5_1
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => mul_ln31_reg_304,
        din1 => batch_read_reg_263,
        ce => ap_const_logic_1,
        dout => grp_fu_239_p2);

    mul_mul_16ns_16ns_32_4_1_U115 : component top_mul_mul_16ns_16ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_249_p0,
        din1 => grp_fu_249_p1,
        ce => grp_fu_249_ce,
        dout => grp_fu_249_p2);

    mul_mul_16ns_16ns_32_4_1_U116 : component top_mul_mul_16ns_16ns_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_255_p0,
        din1 => grp_fu_255_p1,
        ce => grp_fu_255_ce,
        dout => grp_fu_255_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                D_V_reg_270 <= D_V_fu_213_p1;
                IC_V_reg_282 <= IC_V_fu_221_p1;
                OC_V_reg_288 <= OC_V_fu_225_p1;
                batch_read_reg_263 <= batch_dout;
                trunc_ln_reg_295 <= OC_dout(15 downto 4);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                mul_ln31_1_reg_319 <= grp_fu_239_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                mul_ln31_reg_304 <= grp_fu_249_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, D_empty_n, IC_empty_n, OC_empty_n, batch_empty_n, batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((batch_empty_n = ap_const_logic_0) or (ap_const_logic_0 = OC_empty_n) or (ap_const_logic_0 = IC_empty_n) or (ap_const_logic_0 = D_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    D_V_fu_213_p1 <= D_dout(16 - 1 downto 0);

    D_V_out_out2_blk_n_assign_proc : process(D_V_out_out2_full_n, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            D_V_out_out2_blk_n <= D_V_out_out2_full_n;
        else 
            D_V_out_out2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    D_V_out_out2_din <= D_V_reg_270;

    D_V_out_out2_write_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            D_V_out_out2_write <= ap_const_logic_1;
        else 
            D_V_out_out2_write <= ap_const_logic_0;
        end if; 
    end process;


    D_V_out_out_blk_n_assign_proc : process(D_V_out_out_full_n, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            D_V_out_out_blk_n <= D_V_out_out_full_n;
        else 
            D_V_out_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    D_V_out_out_din <= D_V_reg_270;

    D_V_out_out_write_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            D_V_out_out_write <= ap_const_logic_1;
        else 
            D_V_out_out_write <= ap_const_logic_0;
        end if; 
    end process;


    D_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, D_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            D_blk_n <= D_empty_n;
        else 
            D_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    D_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, D_empty_n, IC_empty_n, OC_empty_n, batch_empty_n)
    begin
        if ((not(((batch_empty_n = ap_const_logic_0) or (ap_const_logic_0 = OC_empty_n) or (ap_const_logic_0 = IC_empty_n) or (ap_const_logic_0 = D_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            D_read <= ap_const_logic_1;
        else 
            D_read <= ap_const_logic_0;
        end if; 
    end process;

    IC_V_fu_221_p1 <= IC_dout(16 - 1 downto 0);

    IC_V_out_out_blk_n_assign_proc : process(IC_V_out_out_full_n, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            IC_V_out_out_blk_n <= IC_V_out_out_full_n;
        else 
            IC_V_out_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    IC_V_out_out_din <= IC_V_reg_282;

    IC_V_out_out_write_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            IC_V_out_out_write <= ap_const_logic_1;
        else 
            IC_V_out_out_write <= ap_const_logic_0;
        end if; 
    end process;


    IC_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, IC_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            IC_blk_n <= IC_empty_n;
        else 
            IC_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    IC_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, D_empty_n, IC_empty_n, OC_empty_n, batch_empty_n)
    begin
        if ((not(((batch_empty_n = ap_const_logic_0) or (ap_const_logic_0 = OC_empty_n) or (ap_const_logic_0 = IC_empty_n) or (ap_const_logic_0 = D_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            IC_read <= ap_const_logic_1;
        else 
            IC_read <= ap_const_logic_0;
        end if; 
    end process;

    OC_V_fu_225_p1 <= OC_dout(16 - 1 downto 0);

    OC_V_out_out3_blk_n_assign_proc : process(OC_V_out_out3_full_n, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            OC_V_out_out3_blk_n <= OC_V_out_out3_full_n;
        else 
            OC_V_out_out3_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    OC_V_out_out3_din <= OC_V_reg_288;

    OC_V_out_out3_write_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            OC_V_out_out3_write <= ap_const_logic_1;
        else 
            OC_V_out_out3_write <= ap_const_logic_0;
        end if; 
    end process;


    OC_V_out_out_blk_n_assign_proc : process(OC_V_out_out_full_n, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            OC_V_out_out_blk_n <= OC_V_out_out_full_n;
        else 
            OC_V_out_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    OC_V_out_out_din <= OC_V_reg_288;

    OC_V_out_out_write_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            OC_V_out_out_write <= ap_const_logic_1;
        else 
            OC_V_out_out_write <= ap_const_logic_0;
        end if; 
    end process;


    OC_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, OC_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            OC_blk_n <= OC_empty_n;
        else 
            OC_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    OC_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, D_empty_n, IC_empty_n, OC_empty_n, batch_empty_n)
    begin
        if ((not(((batch_empty_n = ap_const_logic_0) or (ap_const_logic_0 = OC_empty_n) or (ap_const_logic_0 = IC_empty_n) or (ap_const_logic_0 = D_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            OC_read <= ap_const_logic_1;
        else 
            OC_read <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_block_state1_assign_proc : process(real_start, ap_done_reg, D_empty_n, IC_empty_n, OC_empty_n, batch_empty_n)
    begin
                ap_block_state1 <= ((batch_empty_n = ap_const_logic_0) or (ap_const_logic_0 = OC_empty_n) or (ap_const_logic_0 = IC_empty_n) or (ap_const_logic_0 = D_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;


    ap_block_state10_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n)
    begin
                ap_block_state10 <= ((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    batch_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, batch_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            batch_blk_n <= batch_empty_n;
        else 
            batch_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    batch_out1_blk_n_assign_proc : process(batch_out1_full_n, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            batch_out1_blk_n <= batch_out1_full_n;
        else 
            batch_out1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    batch_out1_din <= batch_read_reg_263;

    batch_out1_write_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            batch_out1_write <= ap_const_logic_1;
        else 
            batch_out1_write <= ap_const_logic_0;
        end if; 
    end process;


    batch_out_blk_n_assign_proc : process(batch_out_full_n, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            batch_out_blk_n <= batch_out_full_n;
        else 
            batch_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    batch_out_din <= batch_read_reg_263;

    batch_out_write_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            batch_out_write <= ap_const_logic_1;
        else 
            batch_out_write <= ap_const_logic_0;
        end if; 
    end process;


    batch_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, D_empty_n, IC_empty_n, OC_empty_n, batch_empty_n)
    begin
        if ((not(((batch_empty_n = ap_const_logic_0) or (ap_const_logic_0 = OC_empty_n) or (ap_const_logic_0 = IC_empty_n) or (ap_const_logic_0 = D_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            batch_read <= ap_const_logic_1;
        else 
            batch_read <= ap_const_logic_0;
        end if; 
    end process;


    grp_fu_249_ce_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, D_empty_n, IC_empty_n, OC_empty_n, batch_empty_n, ap_CS_fsm_state4, ap_CS_fsm_state2, ap_CS_fsm_state3)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2) or (ap_const_logic_1 = ap_CS_fsm_state4) or (not(((batch_empty_n = ap_const_logic_0) or (ap_const_logic_0 = OC_empty_n) or (ap_const_logic_0 = IC_empty_n) or (ap_const_logic_0 = D_empty_n) or (ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            grp_fu_249_ce <= ap_const_logic_1;
        else 
            grp_fu_249_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_249_p0 <= zext_ln31_fu_217_p1(16 - 1 downto 0);
    grp_fu_249_p1 <= zext_ln31_fu_217_p1(16 - 1 downto 0);

    grp_fu_255_ce_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10, ap_CS_fsm_state7, ap_CS_fsm_state9, ap_CS_fsm_state8)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state7) or (not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10)))) then 
            grp_fu_255_ce <= ap_const_logic_1;
        else 
            grp_fu_255_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_255_p0 <= grp_fu_255_p00(16 - 1 downto 0);
    grp_fu_255_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(OC_V_reg_288),32));
    grp_fu_255_p1 <= grp_fu_255_p10(16 - 1 downto 0);
    grp_fu_255_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(IC_V_reg_282),32));

    internal_ap_ready_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    mul_ln31_1_out_out5_blk_n_assign_proc : process(mul_ln31_1_out_out5_full_n, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            mul_ln31_1_out_out5_blk_n <= mul_ln31_1_out_out5_full_n;
        else 
            mul_ln31_1_out_out5_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    mul_ln31_1_out_out5_din <= mul_ln31_1_reg_319;

    mul_ln31_1_out_out5_write_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            mul_ln31_1_out_out5_write <= ap_const_logic_1;
        else 
            mul_ln31_1_out_out5_write <= ap_const_logic_0;
        end if; 
    end process;


    mul_ln31_1_out_out6_blk_n_assign_proc : process(mul_ln31_1_out_out6_full_n, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            mul_ln31_1_out_out6_blk_n <= mul_ln31_1_out_out6_full_n;
        else 
            mul_ln31_1_out_out6_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    mul_ln31_1_out_out6_din <= mul_ln31_1_reg_319;

    mul_ln31_1_out_out6_write_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            mul_ln31_1_out_out6_write <= ap_const_logic_1;
        else 
            mul_ln31_1_out_out6_write <= ap_const_logic_0;
        end if; 
    end process;


    mul_ln31_1_out_out_blk_n_assign_proc : process(mul_ln31_1_out_out_full_n, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            mul_ln31_1_out_out_blk_n <= mul_ln31_1_out_out_full_n;
        else 
            mul_ln31_1_out_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    mul_ln31_1_out_out_din <= mul_ln31_1_reg_319;

    mul_ln31_1_out_out_write_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            mul_ln31_1_out_out_write <= ap_const_logic_1;
        else 
            mul_ln31_1_out_out_write <= ap_const_logic_0;
        end if; 
    end process;


    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    ret_V_1_out_out4_blk_n_assign_proc : process(ret_V_1_out_out4_full_n, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            ret_V_1_out_out4_blk_n <= ret_V_1_out_out4_full_n;
        else 
            ret_V_1_out_out4_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ret_V_1_out_out4_din <= grp_fu_255_p2;

    ret_V_1_out_out4_write_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ret_V_1_out_out4_write <= ap_const_logic_1;
        else 
            ret_V_1_out_out4_write <= ap_const_logic_0;
        end if; 
    end process;


    ret_V_1_out_out_blk_n_assign_proc : process(ret_V_1_out_out_full_n, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            ret_V_1_out_out_blk_n <= ret_V_1_out_out_full_n;
        else 
            ret_V_1_out_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ret_V_1_out_out_din <= grp_fu_255_p2;

    ret_V_1_out_out_write_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ret_V_1_out_out_write <= ap_const_logic_1;
        else 
            ret_V_1_out_out_write <= ap_const_logic_0;
        end if; 
    end process;


    ret_V_cast_out_out10_blk_n_assign_proc : process(ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            ret_V_cast_out_out10_blk_n <= ret_V_cast_out_out10_full_n;
        else 
            ret_V_cast_out_out10_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ret_V_cast_out_out10_din <= trunc_ln_reg_295;

    ret_V_cast_out_out10_write_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ret_V_cast_out_out10_write <= ap_const_logic_1;
        else 
            ret_V_cast_out_out10_write <= ap_const_logic_0;
        end if; 
    end process;


    ret_V_cast_out_out7_blk_n_assign_proc : process(ret_V_cast_out_out7_full_n, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            ret_V_cast_out_out7_blk_n <= ret_V_cast_out_out7_full_n;
        else 
            ret_V_cast_out_out7_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ret_V_cast_out_out7_din <= trunc_ln_reg_295;

    ret_V_cast_out_out7_write_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ret_V_cast_out_out7_write <= ap_const_logic_1;
        else 
            ret_V_cast_out_out7_write <= ap_const_logic_0;
        end if; 
    end process;


    ret_V_cast_out_out8_blk_n_assign_proc : process(ret_V_cast_out_out8_full_n, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            ret_V_cast_out_out8_blk_n <= ret_V_cast_out_out8_full_n;
        else 
            ret_V_cast_out_out8_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ret_V_cast_out_out8_din <= trunc_ln_reg_295;

    ret_V_cast_out_out8_write_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ret_V_cast_out_out8_write <= ap_const_logic_1;
        else 
            ret_V_cast_out_out8_write <= ap_const_logic_0;
        end if; 
    end process;


    ret_V_cast_out_out9_blk_n_assign_proc : process(ret_V_cast_out_out9_full_n, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            ret_V_cast_out_out9_blk_n <= ret_V_cast_out_out9_full_n;
        else 
            ret_V_cast_out_out9_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ret_V_cast_out_out9_din <= trunc_ln_reg_295;

    ret_V_cast_out_out9_write_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ret_V_cast_out_out9_write <= ap_const_logic_1;
        else 
            ret_V_cast_out_out9_write <= ap_const_logic_0;
        end if; 
    end process;


    ret_V_cast_out_out_blk_n_assign_proc : process(ret_V_cast_out_out_full_n, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            ret_V_cast_out_out_blk_n <= ret_V_cast_out_out_full_n;
        else 
            ret_V_cast_out_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ret_V_cast_out_out_din <= trunc_ln_reg_295;

    ret_V_cast_out_out_write_assign_proc : process(batch_out_full_n, batch_out1_full_n, D_V_out_out_full_n, D_V_out_out2_full_n, IC_V_out_out_full_n, OC_V_out_out_full_n, OC_V_out_out3_full_n, ret_V_1_out_out_full_n, ret_V_1_out_out4_full_n, mul_ln31_1_out_out_full_n, mul_ln31_1_out_out5_full_n, mul_ln31_1_out_out6_full_n, ret_V_cast_out_out_full_n, ret_V_cast_out_out7_full_n, ret_V_cast_out_out8_full_n, ret_V_cast_out_out9_full_n, ret_V_cast_out_out10_full_n, ap_CS_fsm_state10)
    begin
        if ((not(((ret_V_1_out_out4_full_n = ap_const_logic_0) or (ret_V_1_out_out_full_n = ap_const_logic_0) or (batch_out1_full_n = ap_const_logic_0) or (batch_out_full_n = ap_const_logic_0) or (ap_const_logic_0 = OC_V_out_out3_full_n) or (ap_const_logic_0 = OC_V_out_out_full_n) or (ap_const_logic_0 = IC_V_out_out_full_n) or (ap_const_logic_0 = D_V_out_out2_full_n) or (ap_const_logic_0 = D_V_out_out_full_n) or (ret_V_cast_out_out10_full_n = ap_const_logic_0) or (ret_V_cast_out_out9_full_n = ap_const_logic_0) or (ret_V_cast_out_out8_full_n = ap_const_logic_0) or (ret_V_cast_out_out7_full_n = ap_const_logic_0) or (ret_V_cast_out_out_full_n = ap_const_logic_0) or (mul_ln31_1_out_out6_full_n = ap_const_logic_0) or (mul_ln31_1_out_out5_full_n = ap_const_logic_0) or (mul_ln31_1_out_out_full_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ret_V_cast_out_out_write <= ap_const_logic_1;
        else 
            ret_V_cast_out_out_write <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln31_fu_217_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(D_V_fu_213_p1),32));
end behav;
