// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_quantize_mul_shift_24_8_16_16_16_16_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_conv3_dout,
        s_conv3_empty_n,
        s_conv3_read,
        f3_din,
        f3_full_n,
        f3_write,
        s_scale_1_dout,
        s_scale_1_empty_n,
        s_scale_1_read,
        s_bias_1_dout,
        s_bias_1_empty_n,
        s_bias_1_read,
        mul_ln93_1_loc_dout,
        mul_ln93_1_loc_empty_n,
        mul_ln93_1_loc_read,
        OC_V_loc_dout,
        OC_V_loc_empty_n,
        OC_V_loc_read,
        skip3_dout,
        skip3_empty_n,
        skip3_read,
        relu3_dout,
        relu3_empty_n,
        relu3_read
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_pp0_stage0 = 8'd64;
parameter    ap_ST_fsm_state15 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [511:0] s_conv3_dout;
input   s_conv3_empty_n;
output   s_conv3_read;
output  [127:0] f3_din;
input   f3_full_n;
output   f3_write;
input  [255:0] s_scale_1_dout;
input   s_scale_1_empty_n;
output   s_scale_1_read;
input  [255:0] s_bias_1_dout;
input   s_bias_1_empty_n;
output   s_bias_1_read;
input  [31:0] mul_ln93_1_loc_dout;
input   mul_ln93_1_loc_empty_n;
output   mul_ln93_1_loc_read;
input  [15:0] OC_V_loc_dout;
input   OC_V_loc_empty_n;
output   OC_V_loc_read;
input  [0:0] skip3_dout;
input   skip3_empty_n;
output   skip3_read;
input  [0:0] relu3_dout;
input   relu3_empty_n;
output   relu3_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg s_conv3_read;
reg[127:0] f3_din;
reg f3_write;
reg s_scale_1_read;
reg s_bias_1_read;
reg mul_ln93_1_loc_read;
reg OC_V_loc_read;
reg skip3_read;
reg relu3_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    s_conv3_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg    f3_blk_n;
reg   [0:0] skip_reg_3161;
reg    ap_enable_reg_pp0_iter7;
reg    s_scale_1_blk_n;
reg    s_bias_1_blk_n;
reg    mul_ln93_1_loc_blk_n;
reg    OC_V_loc_blk_n;
reg    skip3_blk_n;
reg    relu3_blk_n;
reg   [43:0] indvar_flatten_reg_283;
reg   [0:0] relu_reg_3165;
reg   [31:0] rep_reg_3185;
reg   [11:0] ret_cast_reg_3190;
wire    ap_CS_fsm_state2;
wire   [43:0] grp_fu_310_p2;
reg   [43:0] bound_reg_3205;
wire    ap_CS_fsm_state6;
wire   [43:0] add_ln272_fu_316_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state7_pp0_stage0_iter0;
reg    ap_block_state8_pp0_stage0_iter1;
wire    ap_block_state9_pp0_stage0_iter2;
wire    ap_block_state10_pp0_stage0_iter3;
wire    ap_block_state11_pp0_stage0_iter4;
wire    ap_block_state12_pp0_stage0_iter5;
wire    ap_block_state13_pp0_stage0_iter6;
reg    ap_block_state14_pp0_stage0_iter7;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln272_fu_322_p2;
wire  signed [15:0] trunc_ln674_2_fu_485_p1;
reg  signed [15:0] trunc_ln674_2_reg_3219;
reg  signed [15:0] trunc_ln674_2_reg_3219_pp0_iter2_reg;
reg  signed [15:0] trunc_ln674_2_reg_3219_pp0_iter3_reg;
reg  signed [15:0] trunc_ln674_2_reg_3219_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_1_i_i_reg_3235;
reg  signed [15:0] p_Result_2_1_i_i_reg_3235_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_1_i_i_reg_3235_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_1_i_i_reg_3235_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_2_i_i_reg_3251;
reg  signed [15:0] p_Result_2_2_i_i_reg_3251_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_2_i_i_reg_3251_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_2_i_i_reg_3251_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_3_i_i_reg_3267;
reg  signed [15:0] p_Result_2_3_i_i_reg_3267_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_3_i_i_reg_3267_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_3_i_i_reg_3267_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_4_i_i_reg_3283;
reg  signed [15:0] p_Result_2_4_i_i_reg_3283_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_4_i_i_reg_3283_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_4_i_i_reg_3283_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_5_i_i_reg_3299;
reg  signed [15:0] p_Result_2_5_i_i_reg_3299_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_5_i_i_reg_3299_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_5_i_i_reg_3299_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_6_i_i_reg_3315;
reg  signed [15:0] p_Result_2_6_i_i_reg_3315_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_6_i_i_reg_3315_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_6_i_i_reg_3315_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_7_i_i_reg_3331;
reg  signed [15:0] p_Result_2_7_i_i_reg_3331_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_7_i_i_reg_3331_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_7_i_i_reg_3331_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_8_i_i_reg_3347;
reg  signed [15:0] p_Result_2_8_i_i_reg_3347_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_8_i_i_reg_3347_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_8_i_i_reg_3347_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_9_i_i_reg_3363;
reg  signed [15:0] p_Result_2_9_i_i_reg_3363_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_9_i_i_reg_3363_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_9_i_i_reg_3363_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_i_i_reg_3379;
reg  signed [15:0] p_Result_2_i_i_reg_3379_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_i_i_reg_3379_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_i_i_reg_3379_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_10_i_i_reg_3395;
reg  signed [15:0] p_Result_2_10_i_i_reg_3395_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_10_i_i_reg_3395_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_10_i_i_reg_3395_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_11_i_i_reg_3411;
reg  signed [15:0] p_Result_2_11_i_i_reg_3411_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_11_i_i_reg_3411_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_11_i_i_reg_3411_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_12_i_i_reg_3427;
reg  signed [15:0] p_Result_2_12_i_i_reg_3427_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_12_i_i_reg_3427_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_12_i_i_reg_3427_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_13_i_i_reg_3443;
reg  signed [15:0] p_Result_2_13_i_i_reg_3443_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_13_i_i_reg_3443_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_13_i_i_reg_3443_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_14_i_i_reg_3459;
reg  signed [15:0] p_Result_2_14_i_i_reg_3459_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_14_i_i_reg_3459_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_14_i_i_reg_3459_pp0_iter4_reg;
reg   [23:0] p_Result_3_i_i_reg_3475;
reg   [22:0] tmp_reg_3480;
reg   [23:0] p_Result_3_1_i_i_reg_3485;
reg   [22:0] tmp_s_reg_3490;
reg   [23:0] p_Result_3_2_i_i_reg_3495;
reg   [22:0] tmp_15_reg_3500;
reg   [23:0] p_Result_3_3_i_i_reg_3505;
reg   [22:0] tmp_16_reg_3510;
reg   [23:0] p_Result_3_4_i_i_reg_3515;
reg   [22:0] tmp_17_reg_3520;
reg   [23:0] p_Result_3_5_i_i_reg_3525;
reg   [22:0] tmp_18_reg_3530;
reg   [23:0] p_Result_3_6_i_i_reg_3535;
reg   [22:0] tmp_19_reg_3540;
reg   [23:0] p_Result_3_7_i_i_reg_3545;
reg   [22:0] tmp_20_reg_3550;
reg   [23:0] p_Result_3_8_i_i_reg_3555;
reg   [22:0] tmp_21_reg_3560;
reg   [23:0] p_Result_3_9_i_i_reg_3565;
reg   [22:0] tmp_22_reg_3570;
reg   [23:0] p_Result_3_i_i_183_reg_3575;
reg   [22:0] tmp_23_reg_3580;
reg   [23:0] p_Result_3_10_i_i_reg_3585;
reg   [22:0] tmp_24_reg_3590;
reg   [23:0] p_Result_3_11_i_i_reg_3595;
reg   [22:0] tmp_25_reg_3600;
reg   [23:0] p_Result_3_12_i_i_reg_3605;
reg   [22:0] tmp_26_reg_3610;
reg   [23:0] p_Result_3_13_i_i_reg_3615;
reg   [22:0] tmp_27_reg_3620;
reg   [23:0] p_Result_3_14_i_i_reg_3625;
reg   [22:0] tmp_28_reg_3630;
wire   [23:0] select_ln263_fu_1432_p3;
reg   [23:0] select_ln263_reg_3635;
reg   [23:0] select_ln263_reg_3635_pp0_iter6_reg;
wire   [23:0] select_ln263_16_fu_1475_p3;
reg   [23:0] select_ln263_16_reg_3641;
reg   [23:0] select_ln263_16_reg_3641_pp0_iter6_reg;
wire   [23:0] select_ln263_17_fu_1518_p3;
reg   [23:0] select_ln263_17_reg_3647;
reg   [23:0] select_ln263_17_reg_3647_pp0_iter6_reg;
wire   [23:0] select_ln263_18_fu_1561_p3;
reg   [23:0] select_ln263_18_reg_3653;
reg   [23:0] select_ln263_18_reg_3653_pp0_iter6_reg;
wire   [23:0] select_ln263_19_fu_1604_p3;
reg   [23:0] select_ln263_19_reg_3659;
reg   [23:0] select_ln263_19_reg_3659_pp0_iter6_reg;
wire   [23:0] select_ln263_20_fu_1647_p3;
reg   [23:0] select_ln263_20_reg_3665;
reg   [23:0] select_ln263_20_reg_3665_pp0_iter6_reg;
wire   [23:0] select_ln263_21_fu_1690_p3;
reg   [23:0] select_ln263_21_reg_3671;
reg   [23:0] select_ln263_21_reg_3671_pp0_iter6_reg;
wire   [23:0] select_ln263_22_fu_1733_p3;
reg   [23:0] select_ln263_22_reg_3677;
reg   [23:0] select_ln263_22_reg_3677_pp0_iter6_reg;
wire   [23:0] select_ln263_23_fu_1776_p3;
reg   [23:0] select_ln263_23_reg_3683;
reg   [23:0] select_ln263_23_reg_3683_pp0_iter6_reg;
wire   [23:0] select_ln263_24_fu_1819_p3;
reg   [23:0] select_ln263_24_reg_3689;
reg   [23:0] select_ln263_24_reg_3689_pp0_iter6_reg;
wire   [23:0] select_ln263_25_fu_1862_p3;
reg   [23:0] select_ln263_25_reg_3695;
reg   [23:0] select_ln263_25_reg_3695_pp0_iter6_reg;
wire   [23:0] select_ln263_26_fu_1905_p3;
reg   [23:0] select_ln263_26_reg_3701;
reg   [23:0] select_ln263_26_reg_3701_pp0_iter6_reg;
wire   [23:0] select_ln263_27_fu_1948_p3;
reg   [23:0] select_ln263_27_reg_3707;
reg   [23:0] select_ln263_27_reg_3707_pp0_iter6_reg;
wire   [23:0] select_ln263_28_fu_1991_p3;
reg   [23:0] select_ln263_28_reg_3713;
reg   [23:0] select_ln263_28_reg_3713_pp0_iter6_reg;
wire   [23:0] select_ln263_29_fu_2034_p3;
reg   [23:0] select_ln263_29_reg_3719;
reg   [23:0] select_ln263_29_reg_3719_pp0_iter6_reg;
wire   [23:0] select_ln263_30_fu_2077_p3;
reg   [23:0] select_ln263_30_reg_3725;
reg   [23:0] select_ln263_30_reg_3725_pp0_iter6_reg;
wire   [0:0] icmp_ln886_fu_2099_p2;
reg   [0:0] icmp_ln886_reg_3731;
wire   [0:0] icmp_ln878_fu_2105_p2;
reg   [0:0] icmp_ln878_reg_3737;
wire   [0:0] icmp_ln886_16_fu_2126_p2;
reg   [0:0] icmp_ln886_16_reg_3742;
wire   [0:0] icmp_ln878_16_fu_2132_p2;
reg   [0:0] icmp_ln878_16_reg_3748;
wire   [0:0] icmp_ln886_17_fu_2153_p2;
reg   [0:0] icmp_ln886_17_reg_3753;
wire   [0:0] icmp_ln878_17_fu_2159_p2;
reg   [0:0] icmp_ln878_17_reg_3759;
wire   [0:0] icmp_ln886_18_fu_2180_p2;
reg   [0:0] icmp_ln886_18_reg_3764;
wire   [0:0] icmp_ln878_18_fu_2186_p2;
reg   [0:0] icmp_ln878_18_reg_3770;
wire   [0:0] icmp_ln886_19_fu_2207_p2;
reg   [0:0] icmp_ln886_19_reg_3775;
wire   [0:0] icmp_ln878_19_fu_2213_p2;
reg   [0:0] icmp_ln878_19_reg_3781;
wire   [0:0] icmp_ln886_20_fu_2234_p2;
reg   [0:0] icmp_ln886_20_reg_3786;
wire   [0:0] icmp_ln878_20_fu_2240_p2;
reg   [0:0] icmp_ln878_20_reg_3792;
wire   [0:0] icmp_ln886_21_fu_2261_p2;
reg   [0:0] icmp_ln886_21_reg_3797;
wire   [0:0] icmp_ln878_21_fu_2267_p2;
reg   [0:0] icmp_ln878_21_reg_3803;
wire   [0:0] icmp_ln886_22_fu_2288_p2;
reg   [0:0] icmp_ln886_22_reg_3808;
wire   [0:0] icmp_ln878_22_fu_2294_p2;
reg   [0:0] icmp_ln878_22_reg_3814;
wire   [0:0] icmp_ln886_23_fu_2315_p2;
reg   [0:0] icmp_ln886_23_reg_3819;
wire   [0:0] icmp_ln878_23_fu_2321_p2;
reg   [0:0] icmp_ln878_23_reg_3825;
wire   [0:0] icmp_ln886_24_fu_2342_p2;
reg   [0:0] icmp_ln886_24_reg_3830;
wire   [0:0] icmp_ln878_24_fu_2348_p2;
reg   [0:0] icmp_ln878_24_reg_3836;
wire   [0:0] icmp_ln886_25_fu_2369_p2;
reg   [0:0] icmp_ln886_25_reg_3841;
wire   [0:0] icmp_ln878_25_fu_2375_p2;
reg   [0:0] icmp_ln878_25_reg_3847;
wire   [0:0] icmp_ln886_26_fu_2396_p2;
reg   [0:0] icmp_ln886_26_reg_3852;
wire   [0:0] icmp_ln878_26_fu_2402_p2;
reg   [0:0] icmp_ln878_26_reg_3858;
wire   [0:0] icmp_ln886_27_fu_2423_p2;
reg   [0:0] icmp_ln886_27_reg_3863;
wire   [0:0] icmp_ln878_27_fu_2429_p2;
reg   [0:0] icmp_ln878_27_reg_3869;
wire   [0:0] icmp_ln886_28_fu_2450_p2;
reg   [0:0] icmp_ln886_28_reg_3874;
wire   [0:0] icmp_ln878_28_fu_2456_p2;
reg   [0:0] icmp_ln878_28_reg_3880;
wire   [0:0] icmp_ln886_29_fu_2477_p2;
reg   [0:0] icmp_ln886_29_reg_3885;
wire   [0:0] icmp_ln878_29_fu_2483_p2;
reg   [0:0] icmp_ln878_29_reg_3891;
wire   [0:0] icmp_ln886_30_fu_2504_p2;
reg   [0:0] icmp_ln886_30_reg_3896;
wire   [0:0] icmp_ln878_30_fu_2510_p2;
reg   [0:0] icmp_ln878_30_reg_3902;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state7;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_block_state1;
wire   [127:0] p_Result_i_i_fu_1071_p17;
reg    ap_block_pp0_stage0_01001;
wire   [127:0] p_Result_4_i_i_fu_2964_p17;
wire   [31:0] grp_fu_310_p0;
wire   [11:0] grp_fu_310_p1;
wire  signed [23:0] tmp_data_V_0_fu_327_p1;
wire  signed [15:0] trunc_ln674_fu_481_p1;
wire  signed [23:0] tmp_data_V_1_fu_331_p4;
wire  signed [15:0] p_Result_1_1_i_i_fu_497_p4;
wire  signed [23:0] tmp_data_V_2_fu_341_p4;
wire  signed [15:0] p_Result_1_2_i_i_fu_525_p4;
wire  signed [23:0] tmp_data_V_3_fu_351_p4;
wire  signed [15:0] p_Result_1_3_i_i_fu_553_p4;
wire  signed [23:0] tmp_data_V_4_fu_361_p4;
wire  signed [15:0] p_Result_1_4_i_i_fu_581_p4;
wire  signed [23:0] tmp_data_V_5_fu_371_p4;
wire  signed [15:0] p_Result_1_5_i_i_fu_609_p4;
wire  signed [23:0] tmp_data_V_6_fu_381_p4;
wire  signed [15:0] p_Result_1_6_i_i_fu_637_p4;
wire  signed [23:0] tmp_data_V_7_fu_391_p4;
wire  signed [15:0] p_Result_1_7_i_i_fu_665_p4;
wire  signed [23:0] tmp_data_V_8_fu_401_p4;
wire  signed [15:0] p_Result_1_8_i_i_fu_693_p4;
wire  signed [23:0] tmp_data_V_9_fu_411_p4;
wire  signed [15:0] p_Result_1_9_i_i_fu_721_p4;
wire  signed [23:0] tmp_data_V_10_fu_421_p4;
wire  signed [15:0] p_Result_1_i_i_fu_749_p4;
wire  signed [23:0] tmp_data_V_11_fu_431_p4;
wire  signed [15:0] p_Result_1_10_i_i_fu_777_p4;
wire  signed [23:0] tmp_data_V_12_fu_441_p4;
wire  signed [15:0] p_Result_1_11_i_i_fu_805_p4;
wire  signed [23:0] tmp_data_V_13_fu_451_p4;
wire  signed [15:0] p_Result_1_12_i_i_fu_833_p4;
wire  signed [23:0] tmp_data_V_14_fu_461_p4;
wire  signed [15:0] p_Result_1_13_i_i_fu_861_p4;
wire  signed [23:0] tmp_data_V_15_fu_471_p4;
wire  signed [15:0] p_Result_1_14_i_i_fu_889_p4;
wire   [7:0] trunc_ln69_28_fu_1061_p4;
wire   [7:0] trunc_ln69_27_fu_1051_p4;
wire   [7:0] trunc_ln69_26_fu_1041_p4;
wire   [7:0] trunc_ln69_25_fu_1031_p4;
wire   [7:0] trunc_ln69_24_fu_1021_p4;
wire   [7:0] trunc_ln69_23_fu_1011_p4;
wire   [7:0] trunc_ln69_22_fu_1001_p4;
wire   [7:0] trunc_ln69_21_fu_991_p4;
wire   [7:0] trunc_ln69_20_fu_981_p4;
wire   [7:0] trunc_ln69_19_fu_971_p4;
wire   [7:0] trunc_ln69_18_fu_961_p4;
wire   [7:0] trunc_ln69_17_fu_951_p4;
wire   [7:0] trunc_ln69_16_fu_941_p4;
wire   [7:0] trunc_ln69_15_fu_931_p4;
wire   [7:0] trunc_ln69_s_fu_921_p4;
wire   [7:0] trunc_ln69_fu_917_p1;
wire  signed [39:0] grp_fu_3001_p3;
wire  signed [39:0] grp_fu_3011_p3;
wire  signed [39:0] grp_fu_3021_p3;
wire  signed [39:0] grp_fu_3031_p3;
wire  signed [39:0] grp_fu_3041_p3;
wire  signed [39:0] grp_fu_3051_p3;
wire  signed [39:0] grp_fu_3061_p3;
wire  signed [39:0] grp_fu_3071_p3;
wire  signed [39:0] grp_fu_3081_p3;
wire  signed [39:0] grp_fu_3091_p3;
wire  signed [39:0] grp_fu_3101_p3;
wire  signed [39:0] grp_fu_3111_p3;
wire  signed [39:0] grp_fu_3121_p3;
wire  signed [39:0] grp_fu_3131_p3;
wire  signed [39:0] grp_fu_3141_p3;
wire  signed [39:0] grp_fu_3151_p3;
wire  signed [23:0] sext_ln691_fu_1396_p1;
wire  signed [22:0] sext_ln691_32_fu_1399_p1;
wire   [23:0] add_ln691_32_fu_1402_p2;
wire   [0:0] tmp_47_fu_1412_p3;
wire   [22:0] add_ln297_fu_1407_p2;
wire   [22:0] select_ln298_fu_1420_p3;
wire   [23:0] zext_ln299_fu_1428_p1;
wire  signed [23:0] sext_ln691_16_fu_1439_p1;
wire  signed [22:0] sext_ln691_33_fu_1442_p1;
wire   [23:0] add_ln691_34_fu_1445_p2;
wire   [0:0] tmp_49_fu_1455_p3;
wire   [22:0] add_ln297_16_fu_1450_p2;
wire   [22:0] select_ln298_16_fu_1463_p3;
wire   [23:0] zext_ln299_16_fu_1471_p1;
wire  signed [23:0] sext_ln691_17_fu_1482_p1;
wire  signed [22:0] sext_ln691_34_fu_1485_p1;
wire   [23:0] add_ln691_36_fu_1488_p2;
wire   [0:0] tmp_51_fu_1498_p3;
wire   [22:0] add_ln297_17_fu_1493_p2;
wire   [22:0] select_ln298_17_fu_1506_p3;
wire   [23:0] zext_ln299_17_fu_1514_p1;
wire  signed [23:0] sext_ln691_18_fu_1525_p1;
wire  signed [22:0] sext_ln691_35_fu_1528_p1;
wire   [23:0] add_ln691_38_fu_1531_p2;
wire   [0:0] tmp_53_fu_1541_p3;
wire   [22:0] add_ln297_18_fu_1536_p2;
wire   [22:0] select_ln298_18_fu_1549_p3;
wire   [23:0] zext_ln299_18_fu_1557_p1;
wire  signed [23:0] sext_ln691_19_fu_1568_p1;
wire  signed [22:0] sext_ln691_36_fu_1571_p1;
wire   [23:0] add_ln691_40_fu_1574_p2;
wire   [0:0] tmp_55_fu_1584_p3;
wire   [22:0] add_ln297_19_fu_1579_p2;
wire   [22:0] select_ln298_19_fu_1592_p3;
wire   [23:0] zext_ln299_19_fu_1600_p1;
wire  signed [23:0] sext_ln691_20_fu_1611_p1;
wire  signed [22:0] sext_ln691_37_fu_1614_p1;
wire   [23:0] add_ln691_42_fu_1617_p2;
wire   [0:0] tmp_57_fu_1627_p3;
wire   [22:0] add_ln297_20_fu_1622_p2;
wire   [22:0] select_ln298_20_fu_1635_p3;
wire   [23:0] zext_ln299_20_fu_1643_p1;
wire  signed [23:0] sext_ln691_21_fu_1654_p1;
wire  signed [22:0] sext_ln691_38_fu_1657_p1;
wire   [23:0] add_ln691_44_fu_1660_p2;
wire   [0:0] tmp_59_fu_1670_p3;
wire   [22:0] add_ln297_21_fu_1665_p2;
wire   [22:0] select_ln298_21_fu_1678_p3;
wire   [23:0] zext_ln299_21_fu_1686_p1;
wire  signed [23:0] sext_ln691_22_fu_1697_p1;
wire  signed [22:0] sext_ln691_39_fu_1700_p1;
wire   [23:0] add_ln691_46_fu_1703_p2;
wire   [0:0] tmp_61_fu_1713_p3;
wire   [22:0] add_ln297_22_fu_1708_p2;
wire   [22:0] select_ln298_22_fu_1721_p3;
wire   [23:0] zext_ln299_22_fu_1729_p1;
wire  signed [23:0] sext_ln691_23_fu_1740_p1;
wire  signed [22:0] sext_ln691_40_fu_1743_p1;
wire   [23:0] add_ln691_48_fu_1746_p2;
wire   [0:0] tmp_63_fu_1756_p3;
wire   [22:0] add_ln297_23_fu_1751_p2;
wire   [22:0] select_ln298_23_fu_1764_p3;
wire   [23:0] zext_ln299_23_fu_1772_p1;
wire  signed [23:0] sext_ln691_24_fu_1783_p1;
wire  signed [22:0] sext_ln691_41_fu_1786_p1;
wire   [23:0] add_ln691_50_fu_1789_p2;
wire   [0:0] tmp_65_fu_1799_p3;
wire   [22:0] add_ln297_24_fu_1794_p2;
wire   [22:0] select_ln298_24_fu_1807_p3;
wire   [23:0] zext_ln299_24_fu_1815_p1;
wire  signed [23:0] sext_ln691_25_fu_1826_p1;
wire  signed [22:0] sext_ln691_42_fu_1829_p1;
wire   [23:0] add_ln691_52_fu_1832_p2;
wire   [0:0] tmp_67_fu_1842_p3;
wire   [22:0] add_ln297_25_fu_1837_p2;
wire   [22:0] select_ln298_25_fu_1850_p3;
wire   [23:0] zext_ln299_25_fu_1858_p1;
wire  signed [23:0] sext_ln691_26_fu_1869_p1;
wire  signed [22:0] sext_ln691_43_fu_1872_p1;
wire   [23:0] add_ln691_54_fu_1875_p2;
wire   [0:0] tmp_69_fu_1885_p3;
wire   [22:0] add_ln297_26_fu_1880_p2;
wire   [22:0] select_ln298_26_fu_1893_p3;
wire   [23:0] zext_ln299_26_fu_1901_p1;
wire  signed [23:0] sext_ln691_27_fu_1912_p1;
wire  signed [22:0] sext_ln691_44_fu_1915_p1;
wire   [23:0] add_ln691_56_fu_1918_p2;
wire   [0:0] tmp_71_fu_1928_p3;
wire   [22:0] add_ln297_27_fu_1923_p2;
wire   [22:0] select_ln298_27_fu_1936_p3;
wire   [23:0] zext_ln299_27_fu_1944_p1;
wire  signed [23:0] sext_ln691_28_fu_1955_p1;
wire  signed [22:0] sext_ln691_45_fu_1958_p1;
wire   [23:0] add_ln691_58_fu_1961_p2;
wire   [0:0] tmp_73_fu_1971_p3;
wire   [22:0] add_ln297_28_fu_1966_p2;
wire   [22:0] select_ln298_28_fu_1979_p3;
wire   [23:0] zext_ln299_28_fu_1987_p1;
wire  signed [23:0] sext_ln691_29_fu_1998_p1;
wire  signed [22:0] sext_ln691_46_fu_2001_p1;
wire   [23:0] add_ln691_60_fu_2004_p2;
wire   [0:0] tmp_75_fu_2014_p3;
wire   [22:0] add_ln297_29_fu_2009_p2;
wire   [22:0] select_ln298_29_fu_2022_p3;
wire   [23:0] zext_ln299_29_fu_2030_p1;
wire  signed [23:0] sext_ln691_30_fu_2041_p1;
wire  signed [22:0] sext_ln691_47_fu_2044_p1;
wire   [23:0] add_ln691_62_fu_2047_p2;
wire   [0:0] tmp_77_fu_2057_p3;
wire   [22:0] add_ln297_30_fu_2052_p2;
wire   [22:0] select_ln298_30_fu_2065_p3;
wire   [23:0] zext_ln299_30_fu_2073_p1;
wire   [23:0] add_ln692_fu_2084_p2;
wire   [16:0] tmp_48_fu_2089_p4;
wire   [23:0] add_ln692_16_fu_2111_p2;
wire   [16:0] tmp_50_fu_2116_p4;
wire   [23:0] add_ln692_17_fu_2138_p2;
wire   [16:0] tmp_52_fu_2143_p4;
wire   [23:0] add_ln692_18_fu_2165_p2;
wire   [16:0] tmp_54_fu_2170_p4;
wire   [23:0] add_ln692_19_fu_2192_p2;
wire   [16:0] tmp_56_fu_2197_p4;
wire   [23:0] add_ln692_20_fu_2219_p2;
wire   [16:0] tmp_58_fu_2224_p4;
wire   [23:0] add_ln692_21_fu_2246_p2;
wire   [16:0] tmp_60_fu_2251_p4;
wire   [23:0] add_ln692_22_fu_2273_p2;
wire   [16:0] tmp_62_fu_2278_p4;
wire   [23:0] add_ln692_23_fu_2300_p2;
wire   [16:0] tmp_64_fu_2305_p4;
wire   [23:0] add_ln692_24_fu_2327_p2;
wire   [16:0] tmp_66_fu_2332_p4;
wire   [23:0] add_ln692_25_fu_2354_p2;
wire   [16:0] tmp_68_fu_2359_p4;
wire   [23:0] add_ln692_26_fu_2381_p2;
wire   [16:0] tmp_70_fu_2386_p4;
wire   [23:0] add_ln692_27_fu_2408_p2;
wire   [16:0] tmp_72_fu_2413_p4;
wire   [23:0] add_ln692_28_fu_2435_p2;
wire   [16:0] tmp_74_fu_2440_p4;
wire   [23:0] add_ln692_29_fu_2462_p2;
wire   [16:0] tmp_76_fu_2467_p4;
wire   [23:0] add_ln692_30_fu_2489_p2;
wire   [16:0] tmp_78_fu_2494_p4;
wire   [7:0] trunc_ln692_fu_2516_p1;
wire   [0:0] or_ln69_fu_2532_p2;
wire   [7:0] select_ln69_fu_2525_p3;
wire   [7:0] xor_ln69_fu_2519_p2;
wire   [7:0] trunc_ln692_16_fu_2544_p1;
wire   [0:0] or_ln69_16_fu_2560_p2;
wire   [7:0] select_ln69_33_fu_2553_p3;
wire   [7:0] xor_ln69_16_fu_2547_p2;
wire   [7:0] trunc_ln692_17_fu_2572_p1;
wire   [0:0] or_ln69_17_fu_2588_p2;
wire   [7:0] select_ln69_35_fu_2581_p3;
wire   [7:0] xor_ln69_17_fu_2575_p2;
wire   [7:0] trunc_ln692_18_fu_2600_p1;
wire   [0:0] or_ln69_18_fu_2616_p2;
wire   [7:0] select_ln69_37_fu_2609_p3;
wire   [7:0] xor_ln69_18_fu_2603_p2;
wire   [7:0] trunc_ln692_19_fu_2628_p1;
wire   [0:0] or_ln69_19_fu_2644_p2;
wire   [7:0] select_ln69_39_fu_2637_p3;
wire   [7:0] xor_ln69_19_fu_2631_p2;
wire   [7:0] trunc_ln692_20_fu_2656_p1;
wire   [0:0] or_ln69_20_fu_2672_p2;
wire   [7:0] select_ln69_41_fu_2665_p3;
wire   [7:0] xor_ln69_20_fu_2659_p2;
wire   [7:0] trunc_ln692_21_fu_2684_p1;
wire   [0:0] or_ln69_21_fu_2700_p2;
wire   [7:0] select_ln69_43_fu_2693_p3;
wire   [7:0] xor_ln69_21_fu_2687_p2;
wire   [7:0] trunc_ln692_22_fu_2712_p1;
wire   [0:0] or_ln69_22_fu_2728_p2;
wire   [7:0] select_ln69_45_fu_2721_p3;
wire   [7:0] xor_ln69_22_fu_2715_p2;
wire   [7:0] trunc_ln692_23_fu_2740_p1;
wire   [0:0] or_ln69_23_fu_2756_p2;
wire   [7:0] select_ln69_47_fu_2749_p3;
wire   [7:0] xor_ln69_23_fu_2743_p2;
wire   [7:0] trunc_ln692_24_fu_2768_p1;
wire   [0:0] or_ln69_24_fu_2784_p2;
wire   [7:0] select_ln69_49_fu_2777_p3;
wire   [7:0] xor_ln69_24_fu_2771_p2;
wire   [7:0] trunc_ln692_25_fu_2796_p1;
wire   [0:0] or_ln69_25_fu_2812_p2;
wire   [7:0] select_ln69_51_fu_2805_p3;
wire   [7:0] xor_ln69_25_fu_2799_p2;
wire   [7:0] trunc_ln692_26_fu_2824_p1;
wire   [0:0] or_ln69_26_fu_2840_p2;
wire   [7:0] select_ln69_53_fu_2833_p3;
wire   [7:0] xor_ln69_26_fu_2827_p2;
wire   [7:0] trunc_ln692_27_fu_2852_p1;
wire   [0:0] or_ln69_27_fu_2868_p2;
wire   [7:0] select_ln69_55_fu_2861_p3;
wire   [7:0] xor_ln69_27_fu_2855_p2;
wire   [7:0] trunc_ln692_28_fu_2880_p1;
wire   [0:0] or_ln69_28_fu_2896_p2;
wire   [7:0] select_ln69_57_fu_2889_p3;
wire   [7:0] xor_ln69_28_fu_2883_p2;
wire   [7:0] trunc_ln692_29_fu_2908_p1;
wire   [0:0] or_ln69_29_fu_2924_p2;
wire   [7:0] select_ln69_59_fu_2917_p3;
wire   [7:0] xor_ln69_29_fu_2911_p2;
wire   [7:0] trunc_ln692_30_fu_2936_p1;
wire   [0:0] or_ln69_30_fu_2952_p2;
wire   [7:0] select_ln69_61_fu_2945_p3;
wire   [7:0] xor_ln69_30_fu_2939_p2;
wire   [7:0] select_ln69_62_fu_2956_p3;
wire   [7:0] select_ln69_60_fu_2928_p3;
wire   [7:0] select_ln69_58_fu_2900_p3;
wire   [7:0] select_ln69_56_fu_2872_p3;
wire   [7:0] select_ln69_54_fu_2844_p3;
wire   [7:0] select_ln69_52_fu_2816_p3;
wire   [7:0] select_ln69_50_fu_2788_p3;
wire   [7:0] select_ln69_48_fu_2760_p3;
wire   [7:0] select_ln69_46_fu_2732_p3;
wire   [7:0] select_ln69_44_fu_2704_p3;
wire   [7:0] select_ln69_42_fu_2676_p3;
wire   [7:0] select_ln69_40_fu_2648_p3;
wire   [7:0] select_ln69_38_fu_2620_p3;
wire   [7:0] select_ln69_36_fu_2592_p3;
wire   [7:0] select_ln69_34_fu_2564_p3;
wire   [7:0] select_ln69_32_fu_2536_p3;
wire   [16:0] grp_fu_3001_p2;
wire   [16:0] grp_fu_3011_p2;
wire   [16:0] grp_fu_3021_p2;
wire   [16:0] grp_fu_3031_p2;
wire   [16:0] grp_fu_3041_p2;
wire   [16:0] grp_fu_3051_p2;
wire   [16:0] grp_fu_3061_p2;
wire   [16:0] grp_fu_3071_p2;
wire   [16:0] grp_fu_3081_p2;
wire   [16:0] grp_fu_3091_p2;
wire   [16:0] grp_fu_3101_p2;
wire   [16:0] grp_fu_3111_p2;
wire   [16:0] grp_fu_3121_p2;
wire   [16:0] grp_fu_3131_p2;
wire   [16:0] grp_fu_3141_p2;
wire   [16:0] grp_fu_3151_p2;
reg    grp_fu_3001_ce;
reg    grp_fu_3011_ce;
reg    grp_fu_3021_ce;
reg    grp_fu_3031_ce;
reg    grp_fu_3041_ce;
reg    grp_fu_3051_ce;
reg    grp_fu_3061_ce;
reg    grp_fu_3071_ce;
reg    grp_fu_3081_ce;
reg    grp_fu_3091_ce;
reg    grp_fu_3101_ce;
reg    grp_fu_3111_ce;
reg    grp_fu_3121_ce;
reg    grp_fu_3131_ce;
reg    grp_fu_3141_ce;
reg    grp_fu_3151_ce;
wire    ap_CS_fsm_state15;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [43:0] grp_fu_310_p00;
wire   [43:0] grp_fu_310_p10;
reg    ap_condition_2456;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
end

top_mul_32ns_12ns_44_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 44 ))
mul_32ns_12ns_44_5_1_U871(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_310_p0),
    .din1(grp_fu_310_p1),
    .ce(1'b1),
    .dout(grp_fu_310_p2)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U872(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_0_fu_327_p1),
    .din1(trunc_ln674_fu_481_p1),
    .din2(grp_fu_3001_p2),
    .ce(grp_fu_3001_ce),
    .dout(grp_fu_3001_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U873(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_1_fu_331_p4),
    .din1(p_Result_1_1_i_i_fu_497_p4),
    .din2(grp_fu_3011_p2),
    .ce(grp_fu_3011_ce),
    .dout(grp_fu_3011_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U874(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_2_fu_341_p4),
    .din1(p_Result_1_2_i_i_fu_525_p4),
    .din2(grp_fu_3021_p2),
    .ce(grp_fu_3021_ce),
    .dout(grp_fu_3021_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U875(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_3_fu_351_p4),
    .din1(p_Result_1_3_i_i_fu_553_p4),
    .din2(grp_fu_3031_p2),
    .ce(grp_fu_3031_ce),
    .dout(grp_fu_3031_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U876(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_4_fu_361_p4),
    .din1(p_Result_1_4_i_i_fu_581_p4),
    .din2(grp_fu_3041_p2),
    .ce(grp_fu_3041_ce),
    .dout(grp_fu_3041_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U877(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_5_fu_371_p4),
    .din1(p_Result_1_5_i_i_fu_609_p4),
    .din2(grp_fu_3051_p2),
    .ce(grp_fu_3051_ce),
    .dout(grp_fu_3051_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U878(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_6_fu_381_p4),
    .din1(p_Result_1_6_i_i_fu_637_p4),
    .din2(grp_fu_3061_p2),
    .ce(grp_fu_3061_ce),
    .dout(grp_fu_3061_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U879(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_7_fu_391_p4),
    .din1(p_Result_1_7_i_i_fu_665_p4),
    .din2(grp_fu_3071_p2),
    .ce(grp_fu_3071_ce),
    .dout(grp_fu_3071_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U880(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_8_fu_401_p4),
    .din1(p_Result_1_8_i_i_fu_693_p4),
    .din2(grp_fu_3081_p2),
    .ce(grp_fu_3081_ce),
    .dout(grp_fu_3081_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U881(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_9_fu_411_p4),
    .din1(p_Result_1_9_i_i_fu_721_p4),
    .din2(grp_fu_3091_p2),
    .ce(grp_fu_3091_ce),
    .dout(grp_fu_3091_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U882(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_10_fu_421_p4),
    .din1(p_Result_1_i_i_fu_749_p4),
    .din2(grp_fu_3101_p2),
    .ce(grp_fu_3101_ce),
    .dout(grp_fu_3101_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U883(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_11_fu_431_p4),
    .din1(p_Result_1_10_i_i_fu_777_p4),
    .din2(grp_fu_3111_p2),
    .ce(grp_fu_3111_ce),
    .dout(grp_fu_3111_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U884(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_12_fu_441_p4),
    .din1(p_Result_1_11_i_i_fu_805_p4),
    .din2(grp_fu_3121_p2),
    .ce(grp_fu_3121_ce),
    .dout(grp_fu_3121_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U885(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_13_fu_451_p4),
    .din1(p_Result_1_12_i_i_fu_833_p4),
    .din2(grp_fu_3131_p2),
    .ce(grp_fu_3131_ce),
    .dout(grp_fu_3131_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U886(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_14_fu_461_p4),
    .din1(p_Result_1_13_i_i_fu_861_p4),
    .din2(grp_fu_3141_p2),
    .ce(grp_fu_3141_ce),
    .dout(grp_fu_3141_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U887(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_15_fu_471_p4),
    .din1(p_Result_1_14_i_i_fu_889_p4),
    .din2(grp_fu_3151_p2),
    .ce(grp_fu_3151_ce),
    .dout(grp_fu_3151_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state15)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state7))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state7)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state7);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp0_iter7 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln272_fu_322_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        indvar_flatten_reg_283 <= add_ln272_fu_316_p2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        indvar_flatten_reg_283 <= 44'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        bound_reg_3205 <= grp_fu_310_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((skip_reg_3161 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln878_16_reg_3748 <= icmp_ln878_16_fu_2132_p2;
        icmp_ln878_17_reg_3759 <= icmp_ln878_17_fu_2159_p2;
        icmp_ln878_18_reg_3770 <= icmp_ln878_18_fu_2186_p2;
        icmp_ln878_19_reg_3781 <= icmp_ln878_19_fu_2213_p2;
        icmp_ln878_20_reg_3792 <= icmp_ln878_20_fu_2240_p2;
        icmp_ln878_21_reg_3803 <= icmp_ln878_21_fu_2267_p2;
        icmp_ln878_22_reg_3814 <= icmp_ln878_22_fu_2294_p2;
        icmp_ln878_23_reg_3825 <= icmp_ln878_23_fu_2321_p2;
        icmp_ln878_24_reg_3836 <= icmp_ln878_24_fu_2348_p2;
        icmp_ln878_25_reg_3847 <= icmp_ln878_25_fu_2375_p2;
        icmp_ln878_26_reg_3858 <= icmp_ln878_26_fu_2402_p2;
        icmp_ln878_27_reg_3869 <= icmp_ln878_27_fu_2429_p2;
        icmp_ln878_28_reg_3880 <= icmp_ln878_28_fu_2456_p2;
        icmp_ln878_29_reg_3891 <= icmp_ln878_29_fu_2483_p2;
        icmp_ln878_30_reg_3902 <= icmp_ln878_30_fu_2510_p2;
        icmp_ln878_reg_3737 <= icmp_ln878_fu_2105_p2;
        icmp_ln886_16_reg_3742 <= icmp_ln886_16_fu_2126_p2;
        icmp_ln886_17_reg_3753 <= icmp_ln886_17_fu_2153_p2;
        icmp_ln886_18_reg_3764 <= icmp_ln886_18_fu_2180_p2;
        icmp_ln886_19_reg_3775 <= icmp_ln886_19_fu_2207_p2;
        icmp_ln886_20_reg_3786 <= icmp_ln886_20_fu_2234_p2;
        icmp_ln886_21_reg_3797 <= icmp_ln886_21_fu_2261_p2;
        icmp_ln886_22_reg_3808 <= icmp_ln886_22_fu_2288_p2;
        icmp_ln886_23_reg_3819 <= icmp_ln886_23_fu_2315_p2;
        icmp_ln886_24_reg_3830 <= icmp_ln886_24_fu_2342_p2;
        icmp_ln886_25_reg_3841 <= icmp_ln886_25_fu_2369_p2;
        icmp_ln886_26_reg_3852 <= icmp_ln886_26_fu_2396_p2;
        icmp_ln886_27_reg_3863 <= icmp_ln886_27_fu_2423_p2;
        icmp_ln886_28_reg_3874 <= icmp_ln886_28_fu_2450_p2;
        icmp_ln886_29_reg_3885 <= icmp_ln886_29_fu_2477_p2;
        icmp_ln886_30_reg_3896 <= icmp_ln886_30_fu_2504_p2;
        icmp_ln886_reg_3731 <= icmp_ln886_fu_2099_p2;
        p_Result_3_10_i_i_reg_3585 <= {{grp_fu_3111_p3[39:16]}};
        p_Result_3_11_i_i_reg_3595 <= {{grp_fu_3121_p3[39:16]}};
        p_Result_3_12_i_i_reg_3605 <= {{grp_fu_3131_p3[39:16]}};
        p_Result_3_13_i_i_reg_3615 <= {{grp_fu_3141_p3[39:16]}};
        p_Result_3_14_i_i_reg_3625 <= {{grp_fu_3151_p3[39:16]}};
        p_Result_3_1_i_i_reg_3485 <= {{grp_fu_3011_p3[39:16]}};
        p_Result_3_2_i_i_reg_3495 <= {{grp_fu_3021_p3[39:16]}};
        p_Result_3_3_i_i_reg_3505 <= {{grp_fu_3031_p3[39:16]}};
        p_Result_3_4_i_i_reg_3515 <= {{grp_fu_3041_p3[39:16]}};
        p_Result_3_5_i_i_reg_3525 <= {{grp_fu_3051_p3[39:16]}};
        p_Result_3_6_i_i_reg_3535 <= {{grp_fu_3061_p3[39:16]}};
        p_Result_3_7_i_i_reg_3545 <= {{grp_fu_3071_p3[39:16]}};
        p_Result_3_8_i_i_reg_3555 <= {{grp_fu_3081_p3[39:16]}};
        p_Result_3_9_i_i_reg_3565 <= {{grp_fu_3091_p3[39:16]}};
        p_Result_3_i_i_183_reg_3575 <= {{grp_fu_3101_p3[39:16]}};
        p_Result_3_i_i_reg_3475 <= {{grp_fu_3001_p3[39:16]}};
        select_ln263_16_reg_3641 <= select_ln263_16_fu_1475_p3;
        select_ln263_17_reg_3647 <= select_ln263_17_fu_1518_p3;
        select_ln263_18_reg_3653 <= select_ln263_18_fu_1561_p3;
        select_ln263_19_reg_3659 <= select_ln263_19_fu_1604_p3;
        select_ln263_20_reg_3665 <= select_ln263_20_fu_1647_p3;
        select_ln263_21_reg_3671 <= select_ln263_21_fu_1690_p3;
        select_ln263_22_reg_3677 <= select_ln263_22_fu_1733_p3;
        select_ln263_23_reg_3683 <= select_ln263_23_fu_1776_p3;
        select_ln263_24_reg_3689 <= select_ln263_24_fu_1819_p3;
        select_ln263_25_reg_3695 <= select_ln263_25_fu_1862_p3;
        select_ln263_26_reg_3701 <= select_ln263_26_fu_1905_p3;
        select_ln263_27_reg_3707 <= select_ln263_27_fu_1948_p3;
        select_ln263_28_reg_3713 <= select_ln263_28_fu_1991_p3;
        select_ln263_29_reg_3719 <= select_ln263_29_fu_2034_p3;
        select_ln263_30_reg_3725 <= select_ln263_30_fu_2077_p3;
        select_ln263_reg_3635 <= select_ln263_fu_1432_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((skip_reg_3161 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_Result_2_10_i_i_reg_3395 <= {{s_bias_1_dout[191:176]}};
        p_Result_2_11_i_i_reg_3411 <= {{s_bias_1_dout[207:192]}};
        p_Result_2_12_i_i_reg_3427 <= {{s_bias_1_dout[223:208]}};
        p_Result_2_13_i_i_reg_3443 <= {{s_bias_1_dout[239:224]}};
        p_Result_2_14_i_i_reg_3459 <= {{s_bias_1_dout[255:240]}};
        p_Result_2_1_i_i_reg_3235 <= {{s_bias_1_dout[31:16]}};
        p_Result_2_2_i_i_reg_3251 <= {{s_bias_1_dout[47:32]}};
        p_Result_2_3_i_i_reg_3267 <= {{s_bias_1_dout[63:48]}};
        p_Result_2_4_i_i_reg_3283 <= {{s_bias_1_dout[79:64]}};
        p_Result_2_5_i_i_reg_3299 <= {{s_bias_1_dout[95:80]}};
        p_Result_2_6_i_i_reg_3315 <= {{s_bias_1_dout[111:96]}};
        p_Result_2_7_i_i_reg_3331 <= {{s_bias_1_dout[127:112]}};
        p_Result_2_8_i_i_reg_3347 <= {{s_bias_1_dout[143:128]}};
        p_Result_2_9_i_i_reg_3363 <= {{s_bias_1_dout[159:144]}};
        p_Result_2_i_i_reg_3379 <= {{s_bias_1_dout[175:160]}};
        trunc_ln674_2_reg_3219 <= trunc_ln674_2_fu_485_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        p_Result_2_10_i_i_reg_3395_pp0_iter2_reg <= p_Result_2_10_i_i_reg_3395;
        p_Result_2_10_i_i_reg_3395_pp0_iter3_reg <= p_Result_2_10_i_i_reg_3395_pp0_iter2_reg;
        p_Result_2_10_i_i_reg_3395_pp0_iter4_reg <= p_Result_2_10_i_i_reg_3395_pp0_iter3_reg;
        p_Result_2_11_i_i_reg_3411_pp0_iter2_reg <= p_Result_2_11_i_i_reg_3411;
        p_Result_2_11_i_i_reg_3411_pp0_iter3_reg <= p_Result_2_11_i_i_reg_3411_pp0_iter2_reg;
        p_Result_2_11_i_i_reg_3411_pp0_iter4_reg <= p_Result_2_11_i_i_reg_3411_pp0_iter3_reg;
        p_Result_2_12_i_i_reg_3427_pp0_iter2_reg <= p_Result_2_12_i_i_reg_3427;
        p_Result_2_12_i_i_reg_3427_pp0_iter3_reg <= p_Result_2_12_i_i_reg_3427_pp0_iter2_reg;
        p_Result_2_12_i_i_reg_3427_pp0_iter4_reg <= p_Result_2_12_i_i_reg_3427_pp0_iter3_reg;
        p_Result_2_13_i_i_reg_3443_pp0_iter2_reg <= p_Result_2_13_i_i_reg_3443;
        p_Result_2_13_i_i_reg_3443_pp0_iter3_reg <= p_Result_2_13_i_i_reg_3443_pp0_iter2_reg;
        p_Result_2_13_i_i_reg_3443_pp0_iter4_reg <= p_Result_2_13_i_i_reg_3443_pp0_iter3_reg;
        p_Result_2_14_i_i_reg_3459_pp0_iter2_reg <= p_Result_2_14_i_i_reg_3459;
        p_Result_2_14_i_i_reg_3459_pp0_iter3_reg <= p_Result_2_14_i_i_reg_3459_pp0_iter2_reg;
        p_Result_2_14_i_i_reg_3459_pp0_iter4_reg <= p_Result_2_14_i_i_reg_3459_pp0_iter3_reg;
        p_Result_2_1_i_i_reg_3235_pp0_iter2_reg <= p_Result_2_1_i_i_reg_3235;
        p_Result_2_1_i_i_reg_3235_pp0_iter3_reg <= p_Result_2_1_i_i_reg_3235_pp0_iter2_reg;
        p_Result_2_1_i_i_reg_3235_pp0_iter4_reg <= p_Result_2_1_i_i_reg_3235_pp0_iter3_reg;
        p_Result_2_2_i_i_reg_3251_pp0_iter2_reg <= p_Result_2_2_i_i_reg_3251;
        p_Result_2_2_i_i_reg_3251_pp0_iter3_reg <= p_Result_2_2_i_i_reg_3251_pp0_iter2_reg;
        p_Result_2_2_i_i_reg_3251_pp0_iter4_reg <= p_Result_2_2_i_i_reg_3251_pp0_iter3_reg;
        p_Result_2_3_i_i_reg_3267_pp0_iter2_reg <= p_Result_2_3_i_i_reg_3267;
        p_Result_2_3_i_i_reg_3267_pp0_iter3_reg <= p_Result_2_3_i_i_reg_3267_pp0_iter2_reg;
        p_Result_2_3_i_i_reg_3267_pp0_iter4_reg <= p_Result_2_3_i_i_reg_3267_pp0_iter3_reg;
        p_Result_2_4_i_i_reg_3283_pp0_iter2_reg <= p_Result_2_4_i_i_reg_3283;
        p_Result_2_4_i_i_reg_3283_pp0_iter3_reg <= p_Result_2_4_i_i_reg_3283_pp0_iter2_reg;
        p_Result_2_4_i_i_reg_3283_pp0_iter4_reg <= p_Result_2_4_i_i_reg_3283_pp0_iter3_reg;
        p_Result_2_5_i_i_reg_3299_pp0_iter2_reg <= p_Result_2_5_i_i_reg_3299;
        p_Result_2_5_i_i_reg_3299_pp0_iter3_reg <= p_Result_2_5_i_i_reg_3299_pp0_iter2_reg;
        p_Result_2_5_i_i_reg_3299_pp0_iter4_reg <= p_Result_2_5_i_i_reg_3299_pp0_iter3_reg;
        p_Result_2_6_i_i_reg_3315_pp0_iter2_reg <= p_Result_2_6_i_i_reg_3315;
        p_Result_2_6_i_i_reg_3315_pp0_iter3_reg <= p_Result_2_6_i_i_reg_3315_pp0_iter2_reg;
        p_Result_2_6_i_i_reg_3315_pp0_iter4_reg <= p_Result_2_6_i_i_reg_3315_pp0_iter3_reg;
        p_Result_2_7_i_i_reg_3331_pp0_iter2_reg <= p_Result_2_7_i_i_reg_3331;
        p_Result_2_7_i_i_reg_3331_pp0_iter3_reg <= p_Result_2_7_i_i_reg_3331_pp0_iter2_reg;
        p_Result_2_7_i_i_reg_3331_pp0_iter4_reg <= p_Result_2_7_i_i_reg_3331_pp0_iter3_reg;
        p_Result_2_8_i_i_reg_3347_pp0_iter2_reg <= p_Result_2_8_i_i_reg_3347;
        p_Result_2_8_i_i_reg_3347_pp0_iter3_reg <= p_Result_2_8_i_i_reg_3347_pp0_iter2_reg;
        p_Result_2_8_i_i_reg_3347_pp0_iter4_reg <= p_Result_2_8_i_i_reg_3347_pp0_iter3_reg;
        p_Result_2_9_i_i_reg_3363_pp0_iter2_reg <= p_Result_2_9_i_i_reg_3363;
        p_Result_2_9_i_i_reg_3363_pp0_iter3_reg <= p_Result_2_9_i_i_reg_3363_pp0_iter2_reg;
        p_Result_2_9_i_i_reg_3363_pp0_iter4_reg <= p_Result_2_9_i_i_reg_3363_pp0_iter3_reg;
        p_Result_2_i_i_reg_3379_pp0_iter2_reg <= p_Result_2_i_i_reg_3379;
        p_Result_2_i_i_reg_3379_pp0_iter3_reg <= p_Result_2_i_i_reg_3379_pp0_iter2_reg;
        p_Result_2_i_i_reg_3379_pp0_iter4_reg <= p_Result_2_i_i_reg_3379_pp0_iter3_reg;
        select_ln263_16_reg_3641_pp0_iter6_reg <= select_ln263_16_reg_3641;
        select_ln263_17_reg_3647_pp0_iter6_reg <= select_ln263_17_reg_3647;
        select_ln263_18_reg_3653_pp0_iter6_reg <= select_ln263_18_reg_3653;
        select_ln263_19_reg_3659_pp0_iter6_reg <= select_ln263_19_reg_3659;
        select_ln263_20_reg_3665_pp0_iter6_reg <= select_ln263_20_reg_3665;
        select_ln263_21_reg_3671_pp0_iter6_reg <= select_ln263_21_reg_3671;
        select_ln263_22_reg_3677_pp0_iter6_reg <= select_ln263_22_reg_3677;
        select_ln263_23_reg_3683_pp0_iter6_reg <= select_ln263_23_reg_3683;
        select_ln263_24_reg_3689_pp0_iter6_reg <= select_ln263_24_reg_3689;
        select_ln263_25_reg_3695_pp0_iter6_reg <= select_ln263_25_reg_3695;
        select_ln263_26_reg_3701_pp0_iter6_reg <= select_ln263_26_reg_3701;
        select_ln263_27_reg_3707_pp0_iter6_reg <= select_ln263_27_reg_3707;
        select_ln263_28_reg_3713_pp0_iter6_reg <= select_ln263_28_reg_3713;
        select_ln263_29_reg_3719_pp0_iter6_reg <= select_ln263_29_reg_3719;
        select_ln263_30_reg_3725_pp0_iter6_reg <= select_ln263_30_reg_3725;
        select_ln263_reg_3635_pp0_iter6_reg <= select_ln263_reg_3635;
        trunc_ln674_2_reg_3219_pp0_iter2_reg <= trunc_ln674_2_reg_3219;
        trunc_ln674_2_reg_3219_pp0_iter3_reg <= trunc_ln674_2_reg_3219_pp0_iter2_reg;
        trunc_ln674_2_reg_3219_pp0_iter4_reg <= trunc_ln674_2_reg_3219_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        relu_reg_3165 <= relu3_dout;
        rep_reg_3185 <= mul_ln93_1_loc_dout;
        ret_cast_reg_3190 <= {{OC_V_loc_dout[15:4]}};
        skip_reg_3161 <= skip3_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((skip_reg_3161 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (relu_reg_3165 == 1'd1))) begin
        tmp_15_reg_3500 <= {{grp_fu_3021_p3[38:16]}};
        tmp_16_reg_3510 <= {{grp_fu_3031_p3[38:16]}};
        tmp_17_reg_3520 <= {{grp_fu_3041_p3[38:16]}};
        tmp_18_reg_3530 <= {{grp_fu_3051_p3[38:16]}};
        tmp_19_reg_3540 <= {{grp_fu_3061_p3[38:16]}};
        tmp_20_reg_3550 <= {{grp_fu_3071_p3[38:16]}};
        tmp_21_reg_3560 <= {{grp_fu_3081_p3[38:16]}};
        tmp_22_reg_3570 <= {{grp_fu_3091_p3[38:16]}};
        tmp_23_reg_3580 <= {{grp_fu_3101_p3[38:16]}};
        tmp_24_reg_3590 <= {{grp_fu_3111_p3[38:16]}};
        tmp_25_reg_3600 <= {{grp_fu_3121_p3[38:16]}};
        tmp_26_reg_3610 <= {{grp_fu_3131_p3[38:16]}};
        tmp_27_reg_3620 <= {{grp_fu_3141_p3[38:16]}};
        tmp_28_reg_3630 <= {{grp_fu_3151_p3[38:16]}};
        tmp_reg_3480 <= {{grp_fu_3001_p3[38:16]}};
        tmp_s_reg_3490 <= {{grp_fu_3011_p3[38:16]}};
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        OC_V_loc_blk_n = OC_V_loc_empty_n;
    end else begin
        OC_V_loc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((relu3_empty_n == 1'b0) | (skip3_empty_n == 1'b0) | (mul_ln93_1_loc_empty_n == 1'b0) | (1'b0 == OC_V_loc_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        OC_V_loc_read = 1'b1;
    end else begin
        OC_V_loc_read = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln272_fu_322_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state7 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state7 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter7 == 1'b1) & (skip_reg_3161 == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((skip_reg_3161 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        f3_blk_n = f3_full_n;
    end else begin
        f3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_01001)) begin
        if (((ap_enable_reg_pp0_iter7 == 1'b1) & (skip_reg_3161 == 1'd0))) begin
            f3_din = p_Result_4_i_i_fu_2964_p17;
        end else if ((1'b1 == ap_condition_2456)) begin
            f3_din = p_Result_i_i_fu_1071_p17;
        end else begin
            f3_din = 'bx;
        end
    end else begin
        f3_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter7 == 1'b1) & (skip_reg_3161 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((skip_reg_3161 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        f3_write = 1'b1;
    end else begin
        f3_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3001_ce = 1'b1;
    end else begin
        grp_fu_3001_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3011_ce = 1'b1;
    end else begin
        grp_fu_3011_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3021_ce = 1'b1;
    end else begin
        grp_fu_3021_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3031_ce = 1'b1;
    end else begin
        grp_fu_3031_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3041_ce = 1'b1;
    end else begin
        grp_fu_3041_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3051_ce = 1'b1;
    end else begin
        grp_fu_3051_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3061_ce = 1'b1;
    end else begin
        grp_fu_3061_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3071_ce = 1'b1;
    end else begin
        grp_fu_3071_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3081_ce = 1'b1;
    end else begin
        grp_fu_3081_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3091_ce = 1'b1;
    end else begin
        grp_fu_3091_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3101_ce = 1'b1;
    end else begin
        grp_fu_3101_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3111_ce = 1'b1;
    end else begin
        grp_fu_3111_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3121_ce = 1'b1;
    end else begin
        grp_fu_3121_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3131_ce = 1'b1;
    end else begin
        grp_fu_3131_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3141_ce = 1'b1;
    end else begin
        grp_fu_3141_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3151_ce = 1'b1;
    end else begin
        grp_fu_3151_ce = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        mul_ln93_1_loc_blk_n = mul_ln93_1_loc_empty_n;
    end else begin
        mul_ln93_1_loc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((relu3_empty_n == 1'b0) | (skip3_empty_n == 1'b0) | (mul_ln93_1_loc_empty_n == 1'b0) | (1'b0 == OC_V_loc_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        mul_ln93_1_loc_read = 1'b1;
    end else begin
        mul_ln93_1_loc_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        relu3_blk_n = relu3_empty_n;
    end else begin
        relu3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((relu3_empty_n == 1'b0) | (skip3_empty_n == 1'b0) | (mul_ln93_1_loc_empty_n == 1'b0) | (1'b0 == OC_V_loc_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        relu3_read = 1'b1;
    end else begin
        relu3_read = 1'b0;
    end
end

always @ (*) begin
    if (((skip_reg_3161 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_bias_1_blk_n = s_bias_1_empty_n;
    end else begin
        s_bias_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((skip_reg_3161 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_bias_1_read = 1'b1;
    end else begin
        s_bias_1_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_conv3_blk_n = s_conv3_empty_n;
    end else begin
        s_conv3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_conv3_read = 1'b1;
    end else begin
        s_conv3_read = 1'b0;
    end
end

always @ (*) begin
    if (((skip_reg_3161 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_scale_1_blk_n = s_scale_1_empty_n;
    end else begin
        s_scale_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((skip_reg_3161 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_scale_1_read = 1'b1;
    end else begin
        s_scale_1_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        skip3_blk_n = skip3_empty_n;
    end else begin
        skip3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((relu3_empty_n == 1'b0) | (skip3_empty_n == 1'b0) | (mul_ln93_1_loc_empty_n == 1'b0) | (1'b0 == OC_V_loc_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        skip3_read = 1'b1;
    end else begin
        skip3_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((relu3_empty_n == 1'b0) | (skip3_empty_n == 1'b0) | (mul_ln93_1_loc_empty_n == 1'b0) | (1'b0 == OC_V_loc_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln272_fu_322_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln272_fu_322_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln272_fu_316_p2 = (indvar_flatten_reg_283 + 44'd1);

assign add_ln297_16_fu_1450_p2 = ($signed(tmp_s_reg_3490) + $signed(sext_ln691_33_fu_1442_p1));

assign add_ln297_17_fu_1493_p2 = ($signed(tmp_15_reg_3500) + $signed(sext_ln691_34_fu_1485_p1));

assign add_ln297_18_fu_1536_p2 = ($signed(tmp_16_reg_3510) + $signed(sext_ln691_35_fu_1528_p1));

assign add_ln297_19_fu_1579_p2 = ($signed(tmp_17_reg_3520) + $signed(sext_ln691_36_fu_1571_p1));

assign add_ln297_20_fu_1622_p2 = ($signed(tmp_18_reg_3530) + $signed(sext_ln691_37_fu_1614_p1));

assign add_ln297_21_fu_1665_p2 = ($signed(tmp_19_reg_3540) + $signed(sext_ln691_38_fu_1657_p1));

assign add_ln297_22_fu_1708_p2 = ($signed(tmp_20_reg_3550) + $signed(sext_ln691_39_fu_1700_p1));

assign add_ln297_23_fu_1751_p2 = ($signed(tmp_21_reg_3560) + $signed(sext_ln691_40_fu_1743_p1));

assign add_ln297_24_fu_1794_p2 = ($signed(tmp_22_reg_3570) + $signed(sext_ln691_41_fu_1786_p1));

assign add_ln297_25_fu_1837_p2 = ($signed(tmp_23_reg_3580) + $signed(sext_ln691_42_fu_1829_p1));

assign add_ln297_26_fu_1880_p2 = ($signed(tmp_24_reg_3590) + $signed(sext_ln691_43_fu_1872_p1));

assign add_ln297_27_fu_1923_p2 = ($signed(tmp_25_reg_3600) + $signed(sext_ln691_44_fu_1915_p1));

assign add_ln297_28_fu_1966_p2 = ($signed(tmp_26_reg_3610) + $signed(sext_ln691_45_fu_1958_p1));

assign add_ln297_29_fu_2009_p2 = ($signed(tmp_27_reg_3620) + $signed(sext_ln691_46_fu_2001_p1));

assign add_ln297_30_fu_2052_p2 = ($signed(tmp_28_reg_3630) + $signed(sext_ln691_47_fu_2044_p1));

assign add_ln297_fu_1407_p2 = ($signed(tmp_reg_3480) + $signed(sext_ln691_32_fu_1399_p1));

assign add_ln691_32_fu_1402_p2 = ($signed(p_Result_3_i_i_reg_3475) + $signed(sext_ln691_fu_1396_p1));

assign add_ln691_34_fu_1445_p2 = ($signed(p_Result_3_1_i_i_reg_3485) + $signed(sext_ln691_16_fu_1439_p1));

assign add_ln691_36_fu_1488_p2 = ($signed(p_Result_3_2_i_i_reg_3495) + $signed(sext_ln691_17_fu_1482_p1));

assign add_ln691_38_fu_1531_p2 = ($signed(p_Result_3_3_i_i_reg_3505) + $signed(sext_ln691_18_fu_1525_p1));

assign add_ln691_40_fu_1574_p2 = ($signed(p_Result_3_4_i_i_reg_3515) + $signed(sext_ln691_19_fu_1568_p1));

assign add_ln691_42_fu_1617_p2 = ($signed(p_Result_3_5_i_i_reg_3525) + $signed(sext_ln691_20_fu_1611_p1));

assign add_ln691_44_fu_1660_p2 = ($signed(p_Result_3_6_i_i_reg_3535) + $signed(sext_ln691_21_fu_1654_p1));

assign add_ln691_46_fu_1703_p2 = ($signed(p_Result_3_7_i_i_reg_3545) + $signed(sext_ln691_22_fu_1697_p1));

assign add_ln691_48_fu_1746_p2 = ($signed(p_Result_3_8_i_i_reg_3555) + $signed(sext_ln691_23_fu_1740_p1));

assign add_ln691_50_fu_1789_p2 = ($signed(p_Result_3_9_i_i_reg_3565) + $signed(sext_ln691_24_fu_1783_p1));

assign add_ln691_52_fu_1832_p2 = ($signed(p_Result_3_i_i_183_reg_3575) + $signed(sext_ln691_25_fu_1826_p1));

assign add_ln691_54_fu_1875_p2 = ($signed(p_Result_3_10_i_i_reg_3585) + $signed(sext_ln691_26_fu_1869_p1));

assign add_ln691_56_fu_1918_p2 = ($signed(p_Result_3_11_i_i_reg_3595) + $signed(sext_ln691_27_fu_1912_p1));

assign add_ln691_58_fu_1961_p2 = ($signed(p_Result_3_12_i_i_reg_3605) + $signed(sext_ln691_28_fu_1955_p1));

assign add_ln691_60_fu_2004_p2 = ($signed(p_Result_3_13_i_i_reg_3615) + $signed(sext_ln691_29_fu_1998_p1));

assign add_ln691_62_fu_2047_p2 = ($signed(p_Result_3_14_i_i_reg_3625) + $signed(sext_ln691_30_fu_2041_p1));

assign add_ln692_16_fu_2111_p2 = ($signed(select_ln263_16_reg_3641) + $signed(24'd16777088));

assign add_ln692_17_fu_2138_p2 = ($signed(select_ln263_17_reg_3647) + $signed(24'd16777088));

assign add_ln692_18_fu_2165_p2 = ($signed(select_ln263_18_reg_3653) + $signed(24'd16777088));

assign add_ln692_19_fu_2192_p2 = ($signed(select_ln263_19_reg_3659) + $signed(24'd16777088));

assign add_ln692_20_fu_2219_p2 = ($signed(select_ln263_20_reg_3665) + $signed(24'd16777088));

assign add_ln692_21_fu_2246_p2 = ($signed(select_ln263_21_reg_3671) + $signed(24'd16777088));

assign add_ln692_22_fu_2273_p2 = ($signed(select_ln263_22_reg_3677) + $signed(24'd16777088));

assign add_ln692_23_fu_2300_p2 = ($signed(select_ln263_23_reg_3683) + $signed(24'd16777088));

assign add_ln692_24_fu_2327_p2 = ($signed(select_ln263_24_reg_3689) + $signed(24'd16777088));

assign add_ln692_25_fu_2354_p2 = ($signed(select_ln263_25_reg_3695) + $signed(24'd16777088));

assign add_ln692_26_fu_2381_p2 = ($signed(select_ln263_26_reg_3701) + $signed(24'd16777088));

assign add_ln692_27_fu_2408_p2 = ($signed(select_ln263_27_reg_3707) + $signed(24'd16777088));

assign add_ln692_28_fu_2435_p2 = ($signed(select_ln263_28_reg_3713) + $signed(24'd16777088));

assign add_ln692_29_fu_2462_p2 = ($signed(select_ln263_29_reg_3719) + $signed(24'd16777088));

assign add_ln692_30_fu_2489_p2 = ($signed(select_ln263_30_reg_3725) + $signed(24'd16777088));

assign add_ln692_fu_2084_p2 = ($signed(select_ln263_reg_3635) + $signed(24'd16777088));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter7 == 1'b1) & (skip_reg_3161 == 1'd0) & (f3_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((s_conv3_empty_n == 1'b0) | ((skip_reg_3161 == 1'd0) & (s_bias_1_empty_n == 1'b0)) | ((skip_reg_3161 == 1'd0) & (s_scale_1_empty_n == 1'b0)) | ((skip_reg_3161 == 1'd1) & (f3_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter7 == 1'b1) & (skip_reg_3161 == 1'd0) & (f3_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((s_conv3_empty_n == 1'b0) | ((skip_reg_3161 == 1'd0) & (s_bias_1_empty_n == 1'b0)) | ((skip_reg_3161 == 1'd0) & (s_scale_1_empty_n == 1'b0)) | ((skip_reg_3161 == 1'd1) & (f3_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter7 == 1'b1) & (skip_reg_3161 == 1'd0) & (f3_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((s_conv3_empty_n == 1'b0) | ((skip_reg_3161 == 1'd0) & (s_bias_1_empty_n == 1'b0)) | ((skip_reg_3161 == 1'd0) & (s_scale_1_empty_n == 1'b0)) | ((skip_reg_3161 == 1'd1) & (f3_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((relu3_empty_n == 1'b0) | (skip3_empty_n == 1'b0) | (mul_ln93_1_loc_empty_n == 1'b0) | (1'b0 == OC_V_loc_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_block_state10_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state14_pp0_stage0_iter7 = ((skip_reg_3161 == 1'd0) & (f3_full_n == 1'b0));
end

assign ap_block_state7_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter1 = ((s_conv3_empty_n == 1'b0) | ((skip_reg_3161 == 1'd0) & (s_bias_1_empty_n == 1'b0)) | ((skip_reg_3161 == 1'd0) & (s_scale_1_empty_n == 1'b0)) | ((skip_reg_3161 == 1'd1) & (f3_full_n == 1'b0)));
end

assign ap_block_state9_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_2456 = ((skip_reg_3161 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign grp_fu_3001_p2 = 40'd32768;

assign grp_fu_3011_p2 = 40'd32768;

assign grp_fu_3021_p2 = 40'd32768;

assign grp_fu_3031_p2 = 40'd32768;

assign grp_fu_3041_p2 = 40'd32768;

assign grp_fu_3051_p2 = 40'd32768;

assign grp_fu_3061_p2 = 40'd32768;

assign grp_fu_3071_p2 = 40'd32768;

assign grp_fu_3081_p2 = 40'd32768;

assign grp_fu_3091_p2 = 40'd32768;

assign grp_fu_3101_p2 = 40'd32768;

assign grp_fu_310_p0 = grp_fu_310_p00;

assign grp_fu_310_p00 = rep_reg_3185;

assign grp_fu_310_p1 = grp_fu_310_p10;

assign grp_fu_310_p10 = ret_cast_reg_3190;

assign grp_fu_3111_p2 = 40'd32768;

assign grp_fu_3121_p2 = 40'd32768;

assign grp_fu_3131_p2 = 40'd32768;

assign grp_fu_3141_p2 = 40'd32768;

assign grp_fu_3151_p2 = 40'd32768;

assign icmp_ln272_fu_322_p2 = ((indvar_flatten_reg_283 == bound_reg_3205) ? 1'b1 : 1'b0);

assign icmp_ln878_16_fu_2132_p2 = (($signed(add_ln692_16_fu_2111_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_17_fu_2159_p2 = (($signed(add_ln692_17_fu_2138_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_18_fu_2186_p2 = (($signed(add_ln692_18_fu_2165_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_19_fu_2213_p2 = (($signed(add_ln692_19_fu_2192_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_20_fu_2240_p2 = (($signed(add_ln692_20_fu_2219_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_21_fu_2267_p2 = (($signed(add_ln692_21_fu_2246_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_22_fu_2294_p2 = (($signed(add_ln692_22_fu_2273_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_23_fu_2321_p2 = (($signed(add_ln692_23_fu_2300_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_24_fu_2348_p2 = (($signed(add_ln692_24_fu_2327_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_25_fu_2375_p2 = (($signed(add_ln692_25_fu_2354_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_26_fu_2402_p2 = (($signed(add_ln692_26_fu_2381_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_27_fu_2429_p2 = (($signed(add_ln692_27_fu_2408_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_28_fu_2456_p2 = (($signed(add_ln692_28_fu_2435_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_29_fu_2483_p2 = (($signed(add_ln692_29_fu_2462_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_30_fu_2510_p2 = (($signed(add_ln692_30_fu_2489_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_fu_2105_p2 = (($signed(add_ln692_fu_2084_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln886_16_fu_2126_p2 = (($signed(tmp_50_fu_2116_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_17_fu_2153_p2 = (($signed(tmp_52_fu_2143_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_18_fu_2180_p2 = (($signed(tmp_54_fu_2170_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_19_fu_2207_p2 = (($signed(tmp_56_fu_2197_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_20_fu_2234_p2 = (($signed(tmp_58_fu_2224_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_21_fu_2261_p2 = (($signed(tmp_60_fu_2251_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_22_fu_2288_p2 = (($signed(tmp_62_fu_2278_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_23_fu_2315_p2 = (($signed(tmp_64_fu_2305_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_24_fu_2342_p2 = (($signed(tmp_66_fu_2332_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_25_fu_2369_p2 = (($signed(tmp_68_fu_2359_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_26_fu_2396_p2 = (($signed(tmp_70_fu_2386_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_27_fu_2423_p2 = (($signed(tmp_72_fu_2413_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_28_fu_2450_p2 = (($signed(tmp_74_fu_2440_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_29_fu_2477_p2 = (($signed(tmp_76_fu_2467_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_30_fu_2504_p2 = (($signed(tmp_78_fu_2494_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_fu_2099_p2 = (($signed(tmp_48_fu_2089_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign or_ln69_16_fu_2560_p2 = (icmp_ln886_16_reg_3742 | icmp_ln878_16_reg_3748);

assign or_ln69_17_fu_2588_p2 = (icmp_ln886_17_reg_3753 | icmp_ln878_17_reg_3759);

assign or_ln69_18_fu_2616_p2 = (icmp_ln886_18_reg_3764 | icmp_ln878_18_reg_3770);

assign or_ln69_19_fu_2644_p2 = (icmp_ln886_19_reg_3775 | icmp_ln878_19_reg_3781);

assign or_ln69_20_fu_2672_p2 = (icmp_ln886_20_reg_3786 | icmp_ln878_20_reg_3792);

assign or_ln69_21_fu_2700_p2 = (icmp_ln886_21_reg_3797 | icmp_ln878_21_reg_3803);

assign or_ln69_22_fu_2728_p2 = (icmp_ln886_22_reg_3808 | icmp_ln878_22_reg_3814);

assign or_ln69_23_fu_2756_p2 = (icmp_ln886_23_reg_3819 | icmp_ln878_23_reg_3825);

assign or_ln69_24_fu_2784_p2 = (icmp_ln886_24_reg_3830 | icmp_ln878_24_reg_3836);

assign or_ln69_25_fu_2812_p2 = (icmp_ln886_25_reg_3841 | icmp_ln878_25_reg_3847);

assign or_ln69_26_fu_2840_p2 = (icmp_ln886_26_reg_3852 | icmp_ln878_26_reg_3858);

assign or_ln69_27_fu_2868_p2 = (icmp_ln886_27_reg_3863 | icmp_ln878_27_reg_3869);

assign or_ln69_28_fu_2896_p2 = (icmp_ln886_28_reg_3874 | icmp_ln878_28_reg_3880);

assign or_ln69_29_fu_2924_p2 = (icmp_ln886_29_reg_3885 | icmp_ln878_29_reg_3891);

assign or_ln69_30_fu_2952_p2 = (icmp_ln886_30_reg_3896 | icmp_ln878_30_reg_3902);

assign or_ln69_fu_2532_p2 = (icmp_ln886_reg_3731 | icmp_ln878_reg_3737);

assign p_Result_1_10_i_i_fu_777_p4 = {{s_scale_1_dout[191:176]}};

assign p_Result_1_11_i_i_fu_805_p4 = {{s_scale_1_dout[207:192]}};

assign p_Result_1_12_i_i_fu_833_p4 = {{s_scale_1_dout[223:208]}};

assign p_Result_1_13_i_i_fu_861_p4 = {{s_scale_1_dout[239:224]}};

assign p_Result_1_14_i_i_fu_889_p4 = {{s_scale_1_dout[255:240]}};

assign p_Result_1_1_i_i_fu_497_p4 = {{s_scale_1_dout[31:16]}};

assign p_Result_1_2_i_i_fu_525_p4 = {{s_scale_1_dout[47:32]}};

assign p_Result_1_3_i_i_fu_553_p4 = {{s_scale_1_dout[63:48]}};

assign p_Result_1_4_i_i_fu_581_p4 = {{s_scale_1_dout[79:64]}};

assign p_Result_1_5_i_i_fu_609_p4 = {{s_scale_1_dout[95:80]}};

assign p_Result_1_6_i_i_fu_637_p4 = {{s_scale_1_dout[111:96]}};

assign p_Result_1_7_i_i_fu_665_p4 = {{s_scale_1_dout[127:112]}};

assign p_Result_1_8_i_i_fu_693_p4 = {{s_scale_1_dout[143:128]}};

assign p_Result_1_9_i_i_fu_721_p4 = {{s_scale_1_dout[159:144]}};

assign p_Result_1_i_i_fu_749_p4 = {{s_scale_1_dout[175:160]}};

assign p_Result_4_i_i_fu_2964_p17 = {{{{{{{{{{{{{{{{select_ln69_62_fu_2956_p3}, {select_ln69_60_fu_2928_p3}}, {select_ln69_58_fu_2900_p3}}, {select_ln69_56_fu_2872_p3}}, {select_ln69_54_fu_2844_p3}}, {select_ln69_52_fu_2816_p3}}, {select_ln69_50_fu_2788_p3}}, {select_ln69_48_fu_2760_p3}}, {select_ln69_46_fu_2732_p3}}, {select_ln69_44_fu_2704_p3}}, {select_ln69_42_fu_2676_p3}}, {select_ln69_40_fu_2648_p3}}, {select_ln69_38_fu_2620_p3}}, {select_ln69_36_fu_2592_p3}}, {select_ln69_34_fu_2564_p3}}, {select_ln69_32_fu_2536_p3}};

assign p_Result_i_i_fu_1071_p17 = {{{{{{{{{{{{{{{{trunc_ln69_28_fu_1061_p4}, {trunc_ln69_27_fu_1051_p4}}, {trunc_ln69_26_fu_1041_p4}}, {trunc_ln69_25_fu_1031_p4}}, {trunc_ln69_24_fu_1021_p4}}, {trunc_ln69_23_fu_1011_p4}}, {trunc_ln69_22_fu_1001_p4}}, {trunc_ln69_21_fu_991_p4}}, {trunc_ln69_20_fu_981_p4}}, {trunc_ln69_19_fu_971_p4}}, {trunc_ln69_18_fu_961_p4}}, {trunc_ln69_17_fu_951_p4}}, {trunc_ln69_16_fu_941_p4}}, {trunc_ln69_15_fu_931_p4}}, {trunc_ln69_s_fu_921_p4}}, {trunc_ln69_fu_917_p1}};

assign select_ln263_16_fu_1475_p3 = ((relu_reg_3165[0:0] == 1'b1) ? zext_ln299_16_fu_1471_p1 : add_ln691_34_fu_1445_p2);

assign select_ln263_17_fu_1518_p3 = ((relu_reg_3165[0:0] == 1'b1) ? zext_ln299_17_fu_1514_p1 : add_ln691_36_fu_1488_p2);

assign select_ln263_18_fu_1561_p3 = ((relu_reg_3165[0:0] == 1'b1) ? zext_ln299_18_fu_1557_p1 : add_ln691_38_fu_1531_p2);

assign select_ln263_19_fu_1604_p3 = ((relu_reg_3165[0:0] == 1'b1) ? zext_ln299_19_fu_1600_p1 : add_ln691_40_fu_1574_p2);

assign select_ln263_20_fu_1647_p3 = ((relu_reg_3165[0:0] == 1'b1) ? zext_ln299_20_fu_1643_p1 : add_ln691_42_fu_1617_p2);

assign select_ln263_21_fu_1690_p3 = ((relu_reg_3165[0:0] == 1'b1) ? zext_ln299_21_fu_1686_p1 : add_ln691_44_fu_1660_p2);

assign select_ln263_22_fu_1733_p3 = ((relu_reg_3165[0:0] == 1'b1) ? zext_ln299_22_fu_1729_p1 : add_ln691_46_fu_1703_p2);

assign select_ln263_23_fu_1776_p3 = ((relu_reg_3165[0:0] == 1'b1) ? zext_ln299_23_fu_1772_p1 : add_ln691_48_fu_1746_p2);

assign select_ln263_24_fu_1819_p3 = ((relu_reg_3165[0:0] == 1'b1) ? zext_ln299_24_fu_1815_p1 : add_ln691_50_fu_1789_p2);

assign select_ln263_25_fu_1862_p3 = ((relu_reg_3165[0:0] == 1'b1) ? zext_ln299_25_fu_1858_p1 : add_ln691_52_fu_1832_p2);

assign select_ln263_26_fu_1905_p3 = ((relu_reg_3165[0:0] == 1'b1) ? zext_ln299_26_fu_1901_p1 : add_ln691_54_fu_1875_p2);

assign select_ln263_27_fu_1948_p3 = ((relu_reg_3165[0:0] == 1'b1) ? zext_ln299_27_fu_1944_p1 : add_ln691_56_fu_1918_p2);

assign select_ln263_28_fu_1991_p3 = ((relu_reg_3165[0:0] == 1'b1) ? zext_ln299_28_fu_1987_p1 : add_ln691_58_fu_1961_p2);

assign select_ln263_29_fu_2034_p3 = ((relu_reg_3165[0:0] == 1'b1) ? zext_ln299_29_fu_2030_p1 : add_ln691_60_fu_2004_p2);

assign select_ln263_30_fu_2077_p3 = ((relu_reg_3165[0:0] == 1'b1) ? zext_ln299_30_fu_2073_p1 : add_ln691_62_fu_2047_p2);

assign select_ln263_fu_1432_p3 = ((relu_reg_3165[0:0] == 1'b1) ? zext_ln299_fu_1428_p1 : add_ln691_32_fu_1402_p2);

assign select_ln298_16_fu_1463_p3 = ((tmp_49_fu_1455_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_16_fu_1450_p2);

assign select_ln298_17_fu_1506_p3 = ((tmp_51_fu_1498_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_17_fu_1493_p2);

assign select_ln298_18_fu_1549_p3 = ((tmp_53_fu_1541_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_18_fu_1536_p2);

assign select_ln298_19_fu_1592_p3 = ((tmp_55_fu_1584_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_19_fu_1579_p2);

assign select_ln298_20_fu_1635_p3 = ((tmp_57_fu_1627_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_20_fu_1622_p2);

assign select_ln298_21_fu_1678_p3 = ((tmp_59_fu_1670_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_21_fu_1665_p2);

assign select_ln298_22_fu_1721_p3 = ((tmp_61_fu_1713_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_22_fu_1708_p2);

assign select_ln298_23_fu_1764_p3 = ((tmp_63_fu_1756_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_23_fu_1751_p2);

assign select_ln298_24_fu_1807_p3 = ((tmp_65_fu_1799_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_24_fu_1794_p2);

assign select_ln298_25_fu_1850_p3 = ((tmp_67_fu_1842_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_25_fu_1837_p2);

assign select_ln298_26_fu_1893_p3 = ((tmp_69_fu_1885_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_26_fu_1880_p2);

assign select_ln298_27_fu_1936_p3 = ((tmp_71_fu_1928_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_27_fu_1923_p2);

assign select_ln298_28_fu_1979_p3 = ((tmp_73_fu_1971_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_28_fu_1966_p2);

assign select_ln298_29_fu_2022_p3 = ((tmp_75_fu_2014_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_29_fu_2009_p2);

assign select_ln298_30_fu_2065_p3 = ((tmp_77_fu_2057_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_30_fu_2052_p2);

assign select_ln298_fu_1420_p3 = ((tmp_47_fu_1412_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_fu_1407_p2);

assign select_ln69_32_fu_2536_p3 = ((or_ln69_fu_2532_p2[0:0] == 1'b1) ? select_ln69_fu_2525_p3 : xor_ln69_fu_2519_p2);

assign select_ln69_33_fu_2553_p3 = ((icmp_ln886_16_reg_3742[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_34_fu_2564_p3 = ((or_ln69_16_fu_2560_p2[0:0] == 1'b1) ? select_ln69_33_fu_2553_p3 : xor_ln69_16_fu_2547_p2);

assign select_ln69_35_fu_2581_p3 = ((icmp_ln886_17_reg_3753[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_36_fu_2592_p3 = ((or_ln69_17_fu_2588_p2[0:0] == 1'b1) ? select_ln69_35_fu_2581_p3 : xor_ln69_17_fu_2575_p2);

assign select_ln69_37_fu_2609_p3 = ((icmp_ln886_18_reg_3764[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_38_fu_2620_p3 = ((or_ln69_18_fu_2616_p2[0:0] == 1'b1) ? select_ln69_37_fu_2609_p3 : xor_ln69_18_fu_2603_p2);

assign select_ln69_39_fu_2637_p3 = ((icmp_ln886_19_reg_3775[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_40_fu_2648_p3 = ((or_ln69_19_fu_2644_p2[0:0] == 1'b1) ? select_ln69_39_fu_2637_p3 : xor_ln69_19_fu_2631_p2);

assign select_ln69_41_fu_2665_p3 = ((icmp_ln886_20_reg_3786[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_42_fu_2676_p3 = ((or_ln69_20_fu_2672_p2[0:0] == 1'b1) ? select_ln69_41_fu_2665_p3 : xor_ln69_20_fu_2659_p2);

assign select_ln69_43_fu_2693_p3 = ((icmp_ln886_21_reg_3797[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_44_fu_2704_p3 = ((or_ln69_21_fu_2700_p2[0:0] == 1'b1) ? select_ln69_43_fu_2693_p3 : xor_ln69_21_fu_2687_p2);

assign select_ln69_45_fu_2721_p3 = ((icmp_ln886_22_reg_3808[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_46_fu_2732_p3 = ((or_ln69_22_fu_2728_p2[0:0] == 1'b1) ? select_ln69_45_fu_2721_p3 : xor_ln69_22_fu_2715_p2);

assign select_ln69_47_fu_2749_p3 = ((icmp_ln886_23_reg_3819[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_48_fu_2760_p3 = ((or_ln69_23_fu_2756_p2[0:0] == 1'b1) ? select_ln69_47_fu_2749_p3 : xor_ln69_23_fu_2743_p2);

assign select_ln69_49_fu_2777_p3 = ((icmp_ln886_24_reg_3830[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_50_fu_2788_p3 = ((or_ln69_24_fu_2784_p2[0:0] == 1'b1) ? select_ln69_49_fu_2777_p3 : xor_ln69_24_fu_2771_p2);

assign select_ln69_51_fu_2805_p3 = ((icmp_ln886_25_reg_3841[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_52_fu_2816_p3 = ((or_ln69_25_fu_2812_p2[0:0] == 1'b1) ? select_ln69_51_fu_2805_p3 : xor_ln69_25_fu_2799_p2);

assign select_ln69_53_fu_2833_p3 = ((icmp_ln886_26_reg_3852[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_54_fu_2844_p3 = ((or_ln69_26_fu_2840_p2[0:0] == 1'b1) ? select_ln69_53_fu_2833_p3 : xor_ln69_26_fu_2827_p2);

assign select_ln69_55_fu_2861_p3 = ((icmp_ln886_27_reg_3863[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_56_fu_2872_p3 = ((or_ln69_27_fu_2868_p2[0:0] == 1'b1) ? select_ln69_55_fu_2861_p3 : xor_ln69_27_fu_2855_p2);

assign select_ln69_57_fu_2889_p3 = ((icmp_ln886_28_reg_3874[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_58_fu_2900_p3 = ((or_ln69_28_fu_2896_p2[0:0] == 1'b1) ? select_ln69_57_fu_2889_p3 : xor_ln69_28_fu_2883_p2);

assign select_ln69_59_fu_2917_p3 = ((icmp_ln886_29_reg_3885[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_60_fu_2928_p3 = ((or_ln69_29_fu_2924_p2[0:0] == 1'b1) ? select_ln69_59_fu_2917_p3 : xor_ln69_29_fu_2911_p2);

assign select_ln69_61_fu_2945_p3 = ((icmp_ln886_30_reg_3896[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_62_fu_2956_p3 = ((or_ln69_30_fu_2952_p2[0:0] == 1'b1) ? select_ln69_61_fu_2945_p3 : xor_ln69_30_fu_2939_p2);

assign select_ln69_fu_2525_p3 = ((icmp_ln886_reg_3731[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign sext_ln691_16_fu_1439_p1 = p_Result_2_1_i_i_reg_3235_pp0_iter4_reg;

assign sext_ln691_17_fu_1482_p1 = p_Result_2_2_i_i_reg_3251_pp0_iter4_reg;

assign sext_ln691_18_fu_1525_p1 = p_Result_2_3_i_i_reg_3267_pp0_iter4_reg;

assign sext_ln691_19_fu_1568_p1 = p_Result_2_4_i_i_reg_3283_pp0_iter4_reg;

assign sext_ln691_20_fu_1611_p1 = p_Result_2_5_i_i_reg_3299_pp0_iter4_reg;

assign sext_ln691_21_fu_1654_p1 = p_Result_2_6_i_i_reg_3315_pp0_iter4_reg;

assign sext_ln691_22_fu_1697_p1 = p_Result_2_7_i_i_reg_3331_pp0_iter4_reg;

assign sext_ln691_23_fu_1740_p1 = p_Result_2_8_i_i_reg_3347_pp0_iter4_reg;

assign sext_ln691_24_fu_1783_p1 = p_Result_2_9_i_i_reg_3363_pp0_iter4_reg;

assign sext_ln691_25_fu_1826_p1 = p_Result_2_i_i_reg_3379_pp0_iter4_reg;

assign sext_ln691_26_fu_1869_p1 = p_Result_2_10_i_i_reg_3395_pp0_iter4_reg;

assign sext_ln691_27_fu_1912_p1 = p_Result_2_11_i_i_reg_3411_pp0_iter4_reg;

assign sext_ln691_28_fu_1955_p1 = p_Result_2_12_i_i_reg_3427_pp0_iter4_reg;

assign sext_ln691_29_fu_1998_p1 = p_Result_2_13_i_i_reg_3443_pp0_iter4_reg;

assign sext_ln691_30_fu_2041_p1 = p_Result_2_14_i_i_reg_3459_pp0_iter4_reg;

assign sext_ln691_32_fu_1399_p1 = trunc_ln674_2_reg_3219_pp0_iter4_reg;

assign sext_ln691_33_fu_1442_p1 = p_Result_2_1_i_i_reg_3235_pp0_iter4_reg;

assign sext_ln691_34_fu_1485_p1 = p_Result_2_2_i_i_reg_3251_pp0_iter4_reg;

assign sext_ln691_35_fu_1528_p1 = p_Result_2_3_i_i_reg_3267_pp0_iter4_reg;

assign sext_ln691_36_fu_1571_p1 = p_Result_2_4_i_i_reg_3283_pp0_iter4_reg;

assign sext_ln691_37_fu_1614_p1 = p_Result_2_5_i_i_reg_3299_pp0_iter4_reg;

assign sext_ln691_38_fu_1657_p1 = p_Result_2_6_i_i_reg_3315_pp0_iter4_reg;

assign sext_ln691_39_fu_1700_p1 = p_Result_2_7_i_i_reg_3331_pp0_iter4_reg;

assign sext_ln691_40_fu_1743_p1 = p_Result_2_8_i_i_reg_3347_pp0_iter4_reg;

assign sext_ln691_41_fu_1786_p1 = p_Result_2_9_i_i_reg_3363_pp0_iter4_reg;

assign sext_ln691_42_fu_1829_p1 = p_Result_2_i_i_reg_3379_pp0_iter4_reg;

assign sext_ln691_43_fu_1872_p1 = p_Result_2_10_i_i_reg_3395_pp0_iter4_reg;

assign sext_ln691_44_fu_1915_p1 = p_Result_2_11_i_i_reg_3411_pp0_iter4_reg;

assign sext_ln691_45_fu_1958_p1 = p_Result_2_12_i_i_reg_3427_pp0_iter4_reg;

assign sext_ln691_46_fu_2001_p1 = p_Result_2_13_i_i_reg_3443_pp0_iter4_reg;

assign sext_ln691_47_fu_2044_p1 = p_Result_2_14_i_i_reg_3459_pp0_iter4_reg;

assign sext_ln691_fu_1396_p1 = trunc_ln674_2_reg_3219_pp0_iter4_reg;

assign tmp_47_fu_1412_p3 = add_ln691_32_fu_1402_p2[32'd23];

assign tmp_48_fu_2089_p4 = {{add_ln692_fu_2084_p2[23:7]}};

assign tmp_49_fu_1455_p3 = add_ln691_34_fu_1445_p2[32'd23];

assign tmp_50_fu_2116_p4 = {{add_ln692_16_fu_2111_p2[23:7]}};

assign tmp_51_fu_1498_p3 = add_ln691_36_fu_1488_p2[32'd23];

assign tmp_52_fu_2143_p4 = {{add_ln692_17_fu_2138_p2[23:7]}};

assign tmp_53_fu_1541_p3 = add_ln691_38_fu_1531_p2[32'd23];

assign tmp_54_fu_2170_p4 = {{add_ln692_18_fu_2165_p2[23:7]}};

assign tmp_55_fu_1584_p3 = add_ln691_40_fu_1574_p2[32'd23];

assign tmp_56_fu_2197_p4 = {{add_ln692_19_fu_2192_p2[23:7]}};

assign tmp_57_fu_1627_p3 = add_ln691_42_fu_1617_p2[32'd23];

assign tmp_58_fu_2224_p4 = {{add_ln692_20_fu_2219_p2[23:7]}};

assign tmp_59_fu_1670_p3 = add_ln691_44_fu_1660_p2[32'd23];

assign tmp_60_fu_2251_p4 = {{add_ln692_21_fu_2246_p2[23:7]}};

assign tmp_61_fu_1713_p3 = add_ln691_46_fu_1703_p2[32'd23];

assign tmp_62_fu_2278_p4 = {{add_ln692_22_fu_2273_p2[23:7]}};

assign tmp_63_fu_1756_p3 = add_ln691_48_fu_1746_p2[32'd23];

assign tmp_64_fu_2305_p4 = {{add_ln692_23_fu_2300_p2[23:7]}};

assign tmp_65_fu_1799_p3 = add_ln691_50_fu_1789_p2[32'd23];

assign tmp_66_fu_2332_p4 = {{add_ln692_24_fu_2327_p2[23:7]}};

assign tmp_67_fu_1842_p3 = add_ln691_52_fu_1832_p2[32'd23];

assign tmp_68_fu_2359_p4 = {{add_ln692_25_fu_2354_p2[23:7]}};

assign tmp_69_fu_1885_p3 = add_ln691_54_fu_1875_p2[32'd23];

assign tmp_70_fu_2386_p4 = {{add_ln692_26_fu_2381_p2[23:7]}};

assign tmp_71_fu_1928_p3 = add_ln691_56_fu_1918_p2[32'd23];

assign tmp_72_fu_2413_p4 = {{add_ln692_27_fu_2408_p2[23:7]}};

assign tmp_73_fu_1971_p3 = add_ln691_58_fu_1961_p2[32'd23];

assign tmp_74_fu_2440_p4 = {{add_ln692_28_fu_2435_p2[23:7]}};

assign tmp_75_fu_2014_p3 = add_ln691_60_fu_2004_p2[32'd23];

assign tmp_76_fu_2467_p4 = {{add_ln692_29_fu_2462_p2[23:7]}};

assign tmp_77_fu_2057_p3 = add_ln691_62_fu_2047_p2[32'd23];

assign tmp_78_fu_2494_p4 = {{add_ln692_30_fu_2489_p2[23:7]}};

assign tmp_data_V_0_fu_327_p1 = s_conv3_dout[23:0];

assign tmp_data_V_10_fu_421_p4 = {{s_conv3_dout[343:320]}};

assign tmp_data_V_11_fu_431_p4 = {{s_conv3_dout[375:352]}};

assign tmp_data_V_12_fu_441_p4 = {{s_conv3_dout[407:384]}};

assign tmp_data_V_13_fu_451_p4 = {{s_conv3_dout[439:416]}};

assign tmp_data_V_14_fu_461_p4 = {{s_conv3_dout[471:448]}};

assign tmp_data_V_15_fu_471_p4 = {{s_conv3_dout[503:480]}};

assign tmp_data_V_1_fu_331_p4 = {{s_conv3_dout[55:32]}};

assign tmp_data_V_2_fu_341_p4 = {{s_conv3_dout[87:64]}};

assign tmp_data_V_3_fu_351_p4 = {{s_conv3_dout[119:96]}};

assign tmp_data_V_4_fu_361_p4 = {{s_conv3_dout[151:128]}};

assign tmp_data_V_5_fu_371_p4 = {{s_conv3_dout[183:160]}};

assign tmp_data_V_6_fu_381_p4 = {{s_conv3_dout[215:192]}};

assign tmp_data_V_7_fu_391_p4 = {{s_conv3_dout[247:224]}};

assign tmp_data_V_8_fu_401_p4 = {{s_conv3_dout[279:256]}};

assign tmp_data_V_9_fu_411_p4 = {{s_conv3_dout[311:288]}};

assign trunc_ln674_2_fu_485_p1 = s_bias_1_dout[15:0];

assign trunc_ln674_fu_481_p1 = s_scale_1_dout[15:0];

assign trunc_ln692_16_fu_2544_p1 = select_ln263_16_reg_3641_pp0_iter6_reg[7:0];

assign trunc_ln692_17_fu_2572_p1 = select_ln263_17_reg_3647_pp0_iter6_reg[7:0];

assign trunc_ln692_18_fu_2600_p1 = select_ln263_18_reg_3653_pp0_iter6_reg[7:0];

assign trunc_ln692_19_fu_2628_p1 = select_ln263_19_reg_3659_pp0_iter6_reg[7:0];

assign trunc_ln692_20_fu_2656_p1 = select_ln263_20_reg_3665_pp0_iter6_reg[7:0];

assign trunc_ln692_21_fu_2684_p1 = select_ln263_21_reg_3671_pp0_iter6_reg[7:0];

assign trunc_ln692_22_fu_2712_p1 = select_ln263_22_reg_3677_pp0_iter6_reg[7:0];

assign trunc_ln692_23_fu_2740_p1 = select_ln263_23_reg_3683_pp0_iter6_reg[7:0];

assign trunc_ln692_24_fu_2768_p1 = select_ln263_24_reg_3689_pp0_iter6_reg[7:0];

assign trunc_ln692_25_fu_2796_p1 = select_ln263_25_reg_3695_pp0_iter6_reg[7:0];

assign trunc_ln692_26_fu_2824_p1 = select_ln263_26_reg_3701_pp0_iter6_reg[7:0];

assign trunc_ln692_27_fu_2852_p1 = select_ln263_27_reg_3707_pp0_iter6_reg[7:0];

assign trunc_ln692_28_fu_2880_p1 = select_ln263_28_reg_3713_pp0_iter6_reg[7:0];

assign trunc_ln692_29_fu_2908_p1 = select_ln263_29_reg_3719_pp0_iter6_reg[7:0];

assign trunc_ln692_30_fu_2936_p1 = select_ln263_30_reg_3725_pp0_iter6_reg[7:0];

assign trunc_ln692_fu_2516_p1 = select_ln263_reg_3635_pp0_iter6_reg[7:0];

assign trunc_ln69_15_fu_931_p4 = {{s_conv3_dout[71:64]}};

assign trunc_ln69_16_fu_941_p4 = {{s_conv3_dout[103:96]}};

assign trunc_ln69_17_fu_951_p4 = {{s_conv3_dout[135:128]}};

assign trunc_ln69_18_fu_961_p4 = {{s_conv3_dout[167:160]}};

assign trunc_ln69_19_fu_971_p4 = {{s_conv3_dout[199:192]}};

assign trunc_ln69_20_fu_981_p4 = {{s_conv3_dout[231:224]}};

assign trunc_ln69_21_fu_991_p4 = {{s_conv3_dout[263:256]}};

assign trunc_ln69_22_fu_1001_p4 = {{s_conv3_dout[295:288]}};

assign trunc_ln69_23_fu_1011_p4 = {{s_conv3_dout[327:320]}};

assign trunc_ln69_24_fu_1021_p4 = {{s_conv3_dout[359:352]}};

assign trunc_ln69_25_fu_1031_p4 = {{s_conv3_dout[391:384]}};

assign trunc_ln69_26_fu_1041_p4 = {{s_conv3_dout[423:416]}};

assign trunc_ln69_27_fu_1051_p4 = {{s_conv3_dout[455:448]}};

assign trunc_ln69_28_fu_1061_p4 = {{s_conv3_dout[487:480]}};

assign trunc_ln69_fu_917_p1 = s_conv3_dout[7:0];

assign trunc_ln69_s_fu_921_p4 = {{s_conv3_dout[39:32]}};

assign xor_ln69_16_fu_2547_p2 = (trunc_ln692_16_fu_2544_p1 ^ 8'd128);

assign xor_ln69_17_fu_2575_p2 = (trunc_ln692_17_fu_2572_p1 ^ 8'd128);

assign xor_ln69_18_fu_2603_p2 = (trunc_ln692_18_fu_2600_p1 ^ 8'd128);

assign xor_ln69_19_fu_2631_p2 = (trunc_ln692_19_fu_2628_p1 ^ 8'd128);

assign xor_ln69_20_fu_2659_p2 = (trunc_ln692_20_fu_2656_p1 ^ 8'd128);

assign xor_ln69_21_fu_2687_p2 = (trunc_ln692_21_fu_2684_p1 ^ 8'd128);

assign xor_ln69_22_fu_2715_p2 = (trunc_ln692_22_fu_2712_p1 ^ 8'd128);

assign xor_ln69_23_fu_2743_p2 = (trunc_ln692_23_fu_2740_p1 ^ 8'd128);

assign xor_ln69_24_fu_2771_p2 = (trunc_ln692_24_fu_2768_p1 ^ 8'd128);

assign xor_ln69_25_fu_2799_p2 = (trunc_ln692_25_fu_2796_p1 ^ 8'd128);

assign xor_ln69_26_fu_2827_p2 = (trunc_ln692_26_fu_2824_p1 ^ 8'd128);

assign xor_ln69_27_fu_2855_p2 = (trunc_ln692_27_fu_2852_p1 ^ 8'd128);

assign xor_ln69_28_fu_2883_p2 = (trunc_ln692_28_fu_2880_p1 ^ 8'd128);

assign xor_ln69_29_fu_2911_p2 = (trunc_ln692_29_fu_2908_p1 ^ 8'd128);

assign xor_ln69_30_fu_2939_p2 = (trunc_ln692_30_fu_2936_p1 ^ 8'd128);

assign xor_ln69_fu_2519_p2 = (trunc_ln692_fu_2516_p1 ^ 8'd128);

assign zext_ln299_16_fu_1471_p1 = select_ln298_16_fu_1463_p3;

assign zext_ln299_17_fu_1514_p1 = select_ln298_17_fu_1506_p3;

assign zext_ln299_18_fu_1557_p1 = select_ln298_18_fu_1549_p3;

assign zext_ln299_19_fu_1600_p1 = select_ln298_19_fu_1592_p3;

assign zext_ln299_20_fu_1643_p1 = select_ln298_20_fu_1635_p3;

assign zext_ln299_21_fu_1686_p1 = select_ln298_21_fu_1678_p3;

assign zext_ln299_22_fu_1729_p1 = select_ln298_22_fu_1721_p3;

assign zext_ln299_23_fu_1772_p1 = select_ln298_23_fu_1764_p3;

assign zext_ln299_24_fu_1815_p1 = select_ln298_24_fu_1807_p3;

assign zext_ln299_25_fu_1858_p1 = select_ln298_25_fu_1850_p3;

assign zext_ln299_26_fu_1901_p1 = select_ln298_26_fu_1893_p3;

assign zext_ln299_27_fu_1944_p1 = select_ln298_27_fu_1936_p3;

assign zext_ln299_28_fu_1987_p1 = select_ln298_28_fu_1979_p3;

assign zext_ln299_29_fu_2030_p1 = select_ln298_29_fu_2022_p3;

assign zext_ln299_30_fu_2073_p1 = select_ln298_30_fu_2065_p3;

assign zext_ln299_fu_1428_p1 = select_ln298_fu_1420_p3;

endmodule //top_quantize_mul_shift_24_8_16_16_16_16_s
