// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_quantize_mul_shift_24_8_16_16_16_16_23 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        s_conv1_dout,
        s_conv1_empty_n,
        s_conv1_read,
        f1_din,
        f1_full_n,
        f1_write,
        s_scale_dout,
        s_scale_empty_n,
        s_scale_read,
        s_bias_dout,
        s_bias_empty_n,
        s_bias_read,
        mul_ln31_1_loc_dout,
        mul_ln31_1_loc_empty_n,
        mul_ln31_1_loc_read,
        OC_V_loc_dout,
        OC_V_loc_empty_n,
        OC_V_loc_read,
        skip1_dout,
        skip1_empty_n,
        skip1_read,
        relu1_dout,
        relu1_empty_n,
        relu1_read,
        OC_V_loc_out_din,
        OC_V_loc_out_full_n,
        OC_V_loc_out_write
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_pp0_stage0 = 8'd64;
parameter    ap_ST_fsm_state15 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [511:0] s_conv1_dout;
input   s_conv1_empty_n;
output   s_conv1_read;
output  [127:0] f1_din;
input   f1_full_n;
output   f1_write;
input  [255:0] s_scale_dout;
input   s_scale_empty_n;
output   s_scale_read;
input  [255:0] s_bias_dout;
input   s_bias_empty_n;
output   s_bias_read;
input  [31:0] mul_ln31_1_loc_dout;
input   mul_ln31_1_loc_empty_n;
output   mul_ln31_1_loc_read;
input  [15:0] OC_V_loc_dout;
input   OC_V_loc_empty_n;
output   OC_V_loc_read;
input  [0:0] skip1_dout;
input   skip1_empty_n;
output   skip1_read;
input  [0:0] relu1_dout;
input   relu1_empty_n;
output   relu1_read;
output  [15:0] OC_V_loc_out_din;
input   OC_V_loc_out_full_n;
output   OC_V_loc_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg s_conv1_read;
reg[127:0] f1_din;
reg f1_write;
reg s_scale_read;
reg s_bias_read;
reg mul_ln31_1_loc_read;
reg OC_V_loc_read;
reg skip1_read;
reg relu1_read;
reg OC_V_loc_out_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    s_conv1_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg    f1_blk_n;
reg   [0:0] skip_reg_3173;
reg    ap_enable_reg_pp0_iter7;
reg    s_scale_blk_n;
reg    s_bias_blk_n;
reg    mul_ln31_1_loc_blk_n;
reg    OC_V_loc_blk_n;
reg    skip1_blk_n;
reg    relu1_blk_n;
reg    OC_V_loc_out_blk_n;
reg   [43:0] indvar_flatten_reg_295;
reg   [0:0] relu_reg_3177;
reg   [31:0] rep_reg_3197;
reg   [11:0] ret_cast_reg_3202;
wire    ap_CS_fsm_state2;
wire   [43:0] grp_fu_322_p2;
reg   [43:0] bound_reg_3217;
wire    ap_CS_fsm_state6;
wire   [43:0] add_ln272_fu_328_p2;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state7_pp0_stage0_iter0;
reg    ap_block_state8_pp0_stage0_iter1;
wire    ap_block_state9_pp0_stage0_iter2;
wire    ap_block_state10_pp0_stage0_iter3;
wire    ap_block_state11_pp0_stage0_iter4;
wire    ap_block_state12_pp0_stage0_iter5;
wire    ap_block_state13_pp0_stage0_iter6;
reg    ap_block_state14_pp0_stage0_iter7;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln272_fu_334_p2;
wire  signed [15:0] trunc_ln674_1_fu_497_p1;
reg  signed [15:0] trunc_ln674_1_reg_3231;
reg  signed [15:0] trunc_ln674_1_reg_3231_pp0_iter2_reg;
reg  signed [15:0] trunc_ln674_1_reg_3231_pp0_iter3_reg;
reg  signed [15:0] trunc_ln674_1_reg_3231_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_1_i_i_reg_3247;
reg  signed [15:0] p_Result_2_1_i_i_reg_3247_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_1_i_i_reg_3247_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_1_i_i_reg_3247_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_2_i_i_reg_3263;
reg  signed [15:0] p_Result_2_2_i_i_reg_3263_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_2_i_i_reg_3263_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_2_i_i_reg_3263_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_3_i_i_reg_3279;
reg  signed [15:0] p_Result_2_3_i_i_reg_3279_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_3_i_i_reg_3279_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_3_i_i_reg_3279_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_4_i_i_reg_3295;
reg  signed [15:0] p_Result_2_4_i_i_reg_3295_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_4_i_i_reg_3295_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_4_i_i_reg_3295_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_5_i_i_reg_3311;
reg  signed [15:0] p_Result_2_5_i_i_reg_3311_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_5_i_i_reg_3311_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_5_i_i_reg_3311_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_6_i_i_reg_3327;
reg  signed [15:0] p_Result_2_6_i_i_reg_3327_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_6_i_i_reg_3327_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_6_i_i_reg_3327_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_7_i_i_reg_3343;
reg  signed [15:0] p_Result_2_7_i_i_reg_3343_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_7_i_i_reg_3343_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_7_i_i_reg_3343_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_8_i_i_reg_3359;
reg  signed [15:0] p_Result_2_8_i_i_reg_3359_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_8_i_i_reg_3359_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_8_i_i_reg_3359_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_9_i_i_reg_3375;
reg  signed [15:0] p_Result_2_9_i_i_reg_3375_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_9_i_i_reg_3375_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_9_i_i_reg_3375_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_i_i_reg_3391;
reg  signed [15:0] p_Result_2_i_i_reg_3391_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_i_i_reg_3391_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_i_i_reg_3391_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_10_i_i_reg_3407;
reg  signed [15:0] p_Result_2_10_i_i_reg_3407_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_10_i_i_reg_3407_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_10_i_i_reg_3407_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_11_i_i_reg_3423;
reg  signed [15:0] p_Result_2_11_i_i_reg_3423_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_11_i_i_reg_3423_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_11_i_i_reg_3423_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_12_i_i_reg_3439;
reg  signed [15:0] p_Result_2_12_i_i_reg_3439_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_12_i_i_reg_3439_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_12_i_i_reg_3439_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_13_i_i_reg_3455;
reg  signed [15:0] p_Result_2_13_i_i_reg_3455_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_13_i_i_reg_3455_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_13_i_i_reg_3455_pp0_iter4_reg;
reg  signed [15:0] p_Result_2_14_i_i_reg_3471;
reg  signed [15:0] p_Result_2_14_i_i_reg_3471_pp0_iter2_reg;
reg  signed [15:0] p_Result_2_14_i_i_reg_3471_pp0_iter3_reg;
reg  signed [15:0] p_Result_2_14_i_i_reg_3471_pp0_iter4_reg;
reg   [23:0] p_Result_3_i_i_reg_3487;
reg   [22:0] tmp_reg_3492;
reg   [23:0] p_Result_3_1_i_i_reg_3497;
reg   [22:0] tmp_1_reg_3502;
reg   [23:0] p_Result_3_2_i_i_reg_3507;
reg   [22:0] tmp_2_reg_3512;
reg   [23:0] p_Result_3_3_i_i_reg_3517;
reg   [22:0] tmp_3_reg_3522;
reg   [23:0] p_Result_3_4_i_i_reg_3527;
reg   [22:0] tmp_4_reg_3532;
reg   [23:0] p_Result_3_5_i_i_reg_3537;
reg   [22:0] tmp_5_reg_3542;
reg   [23:0] p_Result_3_6_i_i_reg_3547;
reg   [22:0] tmp_6_reg_3552;
reg   [23:0] p_Result_3_7_i_i_reg_3557;
reg   [22:0] tmp_7_reg_3562;
reg   [23:0] p_Result_3_8_i_i_reg_3567;
reg   [22:0] tmp_8_reg_3572;
reg   [23:0] p_Result_3_9_i_i_reg_3577;
reg   [22:0] tmp_9_reg_3582;
reg   [23:0] p_Result_3_i_i_182_reg_3587;
reg   [22:0] tmp_s_reg_3592;
reg   [23:0] p_Result_3_10_i_i_reg_3597;
reg   [22:0] tmp_10_reg_3602;
reg   [23:0] p_Result_3_11_i_i_reg_3607;
reg   [22:0] tmp_11_reg_3612;
reg   [23:0] p_Result_3_12_i_i_reg_3617;
reg   [22:0] tmp_12_reg_3622;
reg   [23:0] p_Result_3_13_i_i_reg_3627;
reg   [22:0] tmp_13_reg_3632;
reg   [23:0] p_Result_3_14_i_i_reg_3637;
reg   [22:0] tmp_14_reg_3642;
wire   [23:0] select_ln263_fu_1444_p3;
reg   [23:0] select_ln263_reg_3647;
reg   [23:0] select_ln263_reg_3647_pp0_iter6_reg;
wire   [23:0] select_ln263_1_fu_1487_p3;
reg   [23:0] select_ln263_1_reg_3653;
reg   [23:0] select_ln263_1_reg_3653_pp0_iter6_reg;
wire   [23:0] select_ln263_2_fu_1530_p3;
reg   [23:0] select_ln263_2_reg_3659;
reg   [23:0] select_ln263_2_reg_3659_pp0_iter6_reg;
wire   [23:0] select_ln263_3_fu_1573_p3;
reg   [23:0] select_ln263_3_reg_3665;
reg   [23:0] select_ln263_3_reg_3665_pp0_iter6_reg;
wire   [23:0] select_ln263_4_fu_1616_p3;
reg   [23:0] select_ln263_4_reg_3671;
reg   [23:0] select_ln263_4_reg_3671_pp0_iter6_reg;
wire   [23:0] select_ln263_5_fu_1659_p3;
reg   [23:0] select_ln263_5_reg_3677;
reg   [23:0] select_ln263_5_reg_3677_pp0_iter6_reg;
wire   [23:0] select_ln263_6_fu_1702_p3;
reg   [23:0] select_ln263_6_reg_3683;
reg   [23:0] select_ln263_6_reg_3683_pp0_iter6_reg;
wire   [23:0] select_ln263_7_fu_1745_p3;
reg   [23:0] select_ln263_7_reg_3689;
reg   [23:0] select_ln263_7_reg_3689_pp0_iter6_reg;
wire   [23:0] select_ln263_8_fu_1788_p3;
reg   [23:0] select_ln263_8_reg_3695;
reg   [23:0] select_ln263_8_reg_3695_pp0_iter6_reg;
wire   [23:0] select_ln263_9_fu_1831_p3;
reg   [23:0] select_ln263_9_reg_3701;
reg   [23:0] select_ln263_9_reg_3701_pp0_iter6_reg;
wire   [23:0] select_ln263_10_fu_1874_p3;
reg   [23:0] select_ln263_10_reg_3707;
reg   [23:0] select_ln263_10_reg_3707_pp0_iter6_reg;
wire   [23:0] select_ln263_11_fu_1917_p3;
reg   [23:0] select_ln263_11_reg_3713;
reg   [23:0] select_ln263_11_reg_3713_pp0_iter6_reg;
wire   [23:0] select_ln263_12_fu_1960_p3;
reg   [23:0] select_ln263_12_reg_3719;
reg   [23:0] select_ln263_12_reg_3719_pp0_iter6_reg;
wire   [23:0] select_ln263_13_fu_2003_p3;
reg   [23:0] select_ln263_13_reg_3725;
reg   [23:0] select_ln263_13_reg_3725_pp0_iter6_reg;
wire   [23:0] select_ln263_14_fu_2046_p3;
reg   [23:0] select_ln263_14_reg_3731;
reg   [23:0] select_ln263_14_reg_3731_pp0_iter6_reg;
wire   [23:0] select_ln263_15_fu_2089_p3;
reg   [23:0] select_ln263_15_reg_3737;
reg   [23:0] select_ln263_15_reg_3737_pp0_iter6_reg;
wire   [0:0] icmp_ln886_fu_2111_p2;
reg   [0:0] icmp_ln886_reg_3743;
wire   [0:0] icmp_ln878_fu_2117_p2;
reg   [0:0] icmp_ln878_reg_3749;
wire   [0:0] icmp_ln886_1_fu_2138_p2;
reg   [0:0] icmp_ln886_1_reg_3754;
wire   [0:0] icmp_ln878_1_fu_2144_p2;
reg   [0:0] icmp_ln878_1_reg_3760;
wire   [0:0] icmp_ln886_2_fu_2165_p2;
reg   [0:0] icmp_ln886_2_reg_3765;
wire   [0:0] icmp_ln878_2_fu_2171_p2;
reg   [0:0] icmp_ln878_2_reg_3771;
wire   [0:0] icmp_ln886_3_fu_2192_p2;
reg   [0:0] icmp_ln886_3_reg_3776;
wire   [0:0] icmp_ln878_3_fu_2198_p2;
reg   [0:0] icmp_ln878_3_reg_3782;
wire   [0:0] icmp_ln886_4_fu_2219_p2;
reg   [0:0] icmp_ln886_4_reg_3787;
wire   [0:0] icmp_ln878_4_fu_2225_p2;
reg   [0:0] icmp_ln878_4_reg_3793;
wire   [0:0] icmp_ln886_5_fu_2246_p2;
reg   [0:0] icmp_ln886_5_reg_3798;
wire   [0:0] icmp_ln878_5_fu_2252_p2;
reg   [0:0] icmp_ln878_5_reg_3804;
wire   [0:0] icmp_ln886_6_fu_2273_p2;
reg   [0:0] icmp_ln886_6_reg_3809;
wire   [0:0] icmp_ln878_6_fu_2279_p2;
reg   [0:0] icmp_ln878_6_reg_3815;
wire   [0:0] icmp_ln886_7_fu_2300_p2;
reg   [0:0] icmp_ln886_7_reg_3820;
wire   [0:0] icmp_ln878_7_fu_2306_p2;
reg   [0:0] icmp_ln878_7_reg_3826;
wire   [0:0] icmp_ln886_8_fu_2327_p2;
reg   [0:0] icmp_ln886_8_reg_3831;
wire   [0:0] icmp_ln878_8_fu_2333_p2;
reg   [0:0] icmp_ln878_8_reg_3837;
wire   [0:0] icmp_ln886_9_fu_2354_p2;
reg   [0:0] icmp_ln886_9_reg_3842;
wire   [0:0] icmp_ln878_9_fu_2360_p2;
reg   [0:0] icmp_ln878_9_reg_3848;
wire   [0:0] icmp_ln886_10_fu_2381_p2;
reg   [0:0] icmp_ln886_10_reg_3853;
wire   [0:0] icmp_ln878_10_fu_2387_p2;
reg   [0:0] icmp_ln878_10_reg_3859;
wire   [0:0] icmp_ln886_11_fu_2408_p2;
reg   [0:0] icmp_ln886_11_reg_3864;
wire   [0:0] icmp_ln878_11_fu_2414_p2;
reg   [0:0] icmp_ln878_11_reg_3870;
wire   [0:0] icmp_ln886_12_fu_2435_p2;
reg   [0:0] icmp_ln886_12_reg_3875;
wire   [0:0] icmp_ln878_12_fu_2441_p2;
reg   [0:0] icmp_ln878_12_reg_3881;
wire   [0:0] icmp_ln886_13_fu_2462_p2;
reg   [0:0] icmp_ln886_13_reg_3886;
wire   [0:0] icmp_ln878_13_fu_2468_p2;
reg   [0:0] icmp_ln878_13_reg_3892;
wire   [0:0] icmp_ln886_14_fu_2489_p2;
reg   [0:0] icmp_ln886_14_reg_3897;
wire   [0:0] icmp_ln878_14_fu_2495_p2;
reg   [0:0] icmp_ln878_14_reg_3903;
wire   [0:0] icmp_ln886_15_fu_2516_p2;
reg   [0:0] icmp_ln886_15_reg_3908;
wire   [0:0] icmp_ln878_15_fu_2522_p2;
reg   [0:0] icmp_ln878_15_reg_3914;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state7;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_block_state1;
wire   [127:0] p_Result_i_i_fu_1083_p17;
reg    ap_block_pp0_stage0_01001;
wire   [127:0] p_Result_4_i_i_fu_2976_p17;
wire   [31:0] grp_fu_322_p0;
wire   [11:0] grp_fu_322_p1;
wire  signed [23:0] tmp_data_V_0_fu_339_p1;
wire  signed [15:0] trunc_ln674_fu_493_p1;
wire  signed [23:0] tmp_data_V_1_fu_343_p4;
wire  signed [15:0] p_Result_1_1_i_i_fu_509_p4;
wire  signed [23:0] tmp_data_V_2_fu_353_p4;
wire  signed [15:0] p_Result_1_2_i_i_fu_537_p4;
wire  signed [23:0] tmp_data_V_3_fu_363_p4;
wire  signed [15:0] p_Result_1_3_i_i_fu_565_p4;
wire  signed [23:0] tmp_data_V_4_fu_373_p4;
wire  signed [15:0] p_Result_1_4_i_i_fu_593_p4;
wire  signed [23:0] tmp_data_V_5_fu_383_p4;
wire  signed [15:0] p_Result_1_5_i_i_fu_621_p4;
wire  signed [23:0] tmp_data_V_6_fu_393_p4;
wire  signed [15:0] p_Result_1_6_i_i_fu_649_p4;
wire  signed [23:0] tmp_data_V_7_fu_403_p4;
wire  signed [15:0] p_Result_1_7_i_i_fu_677_p4;
wire  signed [23:0] tmp_data_V_8_fu_413_p4;
wire  signed [15:0] p_Result_1_8_i_i_fu_705_p4;
wire  signed [23:0] tmp_data_V_9_fu_423_p4;
wire  signed [15:0] p_Result_1_9_i_i_fu_733_p4;
wire  signed [23:0] tmp_data_V_10_fu_433_p4;
wire  signed [15:0] p_Result_1_i_i_fu_761_p4;
wire  signed [23:0] tmp_data_V_11_fu_443_p4;
wire  signed [15:0] p_Result_1_10_i_i_fu_789_p4;
wire  signed [23:0] tmp_data_V_12_fu_453_p4;
wire  signed [15:0] p_Result_1_11_i_i_fu_817_p4;
wire  signed [23:0] tmp_data_V_13_fu_463_p4;
wire  signed [15:0] p_Result_1_12_i_i_fu_845_p4;
wire  signed [23:0] tmp_data_V_14_fu_473_p4;
wire  signed [15:0] p_Result_1_13_i_i_fu_873_p4;
wire  signed [23:0] tmp_data_V_15_fu_483_p4;
wire  signed [15:0] p_Result_1_14_i_i_fu_901_p4;
wire   [7:0] trunc_ln69_14_fu_1073_p4;
wire   [7:0] trunc_ln69_13_fu_1063_p4;
wire   [7:0] trunc_ln69_12_fu_1053_p4;
wire   [7:0] trunc_ln69_11_fu_1043_p4;
wire   [7:0] trunc_ln69_10_fu_1033_p4;
wire   [7:0] trunc_ln69_s_fu_1023_p4;
wire   [7:0] trunc_ln69_9_fu_1013_p4;
wire   [7:0] trunc_ln69_8_fu_1003_p4;
wire   [7:0] trunc_ln69_7_fu_993_p4;
wire   [7:0] trunc_ln69_6_fu_983_p4;
wire   [7:0] trunc_ln69_5_fu_973_p4;
wire   [7:0] trunc_ln69_4_fu_963_p4;
wire   [7:0] trunc_ln69_3_fu_953_p4;
wire   [7:0] trunc_ln69_2_fu_943_p4;
wire   [7:0] trunc_ln69_1_fu_933_p4;
wire   [7:0] trunc_ln69_fu_929_p1;
wire  signed [39:0] grp_fu_3013_p3;
wire  signed [39:0] grp_fu_3023_p3;
wire  signed [39:0] grp_fu_3033_p3;
wire  signed [39:0] grp_fu_3043_p3;
wire  signed [39:0] grp_fu_3053_p3;
wire  signed [39:0] grp_fu_3063_p3;
wire  signed [39:0] grp_fu_3073_p3;
wire  signed [39:0] grp_fu_3083_p3;
wire  signed [39:0] grp_fu_3093_p3;
wire  signed [39:0] grp_fu_3103_p3;
wire  signed [39:0] grp_fu_3113_p3;
wire  signed [39:0] grp_fu_3123_p3;
wire  signed [39:0] grp_fu_3133_p3;
wire  signed [39:0] grp_fu_3143_p3;
wire  signed [39:0] grp_fu_3153_p3;
wire  signed [39:0] grp_fu_3163_p3;
wire  signed [23:0] sext_ln691_fu_1408_p1;
wire  signed [22:0] sext_ln691_16_fu_1411_p1;
wire   [23:0] add_ln691_1_fu_1414_p2;
wire   [0:0] tmp_15_fu_1424_p3;
wire   [22:0] add_ln297_fu_1419_p2;
wire   [22:0] select_ln298_fu_1432_p3;
wire   [23:0] zext_ln299_fu_1440_p1;
wire  signed [23:0] sext_ln691_1_fu_1451_p1;
wire  signed [22:0] sext_ln691_17_fu_1454_p1;
wire   [23:0] add_ln691_3_fu_1457_p2;
wire   [0:0] tmp_17_fu_1467_p3;
wire   [22:0] add_ln297_1_fu_1462_p2;
wire   [22:0] select_ln298_1_fu_1475_p3;
wire   [23:0] zext_ln299_1_fu_1483_p1;
wire  signed [23:0] sext_ln691_2_fu_1494_p1;
wire  signed [22:0] sext_ln691_18_fu_1497_p1;
wire   [23:0] add_ln691_5_fu_1500_p2;
wire   [0:0] tmp_19_fu_1510_p3;
wire   [22:0] add_ln297_2_fu_1505_p2;
wire   [22:0] select_ln298_2_fu_1518_p3;
wire   [23:0] zext_ln299_2_fu_1526_p1;
wire  signed [23:0] sext_ln691_3_fu_1537_p1;
wire  signed [22:0] sext_ln691_19_fu_1540_p1;
wire   [23:0] add_ln691_7_fu_1543_p2;
wire   [0:0] tmp_21_fu_1553_p3;
wire   [22:0] add_ln297_3_fu_1548_p2;
wire   [22:0] select_ln298_3_fu_1561_p3;
wire   [23:0] zext_ln299_3_fu_1569_p1;
wire  signed [23:0] sext_ln691_4_fu_1580_p1;
wire  signed [22:0] sext_ln691_20_fu_1583_p1;
wire   [23:0] add_ln691_9_fu_1586_p2;
wire   [0:0] tmp_23_fu_1596_p3;
wire   [22:0] add_ln297_4_fu_1591_p2;
wire   [22:0] select_ln298_4_fu_1604_p3;
wire   [23:0] zext_ln299_4_fu_1612_p1;
wire  signed [23:0] sext_ln691_5_fu_1623_p1;
wire  signed [22:0] sext_ln691_21_fu_1626_p1;
wire   [23:0] add_ln691_11_fu_1629_p2;
wire   [0:0] tmp_25_fu_1639_p3;
wire   [22:0] add_ln297_5_fu_1634_p2;
wire   [22:0] select_ln298_5_fu_1647_p3;
wire   [23:0] zext_ln299_5_fu_1655_p1;
wire  signed [23:0] sext_ln691_6_fu_1666_p1;
wire  signed [22:0] sext_ln691_22_fu_1669_p1;
wire   [23:0] add_ln691_13_fu_1672_p2;
wire   [0:0] tmp_27_fu_1682_p3;
wire   [22:0] add_ln297_6_fu_1677_p2;
wire   [22:0] select_ln298_6_fu_1690_p3;
wire   [23:0] zext_ln299_6_fu_1698_p1;
wire  signed [23:0] sext_ln691_7_fu_1709_p1;
wire  signed [22:0] sext_ln691_23_fu_1712_p1;
wire   [23:0] add_ln691_15_fu_1715_p2;
wire   [0:0] tmp_29_fu_1725_p3;
wire   [22:0] add_ln297_7_fu_1720_p2;
wire   [22:0] select_ln298_7_fu_1733_p3;
wire   [23:0] zext_ln299_7_fu_1741_p1;
wire  signed [23:0] sext_ln691_8_fu_1752_p1;
wire  signed [22:0] sext_ln691_24_fu_1755_p1;
wire   [23:0] add_ln691_17_fu_1758_p2;
wire   [0:0] tmp_31_fu_1768_p3;
wire   [22:0] add_ln297_8_fu_1763_p2;
wire   [22:0] select_ln298_8_fu_1776_p3;
wire   [23:0] zext_ln299_8_fu_1784_p1;
wire  signed [23:0] sext_ln691_9_fu_1795_p1;
wire  signed [22:0] sext_ln691_25_fu_1798_p1;
wire   [23:0] add_ln691_19_fu_1801_p2;
wire   [0:0] tmp_33_fu_1811_p3;
wire   [22:0] add_ln297_9_fu_1806_p2;
wire   [22:0] select_ln298_9_fu_1819_p3;
wire   [23:0] zext_ln299_9_fu_1827_p1;
wire  signed [23:0] sext_ln691_10_fu_1838_p1;
wire  signed [22:0] sext_ln691_26_fu_1841_p1;
wire   [23:0] add_ln691_21_fu_1844_p2;
wire   [0:0] tmp_35_fu_1854_p3;
wire   [22:0] add_ln297_10_fu_1849_p2;
wire   [22:0] select_ln298_10_fu_1862_p3;
wire   [23:0] zext_ln299_10_fu_1870_p1;
wire  signed [23:0] sext_ln691_11_fu_1881_p1;
wire  signed [22:0] sext_ln691_27_fu_1884_p1;
wire   [23:0] add_ln691_23_fu_1887_p2;
wire   [0:0] tmp_37_fu_1897_p3;
wire   [22:0] add_ln297_11_fu_1892_p2;
wire   [22:0] select_ln298_11_fu_1905_p3;
wire   [23:0] zext_ln299_11_fu_1913_p1;
wire  signed [23:0] sext_ln691_12_fu_1924_p1;
wire  signed [22:0] sext_ln691_28_fu_1927_p1;
wire   [23:0] add_ln691_25_fu_1930_p2;
wire   [0:0] tmp_39_fu_1940_p3;
wire   [22:0] add_ln297_12_fu_1935_p2;
wire   [22:0] select_ln298_12_fu_1948_p3;
wire   [23:0] zext_ln299_12_fu_1956_p1;
wire  signed [23:0] sext_ln691_13_fu_1967_p1;
wire  signed [22:0] sext_ln691_29_fu_1970_p1;
wire   [23:0] add_ln691_27_fu_1973_p2;
wire   [0:0] tmp_41_fu_1983_p3;
wire   [22:0] add_ln297_13_fu_1978_p2;
wire   [22:0] select_ln298_13_fu_1991_p3;
wire   [23:0] zext_ln299_13_fu_1999_p1;
wire  signed [23:0] sext_ln691_14_fu_2010_p1;
wire  signed [22:0] sext_ln691_30_fu_2013_p1;
wire   [23:0] add_ln691_29_fu_2016_p2;
wire   [0:0] tmp_43_fu_2026_p3;
wire   [22:0] add_ln297_14_fu_2021_p2;
wire   [22:0] select_ln298_14_fu_2034_p3;
wire   [23:0] zext_ln299_14_fu_2042_p1;
wire  signed [23:0] sext_ln691_15_fu_2053_p1;
wire  signed [22:0] sext_ln691_31_fu_2056_p1;
wire   [23:0] add_ln691_31_fu_2059_p2;
wire   [0:0] tmp_45_fu_2069_p3;
wire   [22:0] add_ln297_15_fu_2064_p2;
wire   [22:0] select_ln298_15_fu_2077_p3;
wire   [23:0] zext_ln299_15_fu_2085_p1;
wire   [23:0] add_ln692_fu_2096_p2;
wire   [16:0] tmp_16_fu_2101_p4;
wire   [23:0] add_ln692_1_fu_2123_p2;
wire   [16:0] tmp_18_fu_2128_p4;
wire   [23:0] add_ln692_2_fu_2150_p2;
wire   [16:0] tmp_20_fu_2155_p4;
wire   [23:0] add_ln692_3_fu_2177_p2;
wire   [16:0] tmp_22_fu_2182_p4;
wire   [23:0] add_ln692_4_fu_2204_p2;
wire   [16:0] tmp_24_fu_2209_p4;
wire   [23:0] add_ln692_5_fu_2231_p2;
wire   [16:0] tmp_26_fu_2236_p4;
wire   [23:0] add_ln692_6_fu_2258_p2;
wire   [16:0] tmp_28_fu_2263_p4;
wire   [23:0] add_ln692_7_fu_2285_p2;
wire   [16:0] tmp_30_fu_2290_p4;
wire   [23:0] add_ln692_8_fu_2312_p2;
wire   [16:0] tmp_32_fu_2317_p4;
wire   [23:0] add_ln692_9_fu_2339_p2;
wire   [16:0] tmp_34_fu_2344_p4;
wire   [23:0] add_ln692_10_fu_2366_p2;
wire   [16:0] tmp_36_fu_2371_p4;
wire   [23:0] add_ln692_11_fu_2393_p2;
wire   [16:0] tmp_38_fu_2398_p4;
wire   [23:0] add_ln692_12_fu_2420_p2;
wire   [16:0] tmp_40_fu_2425_p4;
wire   [23:0] add_ln692_13_fu_2447_p2;
wire   [16:0] tmp_42_fu_2452_p4;
wire   [23:0] add_ln692_14_fu_2474_p2;
wire   [16:0] tmp_44_fu_2479_p4;
wire   [23:0] add_ln692_15_fu_2501_p2;
wire   [16:0] tmp_46_fu_2506_p4;
wire   [7:0] trunc_ln692_fu_2528_p1;
wire   [0:0] or_ln69_fu_2544_p2;
wire   [7:0] select_ln69_fu_2537_p3;
wire   [7:0] xor_ln69_fu_2531_p2;
wire   [7:0] trunc_ln692_1_fu_2556_p1;
wire   [0:0] or_ln69_1_fu_2572_p2;
wire   [7:0] select_ln69_2_fu_2565_p3;
wire   [7:0] xor_ln69_1_fu_2559_p2;
wire   [7:0] trunc_ln692_2_fu_2584_p1;
wire   [0:0] or_ln69_2_fu_2600_p2;
wire   [7:0] select_ln69_4_fu_2593_p3;
wire   [7:0] xor_ln69_2_fu_2587_p2;
wire   [7:0] trunc_ln692_3_fu_2612_p1;
wire   [0:0] or_ln69_3_fu_2628_p2;
wire   [7:0] select_ln69_6_fu_2621_p3;
wire   [7:0] xor_ln69_3_fu_2615_p2;
wire   [7:0] trunc_ln692_4_fu_2640_p1;
wire   [0:0] or_ln69_4_fu_2656_p2;
wire   [7:0] select_ln69_8_fu_2649_p3;
wire   [7:0] xor_ln69_4_fu_2643_p2;
wire   [7:0] trunc_ln692_5_fu_2668_p1;
wire   [0:0] or_ln69_5_fu_2684_p2;
wire   [7:0] select_ln69_10_fu_2677_p3;
wire   [7:0] xor_ln69_5_fu_2671_p2;
wire   [7:0] trunc_ln692_6_fu_2696_p1;
wire   [0:0] or_ln69_6_fu_2712_p2;
wire   [7:0] select_ln69_12_fu_2705_p3;
wire   [7:0] xor_ln69_6_fu_2699_p2;
wire   [7:0] trunc_ln692_7_fu_2724_p1;
wire   [0:0] or_ln69_7_fu_2740_p2;
wire   [7:0] select_ln69_14_fu_2733_p3;
wire   [7:0] xor_ln69_7_fu_2727_p2;
wire   [7:0] trunc_ln692_8_fu_2752_p1;
wire   [0:0] or_ln69_8_fu_2768_p2;
wire   [7:0] select_ln69_16_fu_2761_p3;
wire   [7:0] xor_ln69_8_fu_2755_p2;
wire   [7:0] trunc_ln692_9_fu_2780_p1;
wire   [0:0] or_ln69_9_fu_2796_p2;
wire   [7:0] select_ln69_18_fu_2789_p3;
wire   [7:0] xor_ln69_9_fu_2783_p2;
wire   [7:0] trunc_ln692_10_fu_2808_p1;
wire   [0:0] or_ln69_10_fu_2824_p2;
wire   [7:0] select_ln69_20_fu_2817_p3;
wire   [7:0] xor_ln69_10_fu_2811_p2;
wire   [7:0] trunc_ln692_11_fu_2836_p1;
wire   [0:0] or_ln69_11_fu_2852_p2;
wire   [7:0] select_ln69_22_fu_2845_p3;
wire   [7:0] xor_ln69_11_fu_2839_p2;
wire   [7:0] trunc_ln692_12_fu_2864_p1;
wire   [0:0] or_ln69_12_fu_2880_p2;
wire   [7:0] select_ln69_24_fu_2873_p3;
wire   [7:0] xor_ln69_12_fu_2867_p2;
wire   [7:0] trunc_ln692_13_fu_2892_p1;
wire   [0:0] or_ln69_13_fu_2908_p2;
wire   [7:0] select_ln69_26_fu_2901_p3;
wire   [7:0] xor_ln69_13_fu_2895_p2;
wire   [7:0] trunc_ln692_14_fu_2920_p1;
wire   [0:0] or_ln69_14_fu_2936_p2;
wire   [7:0] select_ln69_28_fu_2929_p3;
wire   [7:0] xor_ln69_14_fu_2923_p2;
wire   [7:0] trunc_ln692_15_fu_2948_p1;
wire   [0:0] or_ln69_15_fu_2964_p2;
wire   [7:0] select_ln69_30_fu_2957_p3;
wire   [7:0] xor_ln69_15_fu_2951_p2;
wire   [7:0] select_ln69_31_fu_2968_p3;
wire   [7:0] select_ln69_29_fu_2940_p3;
wire   [7:0] select_ln69_27_fu_2912_p3;
wire   [7:0] select_ln69_25_fu_2884_p3;
wire   [7:0] select_ln69_23_fu_2856_p3;
wire   [7:0] select_ln69_21_fu_2828_p3;
wire   [7:0] select_ln69_19_fu_2800_p3;
wire   [7:0] select_ln69_17_fu_2772_p3;
wire   [7:0] select_ln69_15_fu_2744_p3;
wire   [7:0] select_ln69_13_fu_2716_p3;
wire   [7:0] select_ln69_11_fu_2688_p3;
wire   [7:0] select_ln69_9_fu_2660_p3;
wire   [7:0] select_ln69_7_fu_2632_p3;
wire   [7:0] select_ln69_5_fu_2604_p3;
wire   [7:0] select_ln69_3_fu_2576_p3;
wire   [7:0] select_ln69_1_fu_2548_p3;
wire   [16:0] grp_fu_3013_p2;
wire   [16:0] grp_fu_3023_p2;
wire   [16:0] grp_fu_3033_p2;
wire   [16:0] grp_fu_3043_p2;
wire   [16:0] grp_fu_3053_p2;
wire   [16:0] grp_fu_3063_p2;
wire   [16:0] grp_fu_3073_p2;
wire   [16:0] grp_fu_3083_p2;
wire   [16:0] grp_fu_3093_p2;
wire   [16:0] grp_fu_3103_p2;
wire   [16:0] grp_fu_3113_p2;
wire   [16:0] grp_fu_3123_p2;
wire   [16:0] grp_fu_3133_p2;
wire   [16:0] grp_fu_3143_p2;
wire   [16:0] grp_fu_3153_p2;
wire   [16:0] grp_fu_3163_p2;
reg    grp_fu_3013_ce;
reg    grp_fu_3023_ce;
reg    grp_fu_3033_ce;
reg    grp_fu_3043_ce;
reg    grp_fu_3053_ce;
reg    grp_fu_3063_ce;
reg    grp_fu_3073_ce;
reg    grp_fu_3083_ce;
reg    grp_fu_3093_ce;
reg    grp_fu_3103_ce;
reg    grp_fu_3113_ce;
reg    grp_fu_3123_ce;
reg    grp_fu_3133_ce;
reg    grp_fu_3143_ce;
reg    grp_fu_3153_ce;
reg    grp_fu_3163_ce;
wire    ap_CS_fsm_state15;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [43:0] grp_fu_322_p00;
wire   [43:0] grp_fu_322_p10;
reg    ap_condition_2463;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
end

top_mul_32ns_12ns_44_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 44 ))
mul_32ns_12ns_44_5_1_U529(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_322_p0),
    .din1(grp_fu_322_p1),
    .ce(1'b1),
    .dout(grp_fu_322_p2)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U530(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_0_fu_339_p1),
    .din1(trunc_ln674_fu_493_p1),
    .din2(grp_fu_3013_p2),
    .ce(grp_fu_3013_ce),
    .dout(grp_fu_3013_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U531(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_1_fu_343_p4),
    .din1(p_Result_1_1_i_i_fu_509_p4),
    .din2(grp_fu_3023_p2),
    .ce(grp_fu_3023_ce),
    .dout(grp_fu_3023_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U532(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_2_fu_353_p4),
    .din1(p_Result_1_2_i_i_fu_537_p4),
    .din2(grp_fu_3033_p2),
    .ce(grp_fu_3033_ce),
    .dout(grp_fu_3033_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U533(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_3_fu_363_p4),
    .din1(p_Result_1_3_i_i_fu_565_p4),
    .din2(grp_fu_3043_p2),
    .ce(grp_fu_3043_ce),
    .dout(grp_fu_3043_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U534(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_4_fu_373_p4),
    .din1(p_Result_1_4_i_i_fu_593_p4),
    .din2(grp_fu_3053_p2),
    .ce(grp_fu_3053_ce),
    .dout(grp_fu_3053_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U535(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_5_fu_383_p4),
    .din1(p_Result_1_5_i_i_fu_621_p4),
    .din2(grp_fu_3063_p2),
    .ce(grp_fu_3063_ce),
    .dout(grp_fu_3063_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U536(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_6_fu_393_p4),
    .din1(p_Result_1_6_i_i_fu_649_p4),
    .din2(grp_fu_3073_p2),
    .ce(grp_fu_3073_ce),
    .dout(grp_fu_3073_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U537(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_7_fu_403_p4),
    .din1(p_Result_1_7_i_i_fu_677_p4),
    .din2(grp_fu_3083_p2),
    .ce(grp_fu_3083_ce),
    .dout(grp_fu_3083_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U538(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_8_fu_413_p4),
    .din1(p_Result_1_8_i_i_fu_705_p4),
    .din2(grp_fu_3093_p2),
    .ce(grp_fu_3093_ce),
    .dout(grp_fu_3093_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U539(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_9_fu_423_p4),
    .din1(p_Result_1_9_i_i_fu_733_p4),
    .din2(grp_fu_3103_p2),
    .ce(grp_fu_3103_ce),
    .dout(grp_fu_3103_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U540(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_10_fu_433_p4),
    .din1(p_Result_1_i_i_fu_761_p4),
    .din2(grp_fu_3113_p2),
    .ce(grp_fu_3113_ce),
    .dout(grp_fu_3113_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U541(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_11_fu_443_p4),
    .din1(p_Result_1_10_i_i_fu_789_p4),
    .din2(grp_fu_3123_p2),
    .ce(grp_fu_3123_ce),
    .dout(grp_fu_3123_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U542(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_12_fu_453_p4),
    .din1(p_Result_1_11_i_i_fu_817_p4),
    .din2(grp_fu_3133_p2),
    .ce(grp_fu_3133_ce),
    .dout(grp_fu_3133_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U543(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_13_fu_463_p4),
    .din1(p_Result_1_12_i_i_fu_845_p4),
    .din2(grp_fu_3143_p2),
    .ce(grp_fu_3143_ce),
    .dout(grp_fu_3143_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U544(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_14_fu_473_p4),
    .din1(p_Result_1_13_i_i_fu_873_p4),
    .din2(grp_fu_3153_p2),
    .ce(grp_fu_3153_ce),
    .dout(grp_fu_3153_p3)
);

top_mac_muladd_24s_16s_17ns_40_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 40 ))
mac_muladd_24s_16s_17ns_40_4_1_U545(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_data_V_15_fu_483_p4),
    .din1(p_Result_1_14_i_i_fu_901_p4),
    .din2(grp_fu_3163_p2),
    .ce(grp_fu_3163_ce),
    .dout(grp_fu_3163_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state15)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state7))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state7)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state7);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end else if ((1'b1 == ap_CS_fsm_state6)) begin
            ap_enable_reg_pp0_iter7 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln272_fu_334_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        indvar_flatten_reg_295 <= add_ln272_fu_328_p2;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        indvar_flatten_reg_295 <= 44'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        bound_reg_3217 <= grp_fu_322_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((skip_reg_3173 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln878_10_reg_3859 <= icmp_ln878_10_fu_2387_p2;
        icmp_ln878_11_reg_3870 <= icmp_ln878_11_fu_2414_p2;
        icmp_ln878_12_reg_3881 <= icmp_ln878_12_fu_2441_p2;
        icmp_ln878_13_reg_3892 <= icmp_ln878_13_fu_2468_p2;
        icmp_ln878_14_reg_3903 <= icmp_ln878_14_fu_2495_p2;
        icmp_ln878_15_reg_3914 <= icmp_ln878_15_fu_2522_p2;
        icmp_ln878_1_reg_3760 <= icmp_ln878_1_fu_2144_p2;
        icmp_ln878_2_reg_3771 <= icmp_ln878_2_fu_2171_p2;
        icmp_ln878_3_reg_3782 <= icmp_ln878_3_fu_2198_p2;
        icmp_ln878_4_reg_3793 <= icmp_ln878_4_fu_2225_p2;
        icmp_ln878_5_reg_3804 <= icmp_ln878_5_fu_2252_p2;
        icmp_ln878_6_reg_3815 <= icmp_ln878_6_fu_2279_p2;
        icmp_ln878_7_reg_3826 <= icmp_ln878_7_fu_2306_p2;
        icmp_ln878_8_reg_3837 <= icmp_ln878_8_fu_2333_p2;
        icmp_ln878_9_reg_3848 <= icmp_ln878_9_fu_2360_p2;
        icmp_ln878_reg_3749 <= icmp_ln878_fu_2117_p2;
        icmp_ln886_10_reg_3853 <= icmp_ln886_10_fu_2381_p2;
        icmp_ln886_11_reg_3864 <= icmp_ln886_11_fu_2408_p2;
        icmp_ln886_12_reg_3875 <= icmp_ln886_12_fu_2435_p2;
        icmp_ln886_13_reg_3886 <= icmp_ln886_13_fu_2462_p2;
        icmp_ln886_14_reg_3897 <= icmp_ln886_14_fu_2489_p2;
        icmp_ln886_15_reg_3908 <= icmp_ln886_15_fu_2516_p2;
        icmp_ln886_1_reg_3754 <= icmp_ln886_1_fu_2138_p2;
        icmp_ln886_2_reg_3765 <= icmp_ln886_2_fu_2165_p2;
        icmp_ln886_3_reg_3776 <= icmp_ln886_3_fu_2192_p2;
        icmp_ln886_4_reg_3787 <= icmp_ln886_4_fu_2219_p2;
        icmp_ln886_5_reg_3798 <= icmp_ln886_5_fu_2246_p2;
        icmp_ln886_6_reg_3809 <= icmp_ln886_6_fu_2273_p2;
        icmp_ln886_7_reg_3820 <= icmp_ln886_7_fu_2300_p2;
        icmp_ln886_8_reg_3831 <= icmp_ln886_8_fu_2327_p2;
        icmp_ln886_9_reg_3842 <= icmp_ln886_9_fu_2354_p2;
        icmp_ln886_reg_3743 <= icmp_ln886_fu_2111_p2;
        p_Result_3_10_i_i_reg_3597 <= {{grp_fu_3123_p3[39:16]}};
        p_Result_3_11_i_i_reg_3607 <= {{grp_fu_3133_p3[39:16]}};
        p_Result_3_12_i_i_reg_3617 <= {{grp_fu_3143_p3[39:16]}};
        p_Result_3_13_i_i_reg_3627 <= {{grp_fu_3153_p3[39:16]}};
        p_Result_3_14_i_i_reg_3637 <= {{grp_fu_3163_p3[39:16]}};
        p_Result_3_1_i_i_reg_3497 <= {{grp_fu_3023_p3[39:16]}};
        p_Result_3_2_i_i_reg_3507 <= {{grp_fu_3033_p3[39:16]}};
        p_Result_3_3_i_i_reg_3517 <= {{grp_fu_3043_p3[39:16]}};
        p_Result_3_4_i_i_reg_3527 <= {{grp_fu_3053_p3[39:16]}};
        p_Result_3_5_i_i_reg_3537 <= {{grp_fu_3063_p3[39:16]}};
        p_Result_3_6_i_i_reg_3547 <= {{grp_fu_3073_p3[39:16]}};
        p_Result_3_7_i_i_reg_3557 <= {{grp_fu_3083_p3[39:16]}};
        p_Result_3_8_i_i_reg_3567 <= {{grp_fu_3093_p3[39:16]}};
        p_Result_3_9_i_i_reg_3577 <= {{grp_fu_3103_p3[39:16]}};
        p_Result_3_i_i_182_reg_3587 <= {{grp_fu_3113_p3[39:16]}};
        p_Result_3_i_i_reg_3487 <= {{grp_fu_3013_p3[39:16]}};
        select_ln263_10_reg_3707 <= select_ln263_10_fu_1874_p3;
        select_ln263_11_reg_3713 <= select_ln263_11_fu_1917_p3;
        select_ln263_12_reg_3719 <= select_ln263_12_fu_1960_p3;
        select_ln263_13_reg_3725 <= select_ln263_13_fu_2003_p3;
        select_ln263_14_reg_3731 <= select_ln263_14_fu_2046_p3;
        select_ln263_15_reg_3737 <= select_ln263_15_fu_2089_p3;
        select_ln263_1_reg_3653 <= select_ln263_1_fu_1487_p3;
        select_ln263_2_reg_3659 <= select_ln263_2_fu_1530_p3;
        select_ln263_3_reg_3665 <= select_ln263_3_fu_1573_p3;
        select_ln263_4_reg_3671 <= select_ln263_4_fu_1616_p3;
        select_ln263_5_reg_3677 <= select_ln263_5_fu_1659_p3;
        select_ln263_6_reg_3683 <= select_ln263_6_fu_1702_p3;
        select_ln263_7_reg_3689 <= select_ln263_7_fu_1745_p3;
        select_ln263_8_reg_3695 <= select_ln263_8_fu_1788_p3;
        select_ln263_9_reg_3701 <= select_ln263_9_fu_1831_p3;
        select_ln263_reg_3647 <= select_ln263_fu_1444_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((skip_reg_3173 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_Result_2_10_i_i_reg_3407 <= {{s_bias_dout[191:176]}};
        p_Result_2_11_i_i_reg_3423 <= {{s_bias_dout[207:192]}};
        p_Result_2_12_i_i_reg_3439 <= {{s_bias_dout[223:208]}};
        p_Result_2_13_i_i_reg_3455 <= {{s_bias_dout[239:224]}};
        p_Result_2_14_i_i_reg_3471 <= {{s_bias_dout[255:240]}};
        p_Result_2_1_i_i_reg_3247 <= {{s_bias_dout[31:16]}};
        p_Result_2_2_i_i_reg_3263 <= {{s_bias_dout[47:32]}};
        p_Result_2_3_i_i_reg_3279 <= {{s_bias_dout[63:48]}};
        p_Result_2_4_i_i_reg_3295 <= {{s_bias_dout[79:64]}};
        p_Result_2_5_i_i_reg_3311 <= {{s_bias_dout[95:80]}};
        p_Result_2_6_i_i_reg_3327 <= {{s_bias_dout[111:96]}};
        p_Result_2_7_i_i_reg_3343 <= {{s_bias_dout[127:112]}};
        p_Result_2_8_i_i_reg_3359 <= {{s_bias_dout[143:128]}};
        p_Result_2_9_i_i_reg_3375 <= {{s_bias_dout[159:144]}};
        p_Result_2_i_i_reg_3391 <= {{s_bias_dout[175:160]}};
        trunc_ln674_1_reg_3231 <= trunc_ln674_1_fu_497_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        p_Result_2_10_i_i_reg_3407_pp0_iter2_reg <= p_Result_2_10_i_i_reg_3407;
        p_Result_2_10_i_i_reg_3407_pp0_iter3_reg <= p_Result_2_10_i_i_reg_3407_pp0_iter2_reg;
        p_Result_2_10_i_i_reg_3407_pp0_iter4_reg <= p_Result_2_10_i_i_reg_3407_pp0_iter3_reg;
        p_Result_2_11_i_i_reg_3423_pp0_iter2_reg <= p_Result_2_11_i_i_reg_3423;
        p_Result_2_11_i_i_reg_3423_pp0_iter3_reg <= p_Result_2_11_i_i_reg_3423_pp0_iter2_reg;
        p_Result_2_11_i_i_reg_3423_pp0_iter4_reg <= p_Result_2_11_i_i_reg_3423_pp0_iter3_reg;
        p_Result_2_12_i_i_reg_3439_pp0_iter2_reg <= p_Result_2_12_i_i_reg_3439;
        p_Result_2_12_i_i_reg_3439_pp0_iter3_reg <= p_Result_2_12_i_i_reg_3439_pp0_iter2_reg;
        p_Result_2_12_i_i_reg_3439_pp0_iter4_reg <= p_Result_2_12_i_i_reg_3439_pp0_iter3_reg;
        p_Result_2_13_i_i_reg_3455_pp0_iter2_reg <= p_Result_2_13_i_i_reg_3455;
        p_Result_2_13_i_i_reg_3455_pp0_iter3_reg <= p_Result_2_13_i_i_reg_3455_pp0_iter2_reg;
        p_Result_2_13_i_i_reg_3455_pp0_iter4_reg <= p_Result_2_13_i_i_reg_3455_pp0_iter3_reg;
        p_Result_2_14_i_i_reg_3471_pp0_iter2_reg <= p_Result_2_14_i_i_reg_3471;
        p_Result_2_14_i_i_reg_3471_pp0_iter3_reg <= p_Result_2_14_i_i_reg_3471_pp0_iter2_reg;
        p_Result_2_14_i_i_reg_3471_pp0_iter4_reg <= p_Result_2_14_i_i_reg_3471_pp0_iter3_reg;
        p_Result_2_1_i_i_reg_3247_pp0_iter2_reg <= p_Result_2_1_i_i_reg_3247;
        p_Result_2_1_i_i_reg_3247_pp0_iter3_reg <= p_Result_2_1_i_i_reg_3247_pp0_iter2_reg;
        p_Result_2_1_i_i_reg_3247_pp0_iter4_reg <= p_Result_2_1_i_i_reg_3247_pp0_iter3_reg;
        p_Result_2_2_i_i_reg_3263_pp0_iter2_reg <= p_Result_2_2_i_i_reg_3263;
        p_Result_2_2_i_i_reg_3263_pp0_iter3_reg <= p_Result_2_2_i_i_reg_3263_pp0_iter2_reg;
        p_Result_2_2_i_i_reg_3263_pp0_iter4_reg <= p_Result_2_2_i_i_reg_3263_pp0_iter3_reg;
        p_Result_2_3_i_i_reg_3279_pp0_iter2_reg <= p_Result_2_3_i_i_reg_3279;
        p_Result_2_3_i_i_reg_3279_pp0_iter3_reg <= p_Result_2_3_i_i_reg_3279_pp0_iter2_reg;
        p_Result_2_3_i_i_reg_3279_pp0_iter4_reg <= p_Result_2_3_i_i_reg_3279_pp0_iter3_reg;
        p_Result_2_4_i_i_reg_3295_pp0_iter2_reg <= p_Result_2_4_i_i_reg_3295;
        p_Result_2_4_i_i_reg_3295_pp0_iter3_reg <= p_Result_2_4_i_i_reg_3295_pp0_iter2_reg;
        p_Result_2_4_i_i_reg_3295_pp0_iter4_reg <= p_Result_2_4_i_i_reg_3295_pp0_iter3_reg;
        p_Result_2_5_i_i_reg_3311_pp0_iter2_reg <= p_Result_2_5_i_i_reg_3311;
        p_Result_2_5_i_i_reg_3311_pp0_iter3_reg <= p_Result_2_5_i_i_reg_3311_pp0_iter2_reg;
        p_Result_2_5_i_i_reg_3311_pp0_iter4_reg <= p_Result_2_5_i_i_reg_3311_pp0_iter3_reg;
        p_Result_2_6_i_i_reg_3327_pp0_iter2_reg <= p_Result_2_6_i_i_reg_3327;
        p_Result_2_6_i_i_reg_3327_pp0_iter3_reg <= p_Result_2_6_i_i_reg_3327_pp0_iter2_reg;
        p_Result_2_6_i_i_reg_3327_pp0_iter4_reg <= p_Result_2_6_i_i_reg_3327_pp0_iter3_reg;
        p_Result_2_7_i_i_reg_3343_pp0_iter2_reg <= p_Result_2_7_i_i_reg_3343;
        p_Result_2_7_i_i_reg_3343_pp0_iter3_reg <= p_Result_2_7_i_i_reg_3343_pp0_iter2_reg;
        p_Result_2_7_i_i_reg_3343_pp0_iter4_reg <= p_Result_2_7_i_i_reg_3343_pp0_iter3_reg;
        p_Result_2_8_i_i_reg_3359_pp0_iter2_reg <= p_Result_2_8_i_i_reg_3359;
        p_Result_2_8_i_i_reg_3359_pp0_iter3_reg <= p_Result_2_8_i_i_reg_3359_pp0_iter2_reg;
        p_Result_2_8_i_i_reg_3359_pp0_iter4_reg <= p_Result_2_8_i_i_reg_3359_pp0_iter3_reg;
        p_Result_2_9_i_i_reg_3375_pp0_iter2_reg <= p_Result_2_9_i_i_reg_3375;
        p_Result_2_9_i_i_reg_3375_pp0_iter3_reg <= p_Result_2_9_i_i_reg_3375_pp0_iter2_reg;
        p_Result_2_9_i_i_reg_3375_pp0_iter4_reg <= p_Result_2_9_i_i_reg_3375_pp0_iter3_reg;
        p_Result_2_i_i_reg_3391_pp0_iter2_reg <= p_Result_2_i_i_reg_3391;
        p_Result_2_i_i_reg_3391_pp0_iter3_reg <= p_Result_2_i_i_reg_3391_pp0_iter2_reg;
        p_Result_2_i_i_reg_3391_pp0_iter4_reg <= p_Result_2_i_i_reg_3391_pp0_iter3_reg;
        select_ln263_10_reg_3707_pp0_iter6_reg <= select_ln263_10_reg_3707;
        select_ln263_11_reg_3713_pp0_iter6_reg <= select_ln263_11_reg_3713;
        select_ln263_12_reg_3719_pp0_iter6_reg <= select_ln263_12_reg_3719;
        select_ln263_13_reg_3725_pp0_iter6_reg <= select_ln263_13_reg_3725;
        select_ln263_14_reg_3731_pp0_iter6_reg <= select_ln263_14_reg_3731;
        select_ln263_15_reg_3737_pp0_iter6_reg <= select_ln263_15_reg_3737;
        select_ln263_1_reg_3653_pp0_iter6_reg <= select_ln263_1_reg_3653;
        select_ln263_2_reg_3659_pp0_iter6_reg <= select_ln263_2_reg_3659;
        select_ln263_3_reg_3665_pp0_iter6_reg <= select_ln263_3_reg_3665;
        select_ln263_4_reg_3671_pp0_iter6_reg <= select_ln263_4_reg_3671;
        select_ln263_5_reg_3677_pp0_iter6_reg <= select_ln263_5_reg_3677;
        select_ln263_6_reg_3683_pp0_iter6_reg <= select_ln263_6_reg_3683;
        select_ln263_7_reg_3689_pp0_iter6_reg <= select_ln263_7_reg_3689;
        select_ln263_8_reg_3695_pp0_iter6_reg <= select_ln263_8_reg_3695;
        select_ln263_9_reg_3701_pp0_iter6_reg <= select_ln263_9_reg_3701;
        select_ln263_reg_3647_pp0_iter6_reg <= select_ln263_reg_3647;
        trunc_ln674_1_reg_3231_pp0_iter2_reg <= trunc_ln674_1_reg_3231;
        trunc_ln674_1_reg_3231_pp0_iter3_reg <= trunc_ln674_1_reg_3231_pp0_iter2_reg;
        trunc_ln674_1_reg_3231_pp0_iter4_reg <= trunc_ln674_1_reg_3231_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        relu_reg_3177 <= relu1_dout;
        rep_reg_3197 <= mul_ln31_1_loc_dout;
        ret_cast_reg_3202 <= {{OC_V_loc_dout[15:4]}};
        skip_reg_3173 <= skip1_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((skip_reg_3173 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (relu_reg_3177 == 1'd1))) begin
        tmp_10_reg_3602 <= {{grp_fu_3123_p3[38:16]}};
        tmp_11_reg_3612 <= {{grp_fu_3133_p3[38:16]}};
        tmp_12_reg_3622 <= {{grp_fu_3143_p3[38:16]}};
        tmp_13_reg_3632 <= {{grp_fu_3153_p3[38:16]}};
        tmp_14_reg_3642 <= {{grp_fu_3163_p3[38:16]}};
        tmp_1_reg_3502 <= {{grp_fu_3023_p3[38:16]}};
        tmp_2_reg_3512 <= {{grp_fu_3033_p3[38:16]}};
        tmp_3_reg_3522 <= {{grp_fu_3043_p3[38:16]}};
        tmp_4_reg_3532 <= {{grp_fu_3053_p3[38:16]}};
        tmp_5_reg_3542 <= {{grp_fu_3063_p3[38:16]}};
        tmp_6_reg_3552 <= {{grp_fu_3073_p3[38:16]}};
        tmp_7_reg_3562 <= {{grp_fu_3083_p3[38:16]}};
        tmp_8_reg_3572 <= {{grp_fu_3093_p3[38:16]}};
        tmp_9_reg_3582 <= {{grp_fu_3103_p3[38:16]}};
        tmp_reg_3492 <= {{grp_fu_3013_p3[38:16]}};
        tmp_s_reg_3592 <= {{grp_fu_3113_p3[38:16]}};
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        OC_V_loc_blk_n = OC_V_loc_empty_n;
    end else begin
        OC_V_loc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        OC_V_loc_out_blk_n = OC_V_loc_out_full_n;
    end else begin
        OC_V_loc_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((relu1_empty_n == 1'b0) | (skip1_empty_n == 1'b0) | (mul_ln31_1_loc_empty_n == 1'b0) | (1'b0 == OC_V_loc_out_full_n) | (1'b0 == OC_V_loc_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        OC_V_loc_out_write = 1'b1;
    end else begin
        OC_V_loc_out_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((relu1_empty_n == 1'b0) | (skip1_empty_n == 1'b0) | (mul_ln31_1_loc_empty_n == 1'b0) | (1'b0 == OC_V_loc_out_full_n) | (1'b0 == OC_V_loc_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        OC_V_loc_read = 1'b1;
    end else begin
        OC_V_loc_read = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln272_fu_334_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state7 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state7 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter7 == 1'b1) & (skip_reg_3173 == 1'd0) & (1'b0 == ap_block_pp0_stage0)) | ((skip_reg_3173 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        f1_blk_n = f1_full_n;
    end else begin
        f1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0_01001)) begin
        if (((ap_enable_reg_pp0_iter7 == 1'b1) & (skip_reg_3173 == 1'd0))) begin
            f1_din = p_Result_4_i_i_fu_2976_p17;
        end else if ((1'b1 == ap_condition_2463)) begin
            f1_din = p_Result_i_i_fu_1083_p17;
        end else begin
            f1_din = 'bx;
        end
    end else begin
        f1_din = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter7 == 1'b1) & (skip_reg_3173 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((skip_reg_3173 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        f1_write = 1'b1;
    end else begin
        f1_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3013_ce = 1'b1;
    end else begin
        grp_fu_3013_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3023_ce = 1'b1;
    end else begin
        grp_fu_3023_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3033_ce = 1'b1;
    end else begin
        grp_fu_3033_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3043_ce = 1'b1;
    end else begin
        grp_fu_3043_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3053_ce = 1'b1;
    end else begin
        grp_fu_3053_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3063_ce = 1'b1;
    end else begin
        grp_fu_3063_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3073_ce = 1'b1;
    end else begin
        grp_fu_3073_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3083_ce = 1'b1;
    end else begin
        grp_fu_3083_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3093_ce = 1'b1;
    end else begin
        grp_fu_3093_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3103_ce = 1'b1;
    end else begin
        grp_fu_3103_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3113_ce = 1'b1;
    end else begin
        grp_fu_3113_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3123_ce = 1'b1;
    end else begin
        grp_fu_3123_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3133_ce = 1'b1;
    end else begin
        grp_fu_3133_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3143_ce = 1'b1;
    end else begin
        grp_fu_3143_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3153_ce = 1'b1;
    end else begin
        grp_fu_3153_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_3163_ce = 1'b1;
    end else begin
        grp_fu_3163_ce = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        mul_ln31_1_loc_blk_n = mul_ln31_1_loc_empty_n;
    end else begin
        mul_ln31_1_loc_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((relu1_empty_n == 1'b0) | (skip1_empty_n == 1'b0) | (mul_ln31_1_loc_empty_n == 1'b0) | (1'b0 == OC_V_loc_out_full_n) | (1'b0 == OC_V_loc_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        mul_ln31_1_loc_read = 1'b1;
    end else begin
        mul_ln31_1_loc_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        relu1_blk_n = relu1_empty_n;
    end else begin
        relu1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((relu1_empty_n == 1'b0) | (skip1_empty_n == 1'b0) | (mul_ln31_1_loc_empty_n == 1'b0) | (1'b0 == OC_V_loc_out_full_n) | (1'b0 == OC_V_loc_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        relu1_read = 1'b1;
    end else begin
        relu1_read = 1'b0;
    end
end

always @ (*) begin
    if (((skip_reg_3173 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_bias_blk_n = s_bias_empty_n;
    end else begin
        s_bias_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((skip_reg_3173 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_bias_read = 1'b1;
    end else begin
        s_bias_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_conv1_blk_n = s_conv1_empty_n;
    end else begin
        s_conv1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_conv1_read = 1'b1;
    end else begin
        s_conv1_read = 1'b0;
    end
end

always @ (*) begin
    if (((skip_reg_3173 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_scale_blk_n = s_scale_empty_n;
    end else begin
        s_scale_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((skip_reg_3173 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_scale_read = 1'b1;
    end else begin
        s_scale_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        skip1_blk_n = skip1_empty_n;
    end else begin
        skip1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((relu1_empty_n == 1'b0) | (skip1_empty_n == 1'b0) | (mul_ln31_1_loc_empty_n == 1'b0) | (1'b0 == OC_V_loc_out_full_n) | (1'b0 == OC_V_loc_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        skip1_read = 1'b1;
    end else begin
        skip1_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((relu1_empty_n == 1'b0) | (skip1_empty_n == 1'b0) | (mul_ln31_1_loc_empty_n == 1'b0) | (1'b0 == OC_V_loc_out_full_n) | (1'b0 == OC_V_loc_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln272_fu_334_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter6 == 1'b0)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (icmp_ln272_fu_334_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OC_V_loc_out_din = OC_V_loc_dout;

assign add_ln272_fu_328_p2 = (indvar_flatten_reg_295 + 44'd1);

assign add_ln297_10_fu_1849_p2 = ($signed(tmp_s_reg_3592) + $signed(sext_ln691_26_fu_1841_p1));

assign add_ln297_11_fu_1892_p2 = ($signed(tmp_10_reg_3602) + $signed(sext_ln691_27_fu_1884_p1));

assign add_ln297_12_fu_1935_p2 = ($signed(tmp_11_reg_3612) + $signed(sext_ln691_28_fu_1927_p1));

assign add_ln297_13_fu_1978_p2 = ($signed(tmp_12_reg_3622) + $signed(sext_ln691_29_fu_1970_p1));

assign add_ln297_14_fu_2021_p2 = ($signed(tmp_13_reg_3632) + $signed(sext_ln691_30_fu_2013_p1));

assign add_ln297_15_fu_2064_p2 = ($signed(tmp_14_reg_3642) + $signed(sext_ln691_31_fu_2056_p1));

assign add_ln297_1_fu_1462_p2 = ($signed(tmp_1_reg_3502) + $signed(sext_ln691_17_fu_1454_p1));

assign add_ln297_2_fu_1505_p2 = ($signed(tmp_2_reg_3512) + $signed(sext_ln691_18_fu_1497_p1));

assign add_ln297_3_fu_1548_p2 = ($signed(tmp_3_reg_3522) + $signed(sext_ln691_19_fu_1540_p1));

assign add_ln297_4_fu_1591_p2 = ($signed(tmp_4_reg_3532) + $signed(sext_ln691_20_fu_1583_p1));

assign add_ln297_5_fu_1634_p2 = ($signed(tmp_5_reg_3542) + $signed(sext_ln691_21_fu_1626_p1));

assign add_ln297_6_fu_1677_p2 = ($signed(tmp_6_reg_3552) + $signed(sext_ln691_22_fu_1669_p1));

assign add_ln297_7_fu_1720_p2 = ($signed(tmp_7_reg_3562) + $signed(sext_ln691_23_fu_1712_p1));

assign add_ln297_8_fu_1763_p2 = ($signed(tmp_8_reg_3572) + $signed(sext_ln691_24_fu_1755_p1));

assign add_ln297_9_fu_1806_p2 = ($signed(tmp_9_reg_3582) + $signed(sext_ln691_25_fu_1798_p1));

assign add_ln297_fu_1419_p2 = ($signed(tmp_reg_3492) + $signed(sext_ln691_16_fu_1411_p1));

assign add_ln691_11_fu_1629_p2 = ($signed(p_Result_3_5_i_i_reg_3537) + $signed(sext_ln691_5_fu_1623_p1));

assign add_ln691_13_fu_1672_p2 = ($signed(p_Result_3_6_i_i_reg_3547) + $signed(sext_ln691_6_fu_1666_p1));

assign add_ln691_15_fu_1715_p2 = ($signed(p_Result_3_7_i_i_reg_3557) + $signed(sext_ln691_7_fu_1709_p1));

assign add_ln691_17_fu_1758_p2 = ($signed(p_Result_3_8_i_i_reg_3567) + $signed(sext_ln691_8_fu_1752_p1));

assign add_ln691_19_fu_1801_p2 = ($signed(p_Result_3_9_i_i_reg_3577) + $signed(sext_ln691_9_fu_1795_p1));

assign add_ln691_1_fu_1414_p2 = ($signed(p_Result_3_i_i_reg_3487) + $signed(sext_ln691_fu_1408_p1));

assign add_ln691_21_fu_1844_p2 = ($signed(p_Result_3_i_i_182_reg_3587) + $signed(sext_ln691_10_fu_1838_p1));

assign add_ln691_23_fu_1887_p2 = ($signed(p_Result_3_10_i_i_reg_3597) + $signed(sext_ln691_11_fu_1881_p1));

assign add_ln691_25_fu_1930_p2 = ($signed(p_Result_3_11_i_i_reg_3607) + $signed(sext_ln691_12_fu_1924_p1));

assign add_ln691_27_fu_1973_p2 = ($signed(p_Result_3_12_i_i_reg_3617) + $signed(sext_ln691_13_fu_1967_p1));

assign add_ln691_29_fu_2016_p2 = ($signed(p_Result_3_13_i_i_reg_3627) + $signed(sext_ln691_14_fu_2010_p1));

assign add_ln691_31_fu_2059_p2 = ($signed(p_Result_3_14_i_i_reg_3637) + $signed(sext_ln691_15_fu_2053_p1));

assign add_ln691_3_fu_1457_p2 = ($signed(p_Result_3_1_i_i_reg_3497) + $signed(sext_ln691_1_fu_1451_p1));

assign add_ln691_5_fu_1500_p2 = ($signed(p_Result_3_2_i_i_reg_3507) + $signed(sext_ln691_2_fu_1494_p1));

assign add_ln691_7_fu_1543_p2 = ($signed(p_Result_3_3_i_i_reg_3517) + $signed(sext_ln691_3_fu_1537_p1));

assign add_ln691_9_fu_1586_p2 = ($signed(p_Result_3_4_i_i_reg_3527) + $signed(sext_ln691_4_fu_1580_p1));

assign add_ln692_10_fu_2366_p2 = ($signed(select_ln263_10_reg_3707) + $signed(24'd16777088));

assign add_ln692_11_fu_2393_p2 = ($signed(select_ln263_11_reg_3713) + $signed(24'd16777088));

assign add_ln692_12_fu_2420_p2 = ($signed(select_ln263_12_reg_3719) + $signed(24'd16777088));

assign add_ln692_13_fu_2447_p2 = ($signed(select_ln263_13_reg_3725) + $signed(24'd16777088));

assign add_ln692_14_fu_2474_p2 = ($signed(select_ln263_14_reg_3731) + $signed(24'd16777088));

assign add_ln692_15_fu_2501_p2 = ($signed(select_ln263_15_reg_3737) + $signed(24'd16777088));

assign add_ln692_1_fu_2123_p2 = ($signed(select_ln263_1_reg_3653) + $signed(24'd16777088));

assign add_ln692_2_fu_2150_p2 = ($signed(select_ln263_2_reg_3659) + $signed(24'd16777088));

assign add_ln692_3_fu_2177_p2 = ($signed(select_ln263_3_reg_3665) + $signed(24'd16777088));

assign add_ln692_4_fu_2204_p2 = ($signed(select_ln263_4_reg_3671) + $signed(24'd16777088));

assign add_ln692_5_fu_2231_p2 = ($signed(select_ln263_5_reg_3677) + $signed(24'd16777088));

assign add_ln692_6_fu_2258_p2 = ($signed(select_ln263_6_reg_3683) + $signed(24'd16777088));

assign add_ln692_7_fu_2285_p2 = ($signed(select_ln263_7_reg_3689) + $signed(24'd16777088));

assign add_ln692_8_fu_2312_p2 = ($signed(select_ln263_8_reg_3695) + $signed(24'd16777088));

assign add_ln692_9_fu_2339_p2 = ($signed(select_ln263_9_reg_3701) + $signed(24'd16777088));

assign add_ln692_fu_2096_p2 = ($signed(select_ln263_reg_3647) + $signed(24'd16777088));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter7 == 1'b1) & (skip_reg_3173 == 1'd0) & (f1_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((s_conv1_empty_n == 1'b0) | ((skip_reg_3173 == 1'd0) & (s_bias_empty_n == 1'b0)) | ((skip_reg_3173 == 1'd0) & (s_scale_empty_n == 1'b0)) | ((skip_reg_3173 == 1'd1) & (f1_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter7 == 1'b1) & (skip_reg_3173 == 1'd0) & (f1_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((s_conv1_empty_n == 1'b0) | ((skip_reg_3173 == 1'd0) & (s_bias_empty_n == 1'b0)) | ((skip_reg_3173 == 1'd0) & (s_scale_empty_n == 1'b0)) | ((skip_reg_3173 == 1'd1) & (f1_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter7 == 1'b1) & (skip_reg_3173 == 1'd0) & (f1_full_n == 1'b0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & ((s_conv1_empty_n == 1'b0) | ((skip_reg_3173 == 1'd0) & (s_bias_empty_n == 1'b0)) | ((skip_reg_3173 == 1'd0) & (s_scale_empty_n == 1'b0)) | ((skip_reg_3173 == 1'd1) & (f1_full_n == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((relu1_empty_n == 1'b0) | (skip1_empty_n == 1'b0) | (mul_ln31_1_loc_empty_n == 1'b0) | (1'b0 == OC_V_loc_out_full_n) | (1'b0 == OC_V_loc_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_block_state10_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state14_pp0_stage0_iter7 = ((skip_reg_3173 == 1'd0) & (f1_full_n == 1'b0));
end

assign ap_block_state7_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter1 = ((s_conv1_empty_n == 1'b0) | ((skip_reg_3173 == 1'd0) & (s_bias_empty_n == 1'b0)) | ((skip_reg_3173 == 1'd0) & (s_scale_empty_n == 1'b0)) | ((skip_reg_3173 == 1'd1) & (f1_full_n == 1'b0)));
end

assign ap_block_state9_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_2463 = ((skip_reg_3173 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign grp_fu_3013_p2 = 40'd32768;

assign grp_fu_3023_p2 = 40'd32768;

assign grp_fu_3033_p2 = 40'd32768;

assign grp_fu_3043_p2 = 40'd32768;

assign grp_fu_3053_p2 = 40'd32768;

assign grp_fu_3063_p2 = 40'd32768;

assign grp_fu_3073_p2 = 40'd32768;

assign grp_fu_3083_p2 = 40'd32768;

assign grp_fu_3093_p2 = 40'd32768;

assign grp_fu_3103_p2 = 40'd32768;

assign grp_fu_3113_p2 = 40'd32768;

assign grp_fu_3123_p2 = 40'd32768;

assign grp_fu_3133_p2 = 40'd32768;

assign grp_fu_3143_p2 = 40'd32768;

assign grp_fu_3153_p2 = 40'd32768;

assign grp_fu_3163_p2 = 40'd32768;

assign grp_fu_322_p0 = grp_fu_322_p00;

assign grp_fu_322_p00 = rep_reg_3197;

assign grp_fu_322_p1 = grp_fu_322_p10;

assign grp_fu_322_p10 = ret_cast_reg_3202;

assign icmp_ln272_fu_334_p2 = ((indvar_flatten_reg_295 == bound_reg_3217) ? 1'b1 : 1'b0);

assign icmp_ln878_10_fu_2387_p2 = (($signed(add_ln692_10_fu_2366_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_11_fu_2414_p2 = (($signed(add_ln692_11_fu_2393_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_12_fu_2441_p2 = (($signed(add_ln692_12_fu_2420_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_13_fu_2468_p2 = (($signed(add_ln692_13_fu_2447_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_14_fu_2495_p2 = (($signed(add_ln692_14_fu_2474_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_15_fu_2522_p2 = (($signed(add_ln692_15_fu_2501_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_1_fu_2144_p2 = (($signed(add_ln692_1_fu_2123_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_2_fu_2171_p2 = (($signed(add_ln692_2_fu_2150_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_3_fu_2198_p2 = (($signed(add_ln692_3_fu_2177_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_4_fu_2225_p2 = (($signed(add_ln692_4_fu_2204_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_5_fu_2252_p2 = (($signed(add_ln692_5_fu_2231_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_6_fu_2279_p2 = (($signed(add_ln692_6_fu_2258_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_7_fu_2306_p2 = (($signed(add_ln692_7_fu_2285_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_8_fu_2333_p2 = (($signed(add_ln692_8_fu_2312_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_9_fu_2360_p2 = (($signed(add_ln692_9_fu_2339_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln878_fu_2117_p2 = (($signed(add_ln692_fu_2096_p2) < $signed(24'd16777088)) ? 1'b1 : 1'b0);

assign icmp_ln886_10_fu_2381_p2 = (($signed(tmp_36_fu_2371_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_11_fu_2408_p2 = (($signed(tmp_38_fu_2398_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_12_fu_2435_p2 = (($signed(tmp_40_fu_2425_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_13_fu_2462_p2 = (($signed(tmp_42_fu_2452_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_14_fu_2489_p2 = (($signed(tmp_44_fu_2479_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_15_fu_2516_p2 = (($signed(tmp_46_fu_2506_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_1_fu_2138_p2 = (($signed(tmp_18_fu_2128_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_2_fu_2165_p2 = (($signed(tmp_20_fu_2155_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_3_fu_2192_p2 = (($signed(tmp_22_fu_2182_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_4_fu_2219_p2 = (($signed(tmp_24_fu_2209_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_5_fu_2246_p2 = (($signed(tmp_26_fu_2236_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_6_fu_2273_p2 = (($signed(tmp_28_fu_2263_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_7_fu_2300_p2 = (($signed(tmp_30_fu_2290_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_8_fu_2327_p2 = (($signed(tmp_32_fu_2317_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_9_fu_2354_p2 = (($signed(tmp_34_fu_2344_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign icmp_ln886_fu_2111_p2 = (($signed(tmp_16_fu_2101_p4) > $signed(17'd0)) ? 1'b1 : 1'b0);

assign or_ln69_10_fu_2824_p2 = (icmp_ln886_10_reg_3853 | icmp_ln878_10_reg_3859);

assign or_ln69_11_fu_2852_p2 = (icmp_ln886_11_reg_3864 | icmp_ln878_11_reg_3870);

assign or_ln69_12_fu_2880_p2 = (icmp_ln886_12_reg_3875 | icmp_ln878_12_reg_3881);

assign or_ln69_13_fu_2908_p2 = (icmp_ln886_13_reg_3886 | icmp_ln878_13_reg_3892);

assign or_ln69_14_fu_2936_p2 = (icmp_ln886_14_reg_3897 | icmp_ln878_14_reg_3903);

assign or_ln69_15_fu_2964_p2 = (icmp_ln886_15_reg_3908 | icmp_ln878_15_reg_3914);

assign or_ln69_1_fu_2572_p2 = (icmp_ln886_1_reg_3754 | icmp_ln878_1_reg_3760);

assign or_ln69_2_fu_2600_p2 = (icmp_ln886_2_reg_3765 | icmp_ln878_2_reg_3771);

assign or_ln69_3_fu_2628_p2 = (icmp_ln886_3_reg_3776 | icmp_ln878_3_reg_3782);

assign or_ln69_4_fu_2656_p2 = (icmp_ln886_4_reg_3787 | icmp_ln878_4_reg_3793);

assign or_ln69_5_fu_2684_p2 = (icmp_ln886_5_reg_3798 | icmp_ln878_5_reg_3804);

assign or_ln69_6_fu_2712_p2 = (icmp_ln886_6_reg_3809 | icmp_ln878_6_reg_3815);

assign or_ln69_7_fu_2740_p2 = (icmp_ln886_7_reg_3820 | icmp_ln878_7_reg_3826);

assign or_ln69_8_fu_2768_p2 = (icmp_ln886_8_reg_3831 | icmp_ln878_8_reg_3837);

assign or_ln69_9_fu_2796_p2 = (icmp_ln886_9_reg_3842 | icmp_ln878_9_reg_3848);

assign or_ln69_fu_2544_p2 = (icmp_ln886_reg_3743 | icmp_ln878_reg_3749);

assign p_Result_1_10_i_i_fu_789_p4 = {{s_scale_dout[191:176]}};

assign p_Result_1_11_i_i_fu_817_p4 = {{s_scale_dout[207:192]}};

assign p_Result_1_12_i_i_fu_845_p4 = {{s_scale_dout[223:208]}};

assign p_Result_1_13_i_i_fu_873_p4 = {{s_scale_dout[239:224]}};

assign p_Result_1_14_i_i_fu_901_p4 = {{s_scale_dout[255:240]}};

assign p_Result_1_1_i_i_fu_509_p4 = {{s_scale_dout[31:16]}};

assign p_Result_1_2_i_i_fu_537_p4 = {{s_scale_dout[47:32]}};

assign p_Result_1_3_i_i_fu_565_p4 = {{s_scale_dout[63:48]}};

assign p_Result_1_4_i_i_fu_593_p4 = {{s_scale_dout[79:64]}};

assign p_Result_1_5_i_i_fu_621_p4 = {{s_scale_dout[95:80]}};

assign p_Result_1_6_i_i_fu_649_p4 = {{s_scale_dout[111:96]}};

assign p_Result_1_7_i_i_fu_677_p4 = {{s_scale_dout[127:112]}};

assign p_Result_1_8_i_i_fu_705_p4 = {{s_scale_dout[143:128]}};

assign p_Result_1_9_i_i_fu_733_p4 = {{s_scale_dout[159:144]}};

assign p_Result_1_i_i_fu_761_p4 = {{s_scale_dout[175:160]}};

assign p_Result_4_i_i_fu_2976_p17 = {{{{{{{{{{{{{{{{select_ln69_31_fu_2968_p3}, {select_ln69_29_fu_2940_p3}}, {select_ln69_27_fu_2912_p3}}, {select_ln69_25_fu_2884_p3}}, {select_ln69_23_fu_2856_p3}}, {select_ln69_21_fu_2828_p3}}, {select_ln69_19_fu_2800_p3}}, {select_ln69_17_fu_2772_p3}}, {select_ln69_15_fu_2744_p3}}, {select_ln69_13_fu_2716_p3}}, {select_ln69_11_fu_2688_p3}}, {select_ln69_9_fu_2660_p3}}, {select_ln69_7_fu_2632_p3}}, {select_ln69_5_fu_2604_p3}}, {select_ln69_3_fu_2576_p3}}, {select_ln69_1_fu_2548_p3}};

assign p_Result_i_i_fu_1083_p17 = {{{{{{{{{{{{{{{{trunc_ln69_14_fu_1073_p4}, {trunc_ln69_13_fu_1063_p4}}, {trunc_ln69_12_fu_1053_p4}}, {trunc_ln69_11_fu_1043_p4}}, {trunc_ln69_10_fu_1033_p4}}, {trunc_ln69_s_fu_1023_p4}}, {trunc_ln69_9_fu_1013_p4}}, {trunc_ln69_8_fu_1003_p4}}, {trunc_ln69_7_fu_993_p4}}, {trunc_ln69_6_fu_983_p4}}, {trunc_ln69_5_fu_973_p4}}, {trunc_ln69_4_fu_963_p4}}, {trunc_ln69_3_fu_953_p4}}, {trunc_ln69_2_fu_943_p4}}, {trunc_ln69_1_fu_933_p4}}, {trunc_ln69_fu_929_p1}};

assign select_ln263_10_fu_1874_p3 = ((relu_reg_3177[0:0] == 1'b1) ? zext_ln299_10_fu_1870_p1 : add_ln691_21_fu_1844_p2);

assign select_ln263_11_fu_1917_p3 = ((relu_reg_3177[0:0] == 1'b1) ? zext_ln299_11_fu_1913_p1 : add_ln691_23_fu_1887_p2);

assign select_ln263_12_fu_1960_p3 = ((relu_reg_3177[0:0] == 1'b1) ? zext_ln299_12_fu_1956_p1 : add_ln691_25_fu_1930_p2);

assign select_ln263_13_fu_2003_p3 = ((relu_reg_3177[0:0] == 1'b1) ? zext_ln299_13_fu_1999_p1 : add_ln691_27_fu_1973_p2);

assign select_ln263_14_fu_2046_p3 = ((relu_reg_3177[0:0] == 1'b1) ? zext_ln299_14_fu_2042_p1 : add_ln691_29_fu_2016_p2);

assign select_ln263_15_fu_2089_p3 = ((relu_reg_3177[0:0] == 1'b1) ? zext_ln299_15_fu_2085_p1 : add_ln691_31_fu_2059_p2);

assign select_ln263_1_fu_1487_p3 = ((relu_reg_3177[0:0] == 1'b1) ? zext_ln299_1_fu_1483_p1 : add_ln691_3_fu_1457_p2);

assign select_ln263_2_fu_1530_p3 = ((relu_reg_3177[0:0] == 1'b1) ? zext_ln299_2_fu_1526_p1 : add_ln691_5_fu_1500_p2);

assign select_ln263_3_fu_1573_p3 = ((relu_reg_3177[0:0] == 1'b1) ? zext_ln299_3_fu_1569_p1 : add_ln691_7_fu_1543_p2);

assign select_ln263_4_fu_1616_p3 = ((relu_reg_3177[0:0] == 1'b1) ? zext_ln299_4_fu_1612_p1 : add_ln691_9_fu_1586_p2);

assign select_ln263_5_fu_1659_p3 = ((relu_reg_3177[0:0] == 1'b1) ? zext_ln299_5_fu_1655_p1 : add_ln691_11_fu_1629_p2);

assign select_ln263_6_fu_1702_p3 = ((relu_reg_3177[0:0] == 1'b1) ? zext_ln299_6_fu_1698_p1 : add_ln691_13_fu_1672_p2);

assign select_ln263_7_fu_1745_p3 = ((relu_reg_3177[0:0] == 1'b1) ? zext_ln299_7_fu_1741_p1 : add_ln691_15_fu_1715_p2);

assign select_ln263_8_fu_1788_p3 = ((relu_reg_3177[0:0] == 1'b1) ? zext_ln299_8_fu_1784_p1 : add_ln691_17_fu_1758_p2);

assign select_ln263_9_fu_1831_p3 = ((relu_reg_3177[0:0] == 1'b1) ? zext_ln299_9_fu_1827_p1 : add_ln691_19_fu_1801_p2);

assign select_ln263_fu_1444_p3 = ((relu_reg_3177[0:0] == 1'b1) ? zext_ln299_fu_1440_p1 : add_ln691_1_fu_1414_p2);

assign select_ln298_10_fu_1862_p3 = ((tmp_35_fu_1854_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_10_fu_1849_p2);

assign select_ln298_11_fu_1905_p3 = ((tmp_37_fu_1897_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_11_fu_1892_p2);

assign select_ln298_12_fu_1948_p3 = ((tmp_39_fu_1940_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_12_fu_1935_p2);

assign select_ln298_13_fu_1991_p3 = ((tmp_41_fu_1983_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_13_fu_1978_p2);

assign select_ln298_14_fu_2034_p3 = ((tmp_43_fu_2026_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_14_fu_2021_p2);

assign select_ln298_15_fu_2077_p3 = ((tmp_45_fu_2069_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_15_fu_2064_p2);

assign select_ln298_1_fu_1475_p3 = ((tmp_17_fu_1467_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_1_fu_1462_p2);

assign select_ln298_2_fu_1518_p3 = ((tmp_19_fu_1510_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_2_fu_1505_p2);

assign select_ln298_3_fu_1561_p3 = ((tmp_21_fu_1553_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_3_fu_1548_p2);

assign select_ln298_4_fu_1604_p3 = ((tmp_23_fu_1596_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_4_fu_1591_p2);

assign select_ln298_5_fu_1647_p3 = ((tmp_25_fu_1639_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_5_fu_1634_p2);

assign select_ln298_6_fu_1690_p3 = ((tmp_27_fu_1682_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_6_fu_1677_p2);

assign select_ln298_7_fu_1733_p3 = ((tmp_29_fu_1725_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_7_fu_1720_p2);

assign select_ln298_8_fu_1776_p3 = ((tmp_31_fu_1768_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_8_fu_1763_p2);

assign select_ln298_9_fu_1819_p3 = ((tmp_33_fu_1811_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_9_fu_1806_p2);

assign select_ln298_fu_1432_p3 = ((tmp_15_fu_1424_p3[0:0] == 1'b1) ? 23'd0 : add_ln297_fu_1419_p2);

assign select_ln69_10_fu_2677_p3 = ((icmp_ln886_5_reg_3798[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_11_fu_2688_p3 = ((or_ln69_5_fu_2684_p2[0:0] == 1'b1) ? select_ln69_10_fu_2677_p3 : xor_ln69_5_fu_2671_p2);

assign select_ln69_12_fu_2705_p3 = ((icmp_ln886_6_reg_3809[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_13_fu_2716_p3 = ((or_ln69_6_fu_2712_p2[0:0] == 1'b1) ? select_ln69_12_fu_2705_p3 : xor_ln69_6_fu_2699_p2);

assign select_ln69_14_fu_2733_p3 = ((icmp_ln886_7_reg_3820[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_15_fu_2744_p3 = ((or_ln69_7_fu_2740_p2[0:0] == 1'b1) ? select_ln69_14_fu_2733_p3 : xor_ln69_7_fu_2727_p2);

assign select_ln69_16_fu_2761_p3 = ((icmp_ln886_8_reg_3831[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_17_fu_2772_p3 = ((or_ln69_8_fu_2768_p2[0:0] == 1'b1) ? select_ln69_16_fu_2761_p3 : xor_ln69_8_fu_2755_p2);

assign select_ln69_18_fu_2789_p3 = ((icmp_ln886_9_reg_3842[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_19_fu_2800_p3 = ((or_ln69_9_fu_2796_p2[0:0] == 1'b1) ? select_ln69_18_fu_2789_p3 : xor_ln69_9_fu_2783_p2);

assign select_ln69_1_fu_2548_p3 = ((or_ln69_fu_2544_p2[0:0] == 1'b1) ? select_ln69_fu_2537_p3 : xor_ln69_fu_2531_p2);

assign select_ln69_20_fu_2817_p3 = ((icmp_ln886_10_reg_3853[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_21_fu_2828_p3 = ((or_ln69_10_fu_2824_p2[0:0] == 1'b1) ? select_ln69_20_fu_2817_p3 : xor_ln69_10_fu_2811_p2);

assign select_ln69_22_fu_2845_p3 = ((icmp_ln886_11_reg_3864[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_23_fu_2856_p3 = ((or_ln69_11_fu_2852_p2[0:0] == 1'b1) ? select_ln69_22_fu_2845_p3 : xor_ln69_11_fu_2839_p2);

assign select_ln69_24_fu_2873_p3 = ((icmp_ln886_12_reg_3875[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_25_fu_2884_p3 = ((or_ln69_12_fu_2880_p2[0:0] == 1'b1) ? select_ln69_24_fu_2873_p3 : xor_ln69_12_fu_2867_p2);

assign select_ln69_26_fu_2901_p3 = ((icmp_ln886_13_reg_3886[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_27_fu_2912_p3 = ((or_ln69_13_fu_2908_p2[0:0] == 1'b1) ? select_ln69_26_fu_2901_p3 : xor_ln69_13_fu_2895_p2);

assign select_ln69_28_fu_2929_p3 = ((icmp_ln886_14_reg_3897[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_29_fu_2940_p3 = ((or_ln69_14_fu_2936_p2[0:0] == 1'b1) ? select_ln69_28_fu_2929_p3 : xor_ln69_14_fu_2923_p2);

assign select_ln69_2_fu_2565_p3 = ((icmp_ln886_1_reg_3754[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_30_fu_2957_p3 = ((icmp_ln886_15_reg_3908[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_31_fu_2968_p3 = ((or_ln69_15_fu_2964_p2[0:0] == 1'b1) ? select_ln69_30_fu_2957_p3 : xor_ln69_15_fu_2951_p2);

assign select_ln69_3_fu_2576_p3 = ((or_ln69_1_fu_2572_p2[0:0] == 1'b1) ? select_ln69_2_fu_2565_p3 : xor_ln69_1_fu_2559_p2);

assign select_ln69_4_fu_2593_p3 = ((icmp_ln886_2_reg_3765[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_5_fu_2604_p3 = ((or_ln69_2_fu_2600_p2[0:0] == 1'b1) ? select_ln69_4_fu_2593_p3 : xor_ln69_2_fu_2587_p2);

assign select_ln69_6_fu_2621_p3 = ((icmp_ln886_3_reg_3776[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_7_fu_2632_p3 = ((or_ln69_3_fu_2628_p2[0:0] == 1'b1) ? select_ln69_6_fu_2621_p3 : xor_ln69_3_fu_2615_p2);

assign select_ln69_8_fu_2649_p3 = ((icmp_ln886_4_reg_3787[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln69_9_fu_2660_p3 = ((or_ln69_4_fu_2656_p2[0:0] == 1'b1) ? select_ln69_8_fu_2649_p3 : xor_ln69_4_fu_2643_p2);

assign select_ln69_fu_2537_p3 = ((icmp_ln886_reg_3743[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign sext_ln691_10_fu_1838_p1 = p_Result_2_i_i_reg_3391_pp0_iter4_reg;

assign sext_ln691_11_fu_1881_p1 = p_Result_2_10_i_i_reg_3407_pp0_iter4_reg;

assign sext_ln691_12_fu_1924_p1 = p_Result_2_11_i_i_reg_3423_pp0_iter4_reg;

assign sext_ln691_13_fu_1967_p1 = p_Result_2_12_i_i_reg_3439_pp0_iter4_reg;

assign sext_ln691_14_fu_2010_p1 = p_Result_2_13_i_i_reg_3455_pp0_iter4_reg;

assign sext_ln691_15_fu_2053_p1 = p_Result_2_14_i_i_reg_3471_pp0_iter4_reg;

assign sext_ln691_16_fu_1411_p1 = trunc_ln674_1_reg_3231_pp0_iter4_reg;

assign sext_ln691_17_fu_1454_p1 = p_Result_2_1_i_i_reg_3247_pp0_iter4_reg;

assign sext_ln691_18_fu_1497_p1 = p_Result_2_2_i_i_reg_3263_pp0_iter4_reg;

assign sext_ln691_19_fu_1540_p1 = p_Result_2_3_i_i_reg_3279_pp0_iter4_reg;

assign sext_ln691_1_fu_1451_p1 = p_Result_2_1_i_i_reg_3247_pp0_iter4_reg;

assign sext_ln691_20_fu_1583_p1 = p_Result_2_4_i_i_reg_3295_pp0_iter4_reg;

assign sext_ln691_21_fu_1626_p1 = p_Result_2_5_i_i_reg_3311_pp0_iter4_reg;

assign sext_ln691_22_fu_1669_p1 = p_Result_2_6_i_i_reg_3327_pp0_iter4_reg;

assign sext_ln691_23_fu_1712_p1 = p_Result_2_7_i_i_reg_3343_pp0_iter4_reg;

assign sext_ln691_24_fu_1755_p1 = p_Result_2_8_i_i_reg_3359_pp0_iter4_reg;

assign sext_ln691_25_fu_1798_p1 = p_Result_2_9_i_i_reg_3375_pp0_iter4_reg;

assign sext_ln691_26_fu_1841_p1 = p_Result_2_i_i_reg_3391_pp0_iter4_reg;

assign sext_ln691_27_fu_1884_p1 = p_Result_2_10_i_i_reg_3407_pp0_iter4_reg;

assign sext_ln691_28_fu_1927_p1 = p_Result_2_11_i_i_reg_3423_pp0_iter4_reg;

assign sext_ln691_29_fu_1970_p1 = p_Result_2_12_i_i_reg_3439_pp0_iter4_reg;

assign sext_ln691_2_fu_1494_p1 = p_Result_2_2_i_i_reg_3263_pp0_iter4_reg;

assign sext_ln691_30_fu_2013_p1 = p_Result_2_13_i_i_reg_3455_pp0_iter4_reg;

assign sext_ln691_31_fu_2056_p1 = p_Result_2_14_i_i_reg_3471_pp0_iter4_reg;

assign sext_ln691_3_fu_1537_p1 = p_Result_2_3_i_i_reg_3279_pp0_iter4_reg;

assign sext_ln691_4_fu_1580_p1 = p_Result_2_4_i_i_reg_3295_pp0_iter4_reg;

assign sext_ln691_5_fu_1623_p1 = p_Result_2_5_i_i_reg_3311_pp0_iter4_reg;

assign sext_ln691_6_fu_1666_p1 = p_Result_2_6_i_i_reg_3327_pp0_iter4_reg;

assign sext_ln691_7_fu_1709_p1 = p_Result_2_7_i_i_reg_3343_pp0_iter4_reg;

assign sext_ln691_8_fu_1752_p1 = p_Result_2_8_i_i_reg_3359_pp0_iter4_reg;

assign sext_ln691_9_fu_1795_p1 = p_Result_2_9_i_i_reg_3375_pp0_iter4_reg;

assign sext_ln691_fu_1408_p1 = trunc_ln674_1_reg_3231_pp0_iter4_reg;

assign tmp_15_fu_1424_p3 = add_ln691_1_fu_1414_p2[32'd23];

assign tmp_16_fu_2101_p4 = {{add_ln692_fu_2096_p2[23:7]}};

assign tmp_17_fu_1467_p3 = add_ln691_3_fu_1457_p2[32'd23];

assign tmp_18_fu_2128_p4 = {{add_ln692_1_fu_2123_p2[23:7]}};

assign tmp_19_fu_1510_p3 = add_ln691_5_fu_1500_p2[32'd23];

assign tmp_20_fu_2155_p4 = {{add_ln692_2_fu_2150_p2[23:7]}};

assign tmp_21_fu_1553_p3 = add_ln691_7_fu_1543_p2[32'd23];

assign tmp_22_fu_2182_p4 = {{add_ln692_3_fu_2177_p2[23:7]}};

assign tmp_23_fu_1596_p3 = add_ln691_9_fu_1586_p2[32'd23];

assign tmp_24_fu_2209_p4 = {{add_ln692_4_fu_2204_p2[23:7]}};

assign tmp_25_fu_1639_p3 = add_ln691_11_fu_1629_p2[32'd23];

assign tmp_26_fu_2236_p4 = {{add_ln692_5_fu_2231_p2[23:7]}};

assign tmp_27_fu_1682_p3 = add_ln691_13_fu_1672_p2[32'd23];

assign tmp_28_fu_2263_p4 = {{add_ln692_6_fu_2258_p2[23:7]}};

assign tmp_29_fu_1725_p3 = add_ln691_15_fu_1715_p2[32'd23];

assign tmp_30_fu_2290_p4 = {{add_ln692_7_fu_2285_p2[23:7]}};

assign tmp_31_fu_1768_p3 = add_ln691_17_fu_1758_p2[32'd23];

assign tmp_32_fu_2317_p4 = {{add_ln692_8_fu_2312_p2[23:7]}};

assign tmp_33_fu_1811_p3 = add_ln691_19_fu_1801_p2[32'd23];

assign tmp_34_fu_2344_p4 = {{add_ln692_9_fu_2339_p2[23:7]}};

assign tmp_35_fu_1854_p3 = add_ln691_21_fu_1844_p2[32'd23];

assign tmp_36_fu_2371_p4 = {{add_ln692_10_fu_2366_p2[23:7]}};

assign tmp_37_fu_1897_p3 = add_ln691_23_fu_1887_p2[32'd23];

assign tmp_38_fu_2398_p4 = {{add_ln692_11_fu_2393_p2[23:7]}};

assign tmp_39_fu_1940_p3 = add_ln691_25_fu_1930_p2[32'd23];

assign tmp_40_fu_2425_p4 = {{add_ln692_12_fu_2420_p2[23:7]}};

assign tmp_41_fu_1983_p3 = add_ln691_27_fu_1973_p2[32'd23];

assign tmp_42_fu_2452_p4 = {{add_ln692_13_fu_2447_p2[23:7]}};

assign tmp_43_fu_2026_p3 = add_ln691_29_fu_2016_p2[32'd23];

assign tmp_44_fu_2479_p4 = {{add_ln692_14_fu_2474_p2[23:7]}};

assign tmp_45_fu_2069_p3 = add_ln691_31_fu_2059_p2[32'd23];

assign tmp_46_fu_2506_p4 = {{add_ln692_15_fu_2501_p2[23:7]}};

assign tmp_data_V_0_fu_339_p1 = s_conv1_dout[23:0];

assign tmp_data_V_10_fu_433_p4 = {{s_conv1_dout[343:320]}};

assign tmp_data_V_11_fu_443_p4 = {{s_conv1_dout[375:352]}};

assign tmp_data_V_12_fu_453_p4 = {{s_conv1_dout[407:384]}};

assign tmp_data_V_13_fu_463_p4 = {{s_conv1_dout[439:416]}};

assign tmp_data_V_14_fu_473_p4 = {{s_conv1_dout[471:448]}};

assign tmp_data_V_15_fu_483_p4 = {{s_conv1_dout[503:480]}};

assign tmp_data_V_1_fu_343_p4 = {{s_conv1_dout[55:32]}};

assign tmp_data_V_2_fu_353_p4 = {{s_conv1_dout[87:64]}};

assign tmp_data_V_3_fu_363_p4 = {{s_conv1_dout[119:96]}};

assign tmp_data_V_4_fu_373_p4 = {{s_conv1_dout[151:128]}};

assign tmp_data_V_5_fu_383_p4 = {{s_conv1_dout[183:160]}};

assign tmp_data_V_6_fu_393_p4 = {{s_conv1_dout[215:192]}};

assign tmp_data_V_7_fu_403_p4 = {{s_conv1_dout[247:224]}};

assign tmp_data_V_8_fu_413_p4 = {{s_conv1_dout[279:256]}};

assign tmp_data_V_9_fu_423_p4 = {{s_conv1_dout[311:288]}};

assign trunc_ln674_1_fu_497_p1 = s_bias_dout[15:0];

assign trunc_ln674_fu_493_p1 = s_scale_dout[15:0];

assign trunc_ln692_10_fu_2808_p1 = select_ln263_10_reg_3707_pp0_iter6_reg[7:0];

assign trunc_ln692_11_fu_2836_p1 = select_ln263_11_reg_3713_pp0_iter6_reg[7:0];

assign trunc_ln692_12_fu_2864_p1 = select_ln263_12_reg_3719_pp0_iter6_reg[7:0];

assign trunc_ln692_13_fu_2892_p1 = select_ln263_13_reg_3725_pp0_iter6_reg[7:0];

assign trunc_ln692_14_fu_2920_p1 = select_ln263_14_reg_3731_pp0_iter6_reg[7:0];

assign trunc_ln692_15_fu_2948_p1 = select_ln263_15_reg_3737_pp0_iter6_reg[7:0];

assign trunc_ln692_1_fu_2556_p1 = select_ln263_1_reg_3653_pp0_iter6_reg[7:0];

assign trunc_ln692_2_fu_2584_p1 = select_ln263_2_reg_3659_pp0_iter6_reg[7:0];

assign trunc_ln692_3_fu_2612_p1 = select_ln263_3_reg_3665_pp0_iter6_reg[7:0];

assign trunc_ln692_4_fu_2640_p1 = select_ln263_4_reg_3671_pp0_iter6_reg[7:0];

assign trunc_ln692_5_fu_2668_p1 = select_ln263_5_reg_3677_pp0_iter6_reg[7:0];

assign trunc_ln692_6_fu_2696_p1 = select_ln263_6_reg_3683_pp0_iter6_reg[7:0];

assign trunc_ln692_7_fu_2724_p1 = select_ln263_7_reg_3689_pp0_iter6_reg[7:0];

assign trunc_ln692_8_fu_2752_p1 = select_ln263_8_reg_3695_pp0_iter6_reg[7:0];

assign trunc_ln692_9_fu_2780_p1 = select_ln263_9_reg_3701_pp0_iter6_reg[7:0];

assign trunc_ln692_fu_2528_p1 = select_ln263_reg_3647_pp0_iter6_reg[7:0];

assign trunc_ln69_10_fu_1033_p4 = {{s_conv1_dout[359:352]}};

assign trunc_ln69_11_fu_1043_p4 = {{s_conv1_dout[391:384]}};

assign trunc_ln69_12_fu_1053_p4 = {{s_conv1_dout[423:416]}};

assign trunc_ln69_13_fu_1063_p4 = {{s_conv1_dout[455:448]}};

assign trunc_ln69_14_fu_1073_p4 = {{s_conv1_dout[487:480]}};

assign trunc_ln69_1_fu_933_p4 = {{s_conv1_dout[39:32]}};

assign trunc_ln69_2_fu_943_p4 = {{s_conv1_dout[71:64]}};

assign trunc_ln69_3_fu_953_p4 = {{s_conv1_dout[103:96]}};

assign trunc_ln69_4_fu_963_p4 = {{s_conv1_dout[135:128]}};

assign trunc_ln69_5_fu_973_p4 = {{s_conv1_dout[167:160]}};

assign trunc_ln69_6_fu_983_p4 = {{s_conv1_dout[199:192]}};

assign trunc_ln69_7_fu_993_p4 = {{s_conv1_dout[231:224]}};

assign trunc_ln69_8_fu_1003_p4 = {{s_conv1_dout[263:256]}};

assign trunc_ln69_9_fu_1013_p4 = {{s_conv1_dout[295:288]}};

assign trunc_ln69_fu_929_p1 = s_conv1_dout[7:0];

assign trunc_ln69_s_fu_1023_p4 = {{s_conv1_dout[327:320]}};

assign xor_ln69_10_fu_2811_p2 = (trunc_ln692_10_fu_2808_p1 ^ 8'd128);

assign xor_ln69_11_fu_2839_p2 = (trunc_ln692_11_fu_2836_p1 ^ 8'd128);

assign xor_ln69_12_fu_2867_p2 = (trunc_ln692_12_fu_2864_p1 ^ 8'd128);

assign xor_ln69_13_fu_2895_p2 = (trunc_ln692_13_fu_2892_p1 ^ 8'd128);

assign xor_ln69_14_fu_2923_p2 = (trunc_ln692_14_fu_2920_p1 ^ 8'd128);

assign xor_ln69_15_fu_2951_p2 = (trunc_ln692_15_fu_2948_p1 ^ 8'd128);

assign xor_ln69_1_fu_2559_p2 = (trunc_ln692_1_fu_2556_p1 ^ 8'd128);

assign xor_ln69_2_fu_2587_p2 = (trunc_ln692_2_fu_2584_p1 ^ 8'd128);

assign xor_ln69_3_fu_2615_p2 = (trunc_ln692_3_fu_2612_p1 ^ 8'd128);

assign xor_ln69_4_fu_2643_p2 = (trunc_ln692_4_fu_2640_p1 ^ 8'd128);

assign xor_ln69_5_fu_2671_p2 = (trunc_ln692_5_fu_2668_p1 ^ 8'd128);

assign xor_ln69_6_fu_2699_p2 = (trunc_ln692_6_fu_2696_p1 ^ 8'd128);

assign xor_ln69_7_fu_2727_p2 = (trunc_ln692_7_fu_2724_p1 ^ 8'd128);

assign xor_ln69_8_fu_2755_p2 = (trunc_ln692_8_fu_2752_p1 ^ 8'd128);

assign xor_ln69_9_fu_2783_p2 = (trunc_ln692_9_fu_2780_p1 ^ 8'd128);

assign xor_ln69_fu_2531_p2 = (trunc_ln692_fu_2528_p1 ^ 8'd128);

assign zext_ln299_10_fu_1870_p1 = select_ln298_10_fu_1862_p3;

assign zext_ln299_11_fu_1913_p1 = select_ln298_11_fu_1905_p3;

assign zext_ln299_12_fu_1956_p1 = select_ln298_12_fu_1948_p3;

assign zext_ln299_13_fu_1999_p1 = select_ln298_13_fu_1991_p3;

assign zext_ln299_14_fu_2042_p1 = select_ln298_14_fu_2034_p3;

assign zext_ln299_15_fu_2085_p1 = select_ln298_15_fu_2077_p3;

assign zext_ln299_1_fu_1483_p1 = select_ln298_1_fu_1475_p3;

assign zext_ln299_2_fu_1526_p1 = select_ln298_2_fu_1518_p3;

assign zext_ln299_3_fu_1569_p1 = select_ln298_3_fu_1561_p3;

assign zext_ln299_4_fu_1612_p1 = select_ln298_4_fu_1604_p3;

assign zext_ln299_5_fu_1655_p1 = select_ln298_5_fu_1647_p3;

assign zext_ln299_6_fu_1698_p1 = select_ln298_6_fu_1690_p3;

assign zext_ln299_7_fu_1741_p1 = select_ln298_7_fu_1733_p3;

assign zext_ln299_8_fu_1784_p1 = select_ln298_8_fu_1776_p3;

assign zext_ln299_9_fu_1827_p1 = select_ln298_9_fu_1819_p3;

assign zext_ln299_fu_1440_p1 = select_ln298_fu_1432_p3;

endmodule //top_quantize_mul_shift_24_8_16_16_16_16_23
