// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module top_Block_split7793_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        D_dout,
        D_empty_n,
        D_read,
        IC_dout,
        IC_empty_n,
        IC_read,
        batch_dout,
        batch_empty_n,
        batch_read,
        ap_return
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_state6 = 13'd32;
parameter    ap_ST_fsm_state7 = 13'd64;
parameter    ap_ST_fsm_state8 = 13'd128;
parameter    ap_ST_fsm_state9 = 13'd256;
parameter    ap_ST_fsm_state10 = 13'd512;
parameter    ap_ST_fsm_state11 = 13'd1024;
parameter    ap_ST_fsm_state12 = 13'd2048;
parameter    ap_ST_fsm_state13 = 13'd4096;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [31:0] D_dout;
input   D_empty_n;
output   D_read;
input  [31:0] IC_dout;
input   IC_empty_n;
output   IC_read;
input  [31:0] batch_dout;
input   batch_empty_n;
output   batch_read;
output  [28:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg D_read;
reg IC_read;
reg batch_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    D_blk_n;
reg    IC_blk_n;
reg    batch_blk_n;
reg  signed [31:0] D_read_reg_114;
reg  signed [31:0] IC_read_reg_120;
reg  signed [31:0] batch_read_reg_125;
wire  signed [31:0] grp_fu_50_p2;
reg  signed [31:0] mul_ln160_reg_130;
wire    ap_CS_fsm_state6;
wire  signed [31:0] grp_fu_54_p2;
reg  signed [31:0] mul_ln160_1_reg_135;
wire   [31:0] grp_fu_58_p2;
reg   [31:0] mul_ln160_2_reg_140;
wire    ap_CS_fsm_state11;
reg   [0:0] tmp_reg_145;
reg   [27:0] trunc_ln160_2_reg_150;
reg   [27:0] trunc_ln160_1_reg_155;
wire    ap_CS_fsm_state12;
reg    ap_block_state1;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state7;
wire   [31:0] sub_ln160_fu_80_p2;
wire    ap_CS_fsm_state13;
wire   [28:0] zext_ln160_fu_95_p1;
wire   [28:0] sub_ln160_1_fu_98_p2;
wire   [28:0] zext_ln160_1_fu_104_p1;
reg   [12:0] ap_NS_fsm;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 13'd1;
end

top_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U65(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(D_read_reg_114),
    .din1(IC_read_reg_120),
    .ce(1'b1),
    .dout(grp_fu_50_p2)
);

top_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U66(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(D_read_reg_114),
    .din1(batch_read_reg_125),
    .ce(1'b1),
    .dout(grp_fu_54_p2)
);

top_mul_32s_32s_32_5_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_5_1_U67(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mul_ln160_1_reg_135),
    .din1(mul_ln160_reg_130),
    .ce(1'b1),
    .dout(grp_fu_58_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state13)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        D_read_reg_114 <= D_dout;
        IC_read_reg_120 <= IC_dout;
        batch_read_reg_125 <= batch_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        mul_ln160_1_reg_135 <= grp_fu_54_p2;
        mul_ln160_reg_130 <= grp_fu_50_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        mul_ln160_2_reg_140 <= grp_fu_58_p2;
        tmp_reg_145 <= grp_fu_58_p2[32'd31];
        trunc_ln160_2_reg_150 <= {{grp_fu_58_p2[31:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_reg_145 == 1'd1) & (1'b1 == ap_CS_fsm_state12))) begin
        trunc_ln160_1_reg_155 <= {{sub_ln160_fu_80_p2[31:4]}};
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        D_blk_n = D_empty_n;
    end else begin
        D_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((batch_empty_n == 1'b0) | (1'b0 == IC_empty_n) | (1'b0 == D_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        D_read = 1'b1;
    end else begin
        D_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        IC_blk_n = IC_empty_n;
    end else begin
        IC_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((batch_empty_n == 1'b0) | (1'b0 == IC_empty_n) | (1'b0 == D_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        IC_read = 1'b1;
    end else begin
        IC_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        batch_blk_n = batch_empty_n;
    end else begin
        batch_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((batch_empty_n == 1'b0) | (1'b0 == IC_empty_n) | (1'b0 == D_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        batch_read = 1'b1;
    end else begin
        batch_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((batch_empty_n == 1'b0) | (1'b0 == IC_empty_n) | (1'b0 == D_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state1 = ((batch_empty_n == 1'b0) | (1'b0 == IC_empty_n) | (1'b0 == D_empty_n) | (ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_return = ((tmp_reg_145[0:0] == 1'b1) ? sub_ln160_1_fu_98_p2 : zext_ln160_1_fu_104_p1);

assign sub_ln160_1_fu_98_p2 = (29'd0 - zext_ln160_fu_95_p1);

assign sub_ln160_fu_80_p2 = (32'd0 - mul_ln160_2_reg_140);

assign zext_ln160_1_fu_104_p1 = trunc_ln160_2_reg_150;

assign zext_ln160_fu_95_p1 = trunc_ln160_1_reg_155;

endmodule //top_Block_split7793_proc
